# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='instrumentdatasession',
            new_name='t_instrumen_subject_57a249_idx',
            old_name='lims_int_subj_time_idx',
        ),
        migrations.RenameIndex(
            model_name='instrumentdatasession',
            new_name='t_instrumen_instrum_f2d6b3_idx',
            old_name='lims_int_type_time_idx',
        ),
        migrations.RenameIndex(
            model_name='instrumentdatasession',
            new_name='t_instrumen_operato_7ba303_idx',
            old_name='lims_int_operator_idx',
        ),
        migrations.RenameIndex(
            model_name='instrumentmeasurement',
            new_name='t_instrumen_session_e8b332_idx',
            old_name='lims_meas_session_metric_idx',
        ),
        migrations.AlterField(
            model_name='instrumentdatasession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instrumentmeasurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='limsconnection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='limssynclog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
