# Generated by Django 4.2.27 on 2026-02-18 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocol', '0006_p2_recruitment_tables'),
        ('crm', '0003_alter_client_feishu_project_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='会议标题')),
                ('meeting_type', models.CharField(choices=[('kickoff', '启动会'), ('weekly', '周会'), ('review', '评审会'), ('client', '客户会议'), ('other', '其他')], default='other', max_length=30, verbose_name='会议类型')),
                ('scheduled_date', models.DateTimeField(verbose_name='计划时间')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='时长(分钟)')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='地点')),
                ('participants', models.JSONField(blank=True, default=list, verbose_name='参会人')),
                ('feishu_calendar_event_id', models.CharField(blank=True, max_length=200, verbose_name='飞书日历事件ID')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='状态')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='protocol.protocol')),
            ],
            options={
                'db_table': 't_meeting',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='方案标题')),
                ('status', models.CharField(choices=[('drafting', '草拟中'), ('internal_review', '内部审查'), ('client_review', '客户审查'), ('revision', '修订中'), ('finalized', '已定稿')], default='drafting', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('product_category', models.CharField(blank=True, default='', max_length=100, verbose_name='产品类别')),
                ('test_methods', models.JSONField(blank=True, default=list, verbose_name='测试方法')),
                ('sample_size_estimate', models.IntegerField(blank=True, null=True, verbose_name='预估样本量')),
                ('estimated_duration_days', models.IntegerField(blank=True, null=True, verbose_name='预估周期(天)')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预估金额')),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.client', verbose_name='客户')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.opportunity', verbose_name='关联商机')),
                ('protocol', models.ForeignKey(blank=True, help_text='定稿后关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='protocol.protocol', verbose_name='关联协议')),
            ],
            options={
                'verbose_name': '方案',
                'db_table': 't_proposal',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='会议纪要内容')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='记录人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='proposal.meeting')),
            ],
            options={
                'db_table': 't_meeting_minute',
            },
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='描述')),
                ('assignee_id', models.IntegerField(blank=True, null=True, verbose_name='负责人ID')),
                ('assignee_name', models.CharField(blank=True, max_length=100, verbose_name='负责人')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('status', models.CharField(choices=[('pending', '待办'), ('in_progress', '进行中'), ('completed', '已完成'), ('overdue', '已逾期')], default='pending', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='proposal.meeting')),
            ],
            options={
                'db_table': 't_meeting_action_item',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_type', models.CharField(choices=[('email', '邮件'), ('phone', '电话'), ('meeting', '会议'), ('feishu_message', '飞书消息'), ('visit', '拜访'), ('file_transfer', '文件传递')], max_length=20, verbose_name='沟通类型')),
                ('subject', models.CharField(max_length=500, verbose_name='主题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('participants', models.JSONField(blank=True, default=list, verbose_name='参与人')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='crm.client', verbose_name='客户')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='crm.opportunity', verbose_name='商机')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='proposal.proposal', verbose_name='方案')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='protocol.protocol', verbose_name='协议')),
            ],
            options={
                'verbose_name': '沟通记录',
                'db_table': 't_communication_log',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='版本号')),
                ('change_summary', models.TextField(blank=True, default='', verbose_name='变更摘要')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('feishu_doc_token', models.CharField(blank=True, default='', max_length=200, verbose_name='飞书文档Token')),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='proposal.proposal', verbose_name='方案')),
            ],
            options={
                'verbose_name': '方案版本',
                'db_table': 't_proposal_version',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['proposal', 'create_time'], name='t_proposal__proposa_c4e29e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProposalChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('quotation', '报价单'), ('technical_plan', '技术方案'), ('regulatory_review', '法规审查'), ('ethics_pre_review', '伦理预审'), ('resource_plan', '资源计划'), ('schedule_confirmation', '排期确认')], max_length=50, verbose_name='检查项')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('completed_by_id', models.IntegerField(blank=True, null=True, verbose_name='完成人ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='proposal.proposal', verbose_name='方案')),
            ],
            options={
                'verbose_name': '方案准备清单',
                'db_table': 't_proposal_checklist',
                'ordering': ['create_time'],
                'indexes': [models.Index(fields=['proposal', 'item_name'], name='t_proposal__proposa_12771c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status'], name='t_proposal_status_8d3b98_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['client', 'status'], name='t_proposal_client__97dc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['client', 'occurred_at'], name='t_communica_client__e9ebc6_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['proposal', 'occurred_at'], name='t_communica_proposa_0e4eb7_idx'),
        ),
    ]
