# Generated by Django 4.2.27 on 2026-02-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='contact_id',
            field=models.IntegerField(blank=True, help_text='关联 t_client_contact.id，精确标记与哪位关键人沟通', null=True, verbose_name='关键联系人ID'),
        ),
    ]
