# Generated by Django 4.2.27 on 2026-02-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('instrument_type', models.CharField(help_text='如：血压计、体温计、实验室设备等', max_length=100, verbose_name='仪器类型')),
                ('interface_type', models.CharField(help_text='如：HL7、REST API、文件导入等', max_length=50, verbose_name='接口类型')),
                ('config', models.JSONField(help_text='连接参数、认证信息等', verbose_name='接口配置')),
                ('mapping', models.JSONField(blank=True, help_text='仪器数据到CRF字段的映射规则', null=True, verbose_name='数据映射')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '仪器接口',
                'db_table': 't_instrument_interface',
                'indexes': [models.Index(fields=['instrument_type', 'is_active'], name='t_instrumen_instrum_448319_idx')],
            },
        ),
        migrations.CreateModel(
            name='CRFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('schema', models.JSONField(help_text='JSON Schema格式的表单定义', verbose_name='表单结构')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': 'CRF模板',
                'db_table': 't_crf_template',
                'indexes': [models.Index(fields=['name', 'version'], name='t_crf_templ_name_53979f_idx'), models.Index(fields=['is_active'], name='t_crf_templ_is_acti_537e66_idx')],
            },
        ),
        migrations.CreateModel(
            name='CRFRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_id', models.IntegerField(db_index=True, help_text='关联工单', verbose_name='工单ID')),
                ('data', models.JSONField(help_text='根据模板schema填写的数据', verbose_name='表单数据')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('verified', '已核实'), ('queried', '已质疑'), ('locked', '已锁定')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('submitted_by', models.IntegerField(blank=True, null=True, verbose_name='提交人ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('verified_by', models.IntegerField(blank=True, null=True, verbose_name='核实人ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='核实时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='edc.crftemplate')),
            ],
            options={
                'verbose_name': 'CRF记录',
                'db_table': 't_crf_record',
                'indexes': [models.Index(fields=['template', 'status'], name='t_crf_recor_templat_0dee26_idx'), models.Index(fields=['work_order_id'], name='t_crf_recor_work_or_9c378d_idx'), models.Index(fields=['status', 'create_time'], name='t_crf_recor_status_4b7cc0_idx')],
            },
        ),
    ]
