# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0002_s1_6_validation_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名')),
                ('query_text', models.TextField(verbose_name='质疑内容')),
                ('status', models.CharField(choices=[('open', '已开放'), ('answered', '已回复'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('answer_text', models.TextField(blank=True, default='', verbose_name='回复内容')),
                ('answered_by_id', models.IntegerField(blank=True, null=True, verbose_name='回复人ID')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('closed_by_id', models.IntegerField(blank=True, null=True, verbose_name='关闭人ID')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('close_reason', models.TextField(blank=True, default='', verbose_name='关闭原因')),
                ('created_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据质疑',
                'db_table': 't_data_query',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SDVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名')),
                ('status', models.CharField(choices=[('pending', '待核查'), ('verified', '已核查'), ('discrepancy', '有差异')], default='pending', max_length=20, verbose_name='状态')),
                ('verified_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='核查人ID')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='核查时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='核查备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SDV记录',
                'db_table': 't_sdv_record',
                'ordering': ['-create_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='crfvalidationresult',
            new_name='t_crf_valid_record__e4e470_idx',
            old_name='edc_vr_result_idx',
        ),
        migrations.RenameIndex(
            model_name='crfvalidationrule',
            new_name='t_crf_valid_templat_8a652c_idx',
            old_name='edc_vr_tpl_field_idx',
        ),
        migrations.RenameIndex(
            model_name='crfvalidationrule',
            new_name='t_crf_valid_rule_ty_4a23e7_idx',
            old_name='edc_vr_type_idx',
        ),
        migrations.AlterField(
            model_name='crfvalidationrule',
            name='rule_config',
            field=models.JSONField(default=dict, help_text='如 {"min": 0, "max": 200} 或 {"pattern": "^[A-Z]{2}\\d+$"}', verbose_name='规则配置'),
        ),
        migrations.AddField(
            model_name='sdvrecord',
            name='crf_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdv_records', to='edc.crfrecord', verbose_name='CRF记录'),
        ),
        migrations.AddField(
            model_name='dataquery',
            name='crf_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_queries', to='edc.crfrecord', verbose_name='CRF记录'),
        ),
        migrations.AddIndex(
            model_name='sdvrecord',
            index=models.Index(fields=['crf_record', 'field_name'], name='t_sdv_recor_crf_rec_3587a4_idx'),
        ),
        migrations.AddIndex(
            model_name='sdvrecord',
            index=models.Index(fields=['status'], name='t_sdv_recor_status_9cb211_idx'),
        ),
        migrations.AddIndex(
            model_name='dataquery',
            index=models.Index(fields=['crf_record', 'status'], name='t_data_quer_crf_rec_f9be4a_idx'),
        ),
        migrations.AddIndex(
            model_name='dataquery',
            index=models.Index(fields=['status'], name='t_data_quer_status_4d8ec4_idx'),
        ),
    ]
