# Generated by Django 4.2.27 on 2026-02-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc', '0003_dataquery_sdvrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crfrecord',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('verified', '已核实'), ('queried', '已质疑'), ('sdv_completed', 'SDV已完成'), ('locked', '已锁定')], db_index=True, default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
