# Generated by Django 4.2.27 on 2026-03-04 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0015_evaluator_compliance_f1_f2_f3'),
        ('edc', '0004_alter_crfrecord_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crfrecord',
            name='t_crf_recor_work_or_9c378d_idx',
        ),
        migrations.RemoveField(
            model_name='crfrecord',
            name='work_order_id',
        ),
        migrations.AddField(
            model_name='crfrecord',
            name='data_source',
            field=models.CharField(blank=True, default='manual_entry', help_text='manual_entry: 手工录入 / instrument_auto: 仪器自动映射 / instrument_import: 仪器文件导入', max_length=30, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='crfrecord',
            name='source_detection_id',
            field=models.IntegerField(blank=True, help_text='关联的 InstrumentDetection.id（数据来源为仪器时）', null=True, verbose_name='来源检测记录ID'),
        ),
        migrations.AddField(
            model_name='crfrecord',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crf_records', to='workorder.workorder', verbose_name='关联工单'),
        ),
        migrations.AddIndex(
            model_name='crfrecord',
            index=models.Index(fields=['work_order'], name='t_crf_recor_work_or_9c378d_idx'),
        ),
    ]
