# Generated by Django 4.2.27 on 2026-02-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(db_index=True, verbose_name='账号ID')),
                ('account_name', models.CharField(max_length=100, verbose_name='账号名称')),
                ('account_type', models.CharField(blank=True, default='', max_length=20, verbose_name='账号类型')),
                ('resource_type', models.CharField(db_index=True, help_text='如：protocol, icf, crf_record等', max_length=50, verbose_name='资源类型')),
                ('resource_id', models.CharField(db_index=True, max_length=100, verbose_name='资源ID')),
                ('resource_name', models.CharField(blank=True, default='', max_length=200, verbose_name='资源名称')),
                ('signature_data', models.JSONField(help_text='签名图像、证书、哈希值等', verbose_name='签名数据')),
                ('reason', models.CharField(blank=True, default='', help_text='如：同意、批准、确认等', max_length=500, verbose_name='签名原因')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('signed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='签名时间')),
            ],
            options={
                'verbose_name': '电子签名',
                'db_table': 't_electronic_signature',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['account_id', 'signed_at'], name='t_electroni_account_a58e12_idx'), models.Index(fields=['resource_type', 'resource_id'], name='t_electroni_resourc_8d4f7a_idx'), models.Index(fields=['signed_at'], name='t_electroni_signed__899de6_idx')],
            },
        ),
    ]
