# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='文档编号')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('in_review', '审核中'), ('approved', '已批准'), ('published', '已发布'), ('obsolete', '已作废'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('content', models.TextField(blank=True, default='', verbose_name='文档内容')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('feishu_doc_token', models.CharField(blank=True, default='', help_text='飞书云文档 token，发布时创建', max_length=200, verbose_name='飞书文档token')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('created_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '文档',
                'db_table': 't_document',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_by_id', models.IntegerField(blank=True, null=True, verbose_name='发布人ID')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('publish_notes', models.TextField(blank=True, default='', verbose_name='发布说明')),
                ('training_required', models.BooleanField(default=False, verbose_name='需要培训')),
                ('training_deadline', models.DateField(blank=True, null=True, verbose_name='培训截止日期')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishes', to='document.document', verbose_name='文档')),
            ],
            options={
                'verbose_name': '文档发布',
                'db_table': 't_document_publish',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='分类编码')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='document.documentcategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '文档分类',
                'db_table': 't_document_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document.documentcategory', verbose_name='文档分类'),
        ),
        migrations.CreateModel(
            name='DocumentTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='Account ID', verbose_name='培训人员ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('completed', '已完成'), ('overdue', '已逾期')], default='pending', max_length=20, verbose_name='状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='document.documentpublish', verbose_name='发布记录')),
            ],
            options={
                'verbose_name': '文档培训',
                'db_table': 't_document_training',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['publish', 'user_id', 'status'], name='t_document__publish_e50bda_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_by_id', models.IntegerField(blank=True, null=True, verbose_name='提交人ID')),
                ('reviewed_by_id', models.IntegerField(blank=True, null=True, verbose_name='审核人ID')),
                ('review_comments', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='document.document', verbose_name='文档')),
            ],
            options={
                'verbose_name': '文档审核',
                'db_table': 't_document_review',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['document', 'status'], name='t_document__documen_db2921_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'status'], name='t_document_categor_6752e8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='t_document_status_bb205c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_no'], name='t_document_documen_992208_idx'),
        ),
    ]
