# Generated by Django 4.2.27 on 2026-02-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='如 2025-H2', max_length=20, verbose_name='评估期')),
                ('scores', models.JSONField(default=dict, help_text='{"维度名": 分数}', verbose_name='各维度分数')),
                ('overall', models.CharField(blank=True, default='', max_length=20, verbose_name='综合评价')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '评估中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('assessor', models.CharField(max_length=100, verbose_name='评估人')),
                ('assessor_id', models.IntegerField(blank=True, null=True, verbose_name='评估人ID')),
                ('comments', models.TextField(blank=True, default='', verbose_name='评估意见')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '能力评估',
                'db_table': 't_assessment',
                'ordering': ['-period', 'staff__name'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon', models.CharField(blank=True, default='', max_length=20, verbose_name='图标')),
                ('levels', models.JSONField(default=list, help_text='JSON 数组，按等级排列', verbose_name='等级描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '胜任力模型',
                'db_table': 't_competency_model',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(max_length=200, verbose_name='岗位')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('gcp_cert', models.CharField(blank=True, default='', max_length=100, verbose_name='GCP证书号')),
                ('gcp_expiry', models.DateField(blank=True, null=True, verbose_name='GCP到期日')),
                ('gcp_status', models.CharField(choices=[('valid', '有效'), ('expiring', '即将过期'), ('expired', '已过期'), ('none', '无证书')], default='none', max_length=20, verbose_name='GCP状态')),
                ('other_certs', models.TextField(blank=True, default='', verbose_name='其他资质')),
                ('training_status', models.CharField(blank=True, default='未开始', max_length=20, verbose_name='培训状态')),
                ('account_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='关联账户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '人员资质',
                'db_table': 't_staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300, verbose_name='课程名称')),
                ('category', models.CharField(max_length=50, verbose_name='类别')),
                ('trainer', models.CharField(max_length=100, verbose_name='讲师')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('hours', models.IntegerField(verbose_name='学时')),
                ('status', models.CharField(choices=[('scheduled', '已排期'), ('in_progress', '进行中'), ('completed', '已完成'), ('overdue', '已逾期')], default='scheduled', max_length=20, verbose_name='状态')),
                ('score', models.CharField(blank=True, default='', max_length=20, verbose_name='考核分')),
                ('feishu_calendar_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书日历ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='hr.staff', verbose_name='学员')),
            ],
            options={
                'verbose_name': '培训记录',
                'db_table': 't_training',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['gcp_status'], name='t_staff_gcp_sta_d10f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department'], name='t_staff_departm_00b44c_idx'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='hr.staff', verbose_name='被评估人'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['status'], name='t_training_status_f93676_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['trainee', 'status'], name='t_training_trainee_54a96d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['staff', 'period'], name='t_assessmen_staff_i_e114f8_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status'], name='t_assessmen_status_ab6492_idx'),
        ),
    ]
