# Generated by Django 4.2.27 on 2026-02-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='staff',
            name='feishu_open_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, unique=True, verbose_name='飞书Open ID'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='手机号'),
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.IntegerField(db_index=True, help_text='关联 Protocol.id', verbose_name='协议ID')),
                ('role', models.CharField(help_text='如 PM/CRA/CRC/DM/MW/QC', max_length=50, verbose_name='项目角色')),
                ('workload_percentage', models.IntegerField(default=100, help_text='0-100, 此项目占该员工总工作量百分比', verbose_name='工作量占比(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='hr.staff', verbose_name='员工')),
            ],
            options={
                'verbose_name': '项目人员分配',
                'db_table': 't_project_assignment',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['protocol_id', 'staff'], name='t_project_a_protoco_7a030e_idx'), models.Index(fields=['staff', 'is_active'], name='t_project_a_staff_i_ce8596_idx')],
                'unique_together': {('protocol_id', 'staff', 'role')},
            },
        ),
    ]
