# Generated by Django 4.2.27 on 2026-03-05 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_staff_account_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='版本号')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('group_config', models.JSONField(blank=True, default=dict, help_text='{"C01": {"label": "心电组", "pool_ratio": 0.3}, ...}', verbose_name='组别配置')),
                ('weight_config', models.JSONField(blank=True, default=dict, help_text='{"workorder": 0.4, "quality": 0.2, "amount": 0.3, "timeliness": 0.1}', verbose_name='维度权重')),
                ('threshold_config', models.JSONField(blank=True, default=dict, help_text='{"S": 90, "A": 75, "B": 60, "C": 0}', verbose_name='等级阈值')),
                ('cap_floor_config', models.JSONField(blank=True, default=dict, help_text='{"cap_multiplier": 2.0, "floor_multiplier": 0.5}', verbose_name='封顶保底')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('draft', '草稿')], default='draft', max_length=20, verbose_name='状态')),
                ('approved_by', models.CharField(blank=True, default='', max_length=100, verbose_name='审批人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '绩效规则',
                'db_table': 't_hr_performance_rule',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7, verbose_name='结算月份')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='标题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewing', '审核中'), ('approved', '已批准'), ('released', '已发放'), ('archived', '已归档'), ('reopened', '已重开')], default='draft', max_length=20, verbose_name='状态')),
                ('total_pool', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='奖金池总额')),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已分配总额')),
                ('data_completeness', models.DecimalField(decimal_places=2, default=0, help_text='0-100，缺数据时低于 100 但不阻断', max_digits=5, verbose_name='数据完整度')),
                ('source_snapshot_ids', models.JSONField(blank=True, default=list, verbose_name='关联贡献快照')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='创建人')),
                ('submitted_by', models.CharField(blank=True, default='', max_length=100, verbose_name='提交人')),
                ('approved_by', models.CharField(blank=True, default='', max_length=100, verbose_name='审批人')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='hr.performancerule', verbose_name='关联规则')),
            ],
            options={
                'verbose_name': '绩效结算单',
                'db_table': 't_hr_performance_settlement',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='SettlementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='新状态')),
                ('operator', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='变更明细')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hr.performancesettlement', verbose_name='结算单')),
            ],
            options={
                'verbose_name': '结算审计日志',
                'db_table': 't_hr_settlement_audit_log',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ContributionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7, verbose_name='统计月份')),
                ('source_workstation', models.CharField(default='manual', max_length=50, verbose_name='来源工作台')),
                ('staff_name', models.CharField(blank=True, default='', max_length=100, verbose_name='姓名（冗余）')),
                ('project_code', models.CharField(blank=True, default='', max_length=100, verbose_name='项目编号')),
                ('group_name', models.CharField(blank=True, default='', max_length=50, verbose_name='组别')),
                ('role_in_project', models.CharField(blank=True, default='', max_length=50, verbose_name='项目角色')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='{"workorder_count": 12, "on_time_rate": 0.95, ...}', verbose_name='指标数据')),
                ('amount_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='金额贡献')),
                ('data_confidence', models.DecimalField(decimal_places=2, default=1.0, help_text='0.00-1.00，手工录入=0.50，Excel=0.70，自动采集=1.00', max_digits=3, verbose_name='数据置信度')),
                ('import_source', models.CharField(blank=True, default='manual', help_text='auto/manual/excel', max_length=50, verbose_name='导入来源')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_snapshots', to='hr.staff', verbose_name='员工')),
            ],
            options={
                'verbose_name': '贡献快照',
                'db_table': 't_hr_contribution_snapshot',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=50, verbose_name='组别')),
                ('role_label', models.CharField(blank=True, default='', max_length=50, verbose_name='角色标签')),
                ('contribution_data', models.JSONField(blank=True, default=dict, verbose_name='贡献原始数据')),
                ('base_score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='基础分')),
                ('quality_adjust', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='质量校正')),
                ('manual_adjust', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='人工调整')),
                ('manual_adjust_reason', models.TextField(blank=True, default='', verbose_name='调整说明')),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='最终分')),
                ('suggested_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='建议奖金')),
                ('final_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='确认奖金')),
                ('grade', models.CharField(blank=True, default='', max_length=10, verbose_name='等级')),
                ('lock_status', models.CharField(choices=[('unlocked', '未锁定'), ('locked', '已锁定')], default='unlocked', max_length=20, verbose_name='锁定状态')),
                ('evidence_refs', models.JSONField(blank=True, default=list, verbose_name='证据引用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.performancesettlement', verbose_name='结算单')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_lines', to='hr.staff', verbose_name='员工')),
            ],
            options={
                'verbose_name': '结算明细',
                'db_table': 't_hr_settlement_line',
                'ordering': ['group_name', '-final_score'],
                'indexes': [models.Index(fields=['settlement', 'staff'], name='t_hr_settle_settlem_62acc0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='settlementline',
            constraint=models.UniqueConstraint(fields=('settlement', 'staff'), name='uq_line_settlement_staff'),
        ),
        migrations.AddConstraint(
            model_name='performancesettlement',
            constraint=models.UniqueConstraint(fields=('period', 'rule'), name='uq_settlement_period_rule'),
        ),
        migrations.AddIndex(
            model_name='contributionsnapshot',
            index=models.Index(fields=['period', 'source_workstation'], name='t_hr_contri_period_96b719_idx'),
        ),
        migrations.AddIndex(
            model_name='contributionsnapshot',
            index=models.Index(fields=['staff', 'period'], name='t_hr_contri_staff_i_201c8e_idx'),
        ),
    ]
