# Generated by Django 4.2.29 on 2026-03-12 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(max_length=32, verbose_name='范围类型')),
                ('scope_id', models.CharField(max_length=64, verbose_name='范围ID')),
                ('period_type', models.CharField(max_length=16, verbose_name='周期类型')),
                ('period_key', models.CharField(db_index=True, max_length=32, verbose_name='周期键')),
                ('metrics_json', models.JSONField(default=dict, verbose_name='指标JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '周报指标快照',
                'db_table': 't_weekly_report_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ReportReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('week_key', models.CharField(db_index=True, max_length=32, verbose_name='周键')),
                ('remind_type', models.CharField(max_length=32, verbose_name='催办类型')),
                ('sent_at', models.DateTimeField(verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '周报催办',
                'db_table': 't_weekly_report_reminder',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('report_year', models.IntegerField(db_index=True, verbose_name='年份')),
                ('report_week', models.IntegerField(db_index=True, verbose_name='周')),
                ('period_start', models.DateField(verbose_name='周期开始')),
                ('period_end', models.DateField(verbose_name='周期结束')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交')], max_length=32, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '周报',
                'db_table': 't_weekly_report',
                'unique_together': {('user_id', 'report_year', 'report_week')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('owner_id', models.IntegerField(db_index=True, verbose_name='负责人ID')),
                ('created_by', models.IntegerField(db_index=True, verbose_name='创建人ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(default='active', max_length=32, verbose_name='状态')),
                ('risk_level', models.CharField(choices=[('green', '低'), ('yellow', '中'), ('red', '高')], default='green', max_length=16, verbose_name='风险等级')),
            ],
            options={
                'verbose_name': '周报项目',
                'db_table': 't_weekly_report_project',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_id', models.IntegerField(db_index=True, verbose_name='负责人ID')),
                ('title', models.CharField(max_length=512, verbose_name='标题')),
                ('status', models.CharField(choices=[('todo', '未开始'), ('doing', '进行中'), ('blocked', '阻塞'), ('done', '已完成')], default='todo', max_length=32, verbose_name='状态')),
                ('priority', models.IntegerField(default=3, verbose_name='优先级')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('plan_hours', models.FloatField(default=0, verbose_name='计划工时')),
                ('actual_hours', models.FloatField(default=0, verbose_name='实际工时')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('blocked_reason', models.TextField(blank=True, null=True, verbose_name='阻塞原因')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='weekly_report.weeklyreportproject')),
            ],
            options={
                'verbose_name': '周报任务',
                'db_table': 't_weekly_report_task',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockers', models.TextField(default='', verbose_name='阻塞')),
                ('support_needed', models.TextField(default='', verbose_name='需要支持')),
                ('next_week_focus', models.TextField(default='', verbose_name='下周聚焦')),
                ('ops_work', models.TextField(default='', verbose_name='运维工作')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='weekly_report.weeklyreport')),
            ],
            options={
                'verbose_name': '周报备注',
                'db_table': 't_weekly_report_notes',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='weekly_report.weeklyreportproject')),
            ],
            options={
                'verbose_name': '周报项目成员',
                'db_table': 't_weekly_report_project_member',
                'unique_together': {('project', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(db_index=True, verbose_name='任务ID')),
                ('this_week_delta', models.TextField(default='', verbose_name='本周进展说明')),
                ('progress_before', models.IntegerField(default=0, verbose_name='进度-前')),
                ('progress_after', models.IntegerField(default=0, verbose_name='进度-后')),
                ('actual_hours', models.FloatField(default=0, verbose_name='实际工时')),
                ('is_delayed', models.BooleanField(default=False, verbose_name='是否延期')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weekly_report.weeklyreport')),
            ],
            options={
                'verbose_name': '周报条目',
                'db_table': 't_weekly_report_item',
                'unique_together': {('report', 'task_id')},
            },
        ),
    ]
