# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weekly_report", "0001_initial_weekly_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyreport",
            name="submitted_content",
            field=models.TextField(blank=True, default="", verbose_name="提交时的周报正文（预览框编辑后内容）"),
        ),
    ]
