# Generated by Django 4.2.27 on 2026-03-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_report', '0006_grant_liyue_leader_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreportleader',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weeklyreportnotes',
            name='next_week_plan',
            field=models.TextField(default='', verbose_name='下周计划'),
        ),
        migrations.AlterField(
            model_name='weeklyreporttask',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='优先级'),
        ),
    ]
