# Generated by Django 4.2.27 on 2026-02-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='SOP编号')),
                ('title', models.CharField(max_length=300, verbose_name='文件名称')),
                ('version', models.CharField(max_length=20, verbose_name='版本')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('status', models.CharField(choices=[('effective', '生效中'), ('draft', '草稿'), ('under_review', '审核中'), ('retired', '已废止')], default='draft', max_length=20, verbose_name='状态')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('next_review', models.DateField(blank=True, null=True, verbose_name='下次审查日期')),
                ('owner', models.CharField(max_length=100, verbose_name='归口部门')),
                ('feishu_doc_url', models.URLField(blank=True, default='', verbose_name='飞书文档链接')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': 'SOP',
                'db_table': 't_sop',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['status'], name='t_sop_status_ea64d8_idx'), models.Index(fields=['category'], name='t_sop_categor_351419_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='偏差编号')),
                ('title', models.CharField(max_length=500, verbose_name='偏差描述')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('major', '重大'), ('minor', '轻微')], max_length=20, verbose_name='严重度')),
                ('status', models.CharField(choices=[('open', '待处理'), ('investigating', '调查中'), ('resolved', '已纠正'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('reporter', models.CharField(max_length=100, verbose_name='报告人')),
                ('reporter_id', models.IntegerField(blank=True, null=True, verbose_name='报告人ID')),
                ('reported_at', models.DateField(verbose_name='报告日期')),
                ('project', models.CharField(max_length=100, verbose_name='项目')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='项目ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='详细描述')),
                ('root_cause', models.TextField(blank=True, default='', verbose_name='根因分析')),
                ('resolution', models.TextField(blank=True, default='', verbose_name='处理措施')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='关闭日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '偏差',
                'db_table': 't_deviation',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='t_deviation_status_ae419d_idx'), models.Index(fields=['project', 'status'], name='t_deviation_project_d1bc0c_idx'), models.Index(fields=['reported_at'], name='t_deviation_reporte_7b418d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='CAPA编号')),
                ('type', models.CharField(choices=[('corrective', '纠正'), ('preventive', '预防')], max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=500, verbose_name='措施描述')),
                ('responsible', models.CharField(max_length=100, verbose_name='责任人')),
                ('responsible_id', models.IntegerField(blank=True, null=True, verbose_name='责任人ID')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('in_progress', '执行中'), ('verification', '验证中'), ('closed', '已关闭'), ('overdue', '已超期')], default='planned', max_length=20, verbose_name='状态')),
                ('effectiveness', models.CharField(blank=True, default='待验证', max_length=20, verbose_name='有效性')),
                ('action_detail', models.TextField(blank=True, default='', verbose_name='措施详情')),
                ('verification_note', models.TextField(blank=True, default='', verbose_name='验证记录')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='quality.deviation', verbose_name='关联偏差')),
            ],
            options={
                'verbose_name': 'CAPA',
                'db_table': 't_capa',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='t_capa_status_50f026_idx'), models.Index(fields=['deviation', 'status'], name='t_capa_deviati_935799_idx')],
            },
        ),
    ]
