# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_add_sop_created_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviation',
            name='status',
            field=models.CharField(choices=[('identified', '已识别'), ('reported', '已报告'), ('investigating', '调查中'), ('capa_pending', 'CAPA待建'), ('capa_executing', 'CAPA执行中'), ('capa_complete', 'CAPA已完成'), ('closed', '已关闭')], default='identified', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='CAPAActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1, verbose_name='序号')),
                ('title', models.CharField(max_length=500, verbose_name='行动项描述')),
                ('responsible_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='责任人ID')),
                ('responsible_name', models.CharField(blank=True, default='', max_length=100, verbose_name='责任人')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '执行中'), ('completed', '已完成'), ('overdue', '已超期')], default='pending', max_length=20, verbose_name='状态')),
                ('completion_note', models.TextField(blank=True, default='', verbose_name='完成说明')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='quality.capa', verbose_name='关联CAPA')),
            ],
            options={
                'verbose_name': 'CAPA行动项',
                'db_table': 't_capa_action_item',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['capa', 'status'], name='t_capa_acti_capa_id_dad9bd_idx')],
            },
        ),
    ]
