# Generated by Django 4.2.27 on 2026-02-19 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_alter_deviation_status_capaactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='change_request_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联变更ID'),
        ),
        migrations.AddField(
            model_name='sop',
            name='previous_version_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='上一版本ID'),
        ),
        migrations.AddField(
            model_name='sop',
            name='review_history',
            field=models.JSONField(blank=True, default=list, verbose_name='审查记录'),
        ),
        migrations.CreateModel(
            name='SOPTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_id', models.IntegerField(verbose_name='培训人员ID')),
                ('trainee_name', models.CharField(max_length=100, verbose_name='培训人员')),
                ('status', models.CharField(choices=[('pending', '待培训'), ('completed', '已完成'), ('overdue', '已超期')], default='pending', max_length=20, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='培训截止日')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='quality.sop')),
            ],
            options={
                'verbose_name': 'SOP培训记录',
                'db_table': 't_sop_training',
                'unique_together': {('sop', 'trainee_id')},
            },
        ),
    ]
