# Generated by Django 4.2.27 on 2026-02-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_qp2_3_sop_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='审计编号')),
                ('title', models.CharField(max_length=200, verbose_name='审计标题')),
                ('audit_type', models.CharField(max_length=50, verbose_name='审计类型')),
                ('scope', models.TextField(blank=True, default='', verbose_name='审计范围')),
                ('auditor', models.CharField(max_length=100, verbose_name='审计员')),
                ('auditor_org', models.CharField(blank=True, default='', max_length=200, verbose_name='审计机构')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('closed', '已关闭')], default='planned', max_length=20, verbose_name='状态')),
                ('summary', models.TextField(blank=True, default='', verbose_name='审计总结')),
                ('checklist', models.JSONField(blank=True, default=list, verbose_name='检查清单')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审计记录',
                'db_table': 't_audit',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='变更编号')),
                ('title', models.CharField(max_length=200, verbose_name='变更标题')),
                ('change_type', models.CharField(max_length=50, verbose_name='变更类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='变更描述')),
                ('impact_assessment', models.TextField(blank=True, default='', verbose_name='影响评估')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='风险等级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已驳回'), ('implementing', '实施中'), ('verified', '已验证'), ('closed', '已关闭')], default='draft', max_length=20, verbose_name='状态')),
                ('applicant', models.CharField(blank=True, default='', max_length=100, verbose_name='申请人')),
                ('applicant_id', models.IntegerField(blank=True, null=True, verbose_name='申请人ID')),
                ('reviewer', models.CharField(blank=True, default='', max_length=100, verbose_name='审批人')),
                ('reviewer_id', models.IntegerField(blank=True, null=True, verbose_name='审批人ID')),
                ('implementation_plan', models.TextField(blank=True, default='', verbose_name='实施方案')),
                ('verification_note', models.TextField(blank=True, default='', verbose_name='验证说明')),
                ('feishu_approval_instance_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书审批实例ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '变更请求',
                'db_table': 't_change_request',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='deviation',
            name='source',
            field=models.CharField(blank=True, default='self_report', max_length=50, verbose_name='偏差来源'),
        ),
        migrations.AddField(
            model_name='deviation',
            name='source_record_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='来源记录ID'),
        ),
        migrations.AddField(
            model_name='deviation',
            name='source_workstation',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='来源工作台'),
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1, verbose_name='序号')),
                ('title', models.CharField(max_length=200, verbose_name='发现项标题')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('major', '重大'), ('minor', '轻微'), ('observation', '观察项')], max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('open', '待整改'), ('in_progress', '整改中'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('clause', models.CharField(blank=True, default='', max_length=100, verbose_name='条款')),
                ('corrective_requirement', models.TextField(blank=True, default='', verbose_name='整改要求')),
                ('corrective_deadline', models.DateField(blank=True, null=True, verbose_name='整改截止日')),
                ('deviation_id', models.IntegerField(blank=True, null=True, verbose_name='关联偏差ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='quality.audit')),
            ],
            options={
                'verbose_name': '审计发现项',
                'db_table': 't_audit_finding',
                'ordering': ['sequence'],
            },
        ),
    ]
