# Generated by Django 4.2.27 on 2026-03-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_audit_changerequest_deviation_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='审计编号')),
                ('title', models.CharField(max_length=200, verbose_name='审计名称')),
                ('audit_type', models.CharField(choices=[('internal', '内部审计'), ('external', '外部审计'), ('client', '客户审计'), ('inspection', '飞行检查')], max_length=20, verbose_name='审计类型')),
                ('scope', models.TextField(blank=True, default='', verbose_name='审计范围')),
                ('auditor', models.CharField(max_length=100, verbose_name='审计员')),
                ('auditor_org', models.CharField(blank=True, default='', max_length=200, verbose_name='审计机构')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('in_progress', '执行中'), ('completed', '已完成'), ('closed', '已关闭')], default='planned', max_length=20, verbose_name='状态')),
                ('checklist', models.JSONField(blank=True, default=list, verbose_name='检查表')),
                ('summary', models.TextField(blank=True, default='', verbose_name='审计总结')),
                ('feishu_calendar_event_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书日历事件ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '质量审计',
                'db_table': 't_quality_audit',
                'ordering': ['-planned_date'],
            },
        ),
    ]
