# Generated by Django 4.2.29 on 2026-03-27 03:58

from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion


def _parse_date_str(s):
    if not s or not isinstance(s, str):
        return None
    s = s.strip()[:10]
    if len(s) < 10:
        return None
    try:
        return datetime.strptime(s, '%Y-%m-%d').date()
    except ValueError:
        return None


def backfill_protocol_supervision(apps, schema_editor):
    Protocol = apps.get_model('protocol', 'Protocol')
    PPS = apps.get_model('quality', 'ProtocolProjectSupervision')
    for p in Protocol.objects.filter(is_deleted=False):
        if PPS.objects.filter(protocol_id=p.id).exists():
            continue
        pd = p.parsed_data if isinstance(p.parsed_data, dict) else {}
        start = None
        end = None
        for key in ('execution_start', 'study_start', 'trial_start', 'screening_start', 'first_visit_date'):
            start = _parse_date_str(pd.get(key))
            if start:
                break
        if start is None and isinstance(pd.get('visits'), list) and len(pd['visits']) > 0:
            v0 = pd['visits'][0]
            if isinstance(v0, dict):
                start = _parse_date_str(v0.get('date') or v0.get('window_start') or v0.get('planned_date'))
        if start is None and p.create_time:
            start = p.create_time.date()
        for key in ('execution_end', 'study_end', 'trial_end', 'last_visit_date'):
            end = _parse_date_str(pd.get(key))
            if end:
                break
        if end is None and isinstance(pd.get('visits'), list) and len(pd['visits']) > 1:
            v_last = pd['visits'][-1]
            if isinstance(v_last, dict):
                end = _parse_date_str(v_last.get('date') or v_last.get('window_end') or v_last.get('planned_date'))
        PPS.objects.create(protocol_id=p.id, execution_start_date=start, execution_end_date=end)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0021_alter_consent_config_account_help_text_qa'),
        ('quality', '0007_qualityaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolProjectSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_start_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='执行周期开始')),
                ('execution_end_date', models.DateField(blank=True, null=True, verbose_name='执行周期结束')),
                ('plan_content', models.TextField(blank=True, default='', verbose_name='监察计划（监察内容）')),
                ('plan_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='监察计划提交时间')),
                ('actual_content', models.TextField(blank=True, default='', verbose_name='实际监察内容')),
                ('actual_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='实际监察提交时间')),
                ('updated_by_id', models.IntegerField(blank=True, null=True, verbose_name='最后更新人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('protocol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_supervision', to='protocol.protocol', verbose_name='协议')),
            ],
            options={
                'verbose_name': '协议项目监察',
                'db_table': 't_quality_protocol_supervision',
                'indexes': [models.Index(fields=['execution_start_date'], name='t_quality_p_executi_3b2011_idx'), models.Index(fields=['plan_submitted_at'], name='t_quality_p_plan_su_a66576_idx'), models.Index(fields=['actual_submitted_at'], name='t_quality_p_actual__daa002_idx')],
            },
        ),
        migrations.RunPython(backfill_protocol_supervision, noop_reverse),
    ]
