# Generated by Django 4.2.27 on 2026-03-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_data_quality_engine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataQualityAlert',
        ),
        migrations.DeleteModel(
            name='DataQualityRule',
        ),
    ]
