# Generated by Django 4.2.29 on 2026-03-27 12:37

from django.db import migrations, models
import django.db.models.deletion


def backfill_registry(apps, schema_editor):
    Protocol = apps.get_model('protocol', 'Protocol')
    QualityProjectRegistry = apps.get_model('quality', 'QualityProjectRegistry')
    for p in Protocol.objects.filter(is_deleted=False).iterator():
        pd = p.parsed_data or {}
        if isinstance(pd, dict) and pd.get('quality_origin') == 'manual_test':
            src = 'quality_manual'
        else:
            src = 'weizhou'
        QualityProjectRegistry.objects.get_or_create(protocol_id=p.id, defaults={'source': src})


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0021_alter_consent_config_account_help_text_qa'),
        ('quality', '0008_protocol_project_supervision'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityProjectRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('weizhou', '维周执行台'), ('quality_manual', '质量台本地测试')], db_index=True, default='weizhou', max_length=32, verbose_name='来源')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('protocol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_project_registry', to='protocol.protocol', verbose_name='协议')),
            ],
            options={
                'verbose_name': '质量台项目来源登记',
                'db_table': 't_quality_project_registry',
            },
        ),
        migrations.RunPython(backfill_registry, migrations.RunPython.noop),
    ]
