# Generated by Django 4.2.29 on 2026-03-28 06:58

import apps.quality.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_quality_project_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolprojectsupervision',
            name='plan_entries',
            field=models.JSONField(blank=True, default=apps.quality.models._empty_plan_entries, help_text='JSON 数组：访视阶段、计划监察日期、监察内容、监察人', verbose_name='监察计划条目'),
        ),
    ]
