# Generated by Django 4.2.29 on 2026-03-28 07:19

import apps.quality.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_protocol_supervision_plan_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolprojectsupervision',
            name='actual_entries',
            field=models.JSONField(blank=True, default=apps.quality.models._empty_plan_entries, help_text='JSON 数组：访视阶段、监察时间、监察内容、结论（entry_id 锁定已提交行）', verbose_name='监察记录条目'),
        ),
    ]
