# Generated by Django 4.2.27 on 2026-02-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('review', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('assigned_to', models.IntegerField(blank=True, db_index=True, help_text='Account ID', null=True, verbose_name='分配给')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='subject.enrollment')),
                ('visit_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='visit.visitnode')),
            ],
            options={
                'verbose_name': '工单',
                'db_table': 't_work_order',
                'indexes': [models.Index(fields=['enrollment', 'status'], name='t_work_orde_enrollm_5c9278_idx'), models.Index(fields=['visit_node', 'status'], name='t_work_orde_visit_n_ef4d43_idx'), models.Index(fields=['assigned_to', 'status'], name='t_work_orde_assigne_5def34_idx'), models.Index(fields=['status', 'due_date'], name='t_work_orde_status_eb0c02_idx'), models.Index(fields=['create_time'], name='t_work_orde_create__e2ec73_idx')],
            },
        ),
    ]
