# Generated by Django 4.2.27 on 2026-02-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='feishu_approval_instance_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='飞书审批实例ID'),
        ),
    ]
