# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0005_s1_5_workorder_enhance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderQualityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeness', models.FloatField(default=0.0, help_text='0.0~1.0', verbose_name='数据完整度')),
                ('has_anomaly', models.BooleanField(default=False, verbose_name='存在异常')),
                ('result', models.CharField(help_text='auto_pass/auto_reject/manual_review', max_length=20, verbose_name='审计结果')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='审计详情')),
                ('reviewer_id', models.IntegerField(blank=True, null=True, verbose_name='人工审核人ID')),
                ('reviewer_comment', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工单质量审计',
                'db_table': 't_work_order_quality_audit',
                'ordering': ['-create_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='workorderassignment',
            new_name='t_work_orde_work_or_b7ddb4_idx',
            old_name='woa_wo_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderassignment',
            new_name='t_work_orde_assigne_29bce5_idx',
            old_name='woa_user_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderresource',
            new_name='t_work_orde_work_or_d1e549_idx',
            old_name='wor_wo_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderresource',
            new_name='t_work_orde_resourc_5bd688_idx',
            old_name='wor_cat_idx',
        ),
        migrations.AddField(
            model_name='workorderqualityaudit',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_audits', to='workorder.workorder', verbose_name='工单'),
        ),
        migrations.AddIndex(
            model_name='workorderqualityaudit',
            index=models.Index(fields=['work_order'], name='t_work_orde_work_or_8d636c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderqualityaudit',
            index=models.Index(fields=['result'], name='t_work_orde_result_0abe8e_idx'),
        ),
    ]
