# Generated by Django 4.2.27 on 2026-02-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_workorderqualityaudit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('assigned', '已分配'), ('in_progress', '进行中'), ('completed', '已完成'), ('review', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
