# Generated by Django 4.2.27 on 2026-02-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0007_alter_workorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, verbose_name='序号')),
                ('item_text', models.CharField(max_length=500, verbose_name='检查项内容')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='是否必须')),
                ('is_checked', models.BooleanField(default=False, verbose_name='已勾选')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='勾选时间')),
                ('checked_by', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='勾选人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='workorder.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单检查清单',
                'db_table': 't_work_order_checklist',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['work_order'], name='t_work_orde_work_or_9469e9_idx')],
            },
        ),
    ]
