# Generated by Django 4.2.27 on 2026-02-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0006_p2_recruitment_tables'),
        ('workorder', '0009_workordersuspension_workorderprogresstracker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(help_text='workorder_overdue/workload_imbalance/equipment_calibration/subject_no_show', max_length=50, verbose_name='告警类型')),
                ('threshold', models.FloatField(default=0, verbose_name='阈值')),
                ('level', models.CharField(default='warning', help_text='info/warning/critical', max_length=20, verbose_name='级别')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警配置',
                'db_table': 't_alert_config',
                'ordering': ['alert_type'],
            },
        ),
        migrations.CreateModel(
            name='AutoReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.IntegerField(unique=True, verbose_name='协议ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_by', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自动通报配置',
                'db_table': 't_auto_report_config',
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='审批通过后锁定，不可修改', verbose_name='数据锁定'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='sop_confirmed',
            field=models.BooleanField(default=False, help_text='执行前确认已阅读操作规范', verbose_name='SOP已确认'),
        ),
        migrations.CreateModel(
            name='ProjectExecutionContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_requirements', models.JSONField(blank=True, default=list, help_text='[{"category": "检测要求", "content": "...", "priority": "high"}]', verbose_name='关键要求摘要')),
                ('special_notes', models.TextField(blank=True, default='', help_text='CRC维护的项目特殊要求和注意事项', verbose_name='特殊注意事项')),
                ('execution_guidelines', models.JSONField(blank=True, default=dict, help_text='{"sample_handling": "...", "scheduling_notes": "..."}', verbose_name='执行指南')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='创建人 Account ID')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='最后更新人 Account ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('protocol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_context', to='protocol.protocol', verbose_name='关联协议')),
            ],
            options={
                'verbose_name': '项目执行上下文',
                'db_table': 't_project_execution_context',
            },
        ),
        migrations.CreateModel(
            name='CRCDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(help_text='schedule_adjustment/personnel_swap/exception_handling/process_deviation/other', max_length=50, verbose_name='决策类型')),
                ('scope', models.CharField(choices=[('minor', '轻微（范围内自主决策）'), ('moderate', '中等（需CRC主管确认）'), ('major', '重大（需PM确认）')], default='minor', max_length=20, verbose_name='决策范围')),
                ('title', models.CharField(max_length=200, verbose_name='决策标题')),
                ('description', models.TextField(verbose_name='决策内容')),
                ('rationale', models.TextField(blank=True, default='', verbose_name='决策依据')),
                ('impact', models.TextField(blank=True, default='', verbose_name='影响分析')),
                ('outcome', models.TextField(blank=True, default='', verbose_name='决策结果')),
                ('decided_by', models.IntegerField(verbose_name='决策人 Account ID')),
                ('approved_by', models.IntegerField(blank=True, null=True, verbose_name='审批人 Account ID')),
                ('decision_time', models.DateTimeField(auto_now_add=True, verbose_name='决策时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='workorder.projectexecutioncontext', verbose_name='项目执行上下文')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='workorder.workorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': 'CRC决策日志',
                'db_table': 't_crc_decision_log',
                'ordering': ['-decision_time'],
            },
        ),
        migrations.CreateModel(
            name='ChangeResponseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_source', models.CharField(help_text='protocol_amendment/schedule_adjustment/resource_change/other', max_length=50, verbose_name='变更来源')),
                ('change_description', models.TextField(verbose_name='变更内容描述')),
                ('impact_assessment', models.TextField(blank=True, default='', verbose_name='影响评估')),
                ('response_actions', models.JSONField(blank=True, default=list, help_text='[{"action": "...", "assignee_id": 1, "deadline": "2026-01-01", "status": "pending"}]', verbose_name='响应措施')),
                ('status', models.CharField(choices=[('received', '已接收'), ('assessing', '评估中'), ('implementing', '执行中'), ('completed', '已完成')], default='received', max_length=20, verbose_name='响应状态')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('received_by', models.IntegerField(verbose_name='接收人 Account ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_responses', to='workorder.projectexecutioncontext', verbose_name='项目执行上下文')),
            ],
            options={
                'verbose_name': '变更响应记录',
                'db_table': 't_change_response_record',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(help_text='Account ID', verbose_name='作者ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workorder.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '工单评论',
                'db_table': 't_workorder_comment',
                'ordering': ['create_time'],
                'indexes': [models.Index(fields=['work_order'], name='t_workorder_work_or_439de7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='projectexecutioncontext',
            index=models.Index(fields=['protocol'], name='t_project_e_protoco_8552e2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexecutioncontext',
            index=models.Index(fields=['updated_by'], name='t_project_e_updated_a3bbc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectexecutioncontext',
            unique_together={('protocol',)},
        ),
        migrations.AddIndex(
            model_name='crcdecisionlog',
            index=models.Index(fields=['context'], name='t_crc_decis_context_113175_idx'),
        ),
        migrations.AddIndex(
            model_name='crcdecisionlog',
            index=models.Index(fields=['decided_by'], name='t_crc_decis_decided_1fbfb9_idx'),
        ),
        migrations.AddIndex(
            model_name='crcdecisionlog',
            index=models.Index(fields=['decision_time'], name='t_crc_decis_decisio_81df5a_idx'),
        ),
        migrations.AddIndex(
            model_name='changeresponserecord',
            index=models.Index(fields=['context'], name='t_change_re_context_d915ef_idx'),
        ),
        migrations.AddIndex(
            model_name='changeresponserecord',
            index=models.Index(fields=['status'], name='t_change_re_status_ed5b6c_idx'),
        ),
    ]
