# Generated by Django 4.2.27 on 2026-03-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0014_relax_workorder_dual_track_checks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workorder',
            new_name='t_work_orde_assigne_0d885f_idx',
            old_name='t_work_orde_assigne_58caea_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderassignment',
            new_name='t_work_orde_assigne_fe817a_idx',
            old_name='t_work_orde_assigne_05e8aa_idx',
        ),
        migrations.RenameIndex(
            model_name='workorderassignment',
            new_name='t_work_orde_assigne_fa4957_idx',
            old_name='t_work_orde_assigne_0af839_idx',
        ),
        migrations.AddField(
            model_name='instrumentdetection',
            name='data_source',
            field=models.CharField(choices=[('manual_entry', '手工录入'), ('instrument_auto', '仪器自动采集'), ('instrument_import', '仪器文件导入')], default='manual_entry', max_length=30, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='instrumentdetection',
            name='environment_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='检测开始时的温湿度快照：{"temperature": 22.5, "humidity": 48.0, "is_compliant": true, ...}', verbose_name='环境快照'),
        ),
        migrations.AddField(
            model_name='instrumentdetection',
            name='is_voided',
            field=models.BooleanField(default=False, verbose_name='是否已作废'),
        ),
        migrations.AddField(
            model_name='instrumentdetection',
            name='operator_qualification_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='检测开始时的操作人方法资质和设备授权快照', verbose_name='操作人资质快照'),
        ),
        migrations.AddField(
            model_name='instrumentdetection',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作废时间'),
        ),
        migrations.AddField(
            model_name='instrumentdetection',
            name='voided_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='作废人 Account ID'),
        ),
        migrations.AddField(
            model_name='instrumentdetection',
            name='voided_reason',
            field=models.TextField(blank=True, default='', verbose_name='作废原因'),
        ),
    ]
