# Generated by Django 4.2.27 on 2026-03-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0020_merge_0019_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatorschedulenote',
            name='source',
        ),
    ]
