# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0003_add_enrollment_created_by_id'),
        ('workorder', '0006_workorderqualityaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('severity', models.CharField(choices=[('mild', '轻度'), ('moderate', '中度'), ('severe', '重度')], max_length=20, verbose_name='严重程度')),
                ('relation', models.CharField(choices=[('unrelated', '无关'), ('possible', '可能有关'), ('probable', '很可能有关'), ('certain', '肯定有关')], max_length=20, verbose_name='因果关系')),
                ('action_taken', models.TextField(blank=True, default='', verbose_name='处理措施')),
                ('outcome', models.CharField(choices=[('recovered', '痊愈'), ('recovering', '好转'), ('not_recovered', '未好转'), ('sequelae', '有后遗症'), ('death', '死亡'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='转归')),
                ('is_sae', models.BooleanField(default=False, help_text='严重不良事件（导致死亡、危及生命、住院等）', verbose_name='是否SAE')),
                ('status', models.CharField(choices=[('reported', '已上报'), ('under_review', '审核中'), ('approved', '已确认'), ('following', '随访中'), ('closed', '已关闭')], db_index=True, default='reported', max_length=20, verbose_name='状态')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='上报日期')),
                ('feishu_approval_instance_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='飞书审批实例ID')),
                ('feishu_urgent_message_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书加急消息ID')),
                ('reported_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='报告人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adverse_events', to='subject.enrollment', verbose_name='关联入组')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_events', to='workorder.workorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '不良事件',
                'db_table': 't_adverse_event',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='AEFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=1, verbose_name='随访序号')),
                ('followup_date', models.DateField(verbose_name='随访日期')),
                ('current_status', models.TextField(verbose_name='当前状态')),
                ('outcome_update', models.CharField(blank=True, default='', max_length=30, verbose_name='转归更新')),
                ('severity_change', models.CharField(blank=True, default='', max_length=50, verbose_name='严重程度变化')),
                ('treatment_update', models.TextField(blank=True, default='', verbose_name='治疗更新')),
                ('requires_further_followup', models.BooleanField(default=True, verbose_name='需要继续随访')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='下次随访日期')),
                ('recorded_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='记录人ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('adverse_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='safety.adverseevent', verbose_name='不良事件')),
            ],
            options={
                'verbose_name': 'AE随访记录',
                'db_table': 't_ae_follow_up',
                'ordering': ['adverse_event', 'sequence'],
                'indexes': [models.Index(fields=['adverse_event', 'sequence'], name='t_ae_follow_adverse_a7c631_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='adverseevent',
            index=models.Index(fields=['enrollment', 'status'], name='t_adverse_e_enrollm_f6a4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='adverseevent',
            index=models.Index(fields=['status', 'severity'], name='t_adverse_e_status_1dd502_idx'),
        ),
        migrations.AddIndex(
            model_name='adverseevent',
            index=models.Index(fields=['is_sae'], name='t_adverse_e_is_sae_4110e4_idx'),
        ),
        migrations.AddIndex(
            model_name='adverseevent',
            index=models.Index(fields=['report_date'], name='t_adverse_e_report__7853b2_idx'),
        ),
    ]
