# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseevent',
            name='change_request_id',
            field=models.IntegerField(blank=True, help_text='ChangeRequest ID', null=True, verbose_name='关联变更ID'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='deviation_id',
            field=models.IntegerField(blank=True, help_text='Deviation ID', null=True, verbose_name='关联偏差ID'),
        ),
    ]
