# Generated by Django 4.2.29 on 2026-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_adverseevent_change_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='severity',
            field=models.CharField(choices=[('mild', '轻微'), ('moderate', '中度'), ('severe', '严重'), ('very_severe', '非常严重')], max_length=20, verbose_name='严重程度'),
        ),
    ]
