# Generated by Django 4.2.29 on 2026-03-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0034_mini_adverse_event_report'),
        ('safety', '0003_ae_severity_four_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAdverseEventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(db_index=True, max_length=100, verbose_name='项目编号')),
                ('project_name', models.CharField(blank=True, default='', max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='症状描述')),
                ('severity', models.CharField(choices=[('mild', '轻微'), ('moderate', '中度'), ('severe', '严重'), ('very_severe', '非常严重')], max_length=20, verbose_name='严重程度')),
                ('occur_date', models.DateField(verbose_name='发生日期')),
                ('status', models.CharField(choices=[('reported', '已上报'), ('under_review', '审核中'), ('closed', '已关闭')], db_index=True, default='reported', max_length=20, verbose_name='处理状态')),
                ('photo_urls', models.JSONField(blank=True, default=list, verbose_name='照片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_ae_reports', to='subject.subject', verbose_name='受试者')),
            ],
            options={
                'verbose_name': '小程序不良反应上报',
                'db_table': 't_mini_adverse_event_report',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['subject', 'project_code'], name='t_mini_adve_subject_0c5df0_idx'), models.Index(fields=['status'], name='t_mini_adve_status_13f976_idx'), models.Index(fields=['create_time'], name='t_mini_adve_create__7cced5_idx')],
            },
        ),
    ]
