"""
将 ROLE_MATRIX 全量岗位同步到 t_worker_role_definition。
覆盖蓝图中定义的全部 28 个岗位。
"""
from django.core.management.base import BaseCommand

from apps.secretary.models_roles import WorkerRoleDefinition

INITIAL_ROLES = [
    # === 客户与需求簇 ===
    {'role_code': 'customer_demand_analyst', 'role_name': '客户需求分析员', 'role_cluster': '客户与需求簇',
     'service_targets': ['销售', '客户经理', '项目负责人'], 'core_scenarios': ['新客户需求进入', '老客户变更需求'],
     'input_contract': ['会议纪要', '聊天记录', '需求文档', '历史案例'], 'output_contract': ['需求摘要', '缺口清单', '评审材料'],
     'automation_level': 'L2', 'human_confirmation_points': ['需求边界承诺', '客户口径确认'],
     'kpi_metrics': ['需求澄清轮次下降', '内部评审准备时间下降'],
     'mapped_agent_ids': ['crm-agent', 'knowledge-agent'], 'mapped_skill_ids': [], 'workstation_scope': ['crm', 'secretary'],
     'baseline_manual_minutes': 30},
    {'role_code': 'opportunity_tracker', 'role_name': '商机推进助理', 'role_cluster': '客户与需求簇',
     'service_targets': ['销售', '客户经理'], 'core_scenarios': ['商机推进', '客户跟进', '节点提醒'],
     'input_contract': ['CRM 状态', '沟通记录', '待办事项'], 'output_contract': ['跟进提醒', '商机状态摘要', '下一步建议'],
     'automation_level': 'L2', 'human_confirmation_points': ['对客户的正式承诺'],
     'kpi_metrics': ['商机流转周期', '漏跟进次数'],
     'mapped_agent_ids': ['crm-agent'], 'mapped_skill_ids': [], 'workstation_scope': ['crm'],
     'baseline_manual_minutes': 10},
    {'role_code': 'solution_designer', 'role_name': '方案生成员', 'role_cluster': '客户与需求簇',
     'service_targets': ['项目负责人', '医学/研究支持', '财务'], 'core_scenarios': ['初版方案', '可行性讨论', '报价准备'],
     'input_contract': ['需求摘要', '历史模板', '资源约束'], 'output_contract': ['方案初稿', '报价输入项', '风险清单'],
     'automation_level': 'L2', 'human_confirmation_points': ['方案定稿', '报价最终拍板'],
     'kpi_metrics': ['方案初稿产出时间', '方案返工率'],
     'mapped_agent_ids': ['protocol-agent', 'solution-designer'], 'mapped_skill_ids': ['protocol-parser', 'protocol-to-startup-pack'],
     'workstation_scope': ['research', 'finance'], 'baseline_manual_minutes': 60},
    {'role_code': 'quote_analyst', 'role_name': '报价助手', 'role_cluster': '客户与需求簇',
     'service_targets': ['财务', '销售'], 'core_scenarios': ['成本测算', '报价支持'],
     'input_contract': ['方案要素', '资源消耗', '历史报价'], 'output_contract': ['成本拆解', '报价输入清单'],
     'automation_level': 'L2', 'human_confirmation_points': ['报价最终签发'],
     'kpi_metrics': ['报价准备时间', '漏项率'],
     'mapped_agent_ids': ['finance-agent'], 'mapped_skill_ids': ['auto-quotation'], 'workstation_scope': ['finance'],
     'baseline_manual_minutes': 40},
    # === 项目准备与启动簇 ===
    {'role_code': 'project_docs_coordinator', 'role_name': '项目资料统筹员', 'role_cluster': '项目准备与启动簇',
     'service_targets': ['项目经理', '研究支持', 'QA'], 'core_scenarios': ['立项后全套资料准备'],
     'input_contract': ['协议', 'SOP', '模板', '培训资料'], 'output_contract': ['资料清单', '缺口清单', '角色化打包'],
     'automation_level': 'L2', 'human_confirmation_points': ['对外正式交付资料包'],
     'kpi_metrics': ['启动资料缺失率', '资料准备时间'],
     'mapped_agent_ids': ['knowledge-agent', 'orchestration-agent'], 'mapped_skill_ids': ['protocol-to-startup-pack', 'knowledge-hybrid-search'],
     'workstation_scope': ['research'], 'baseline_manual_minutes': 45},
    {'role_code': 'version_guardian', 'role_name': '版本守护员', 'role_cluster': '项目准备与启动簇',
     'service_targets': ['项目经理', 'QA'], 'core_scenarios': ['文档版本一致性检查'],
     'input_contract': ['当前版本库', '项目资料'], 'output_contract': ['版本冲突报告', '旧版预警'],
     'automation_level': 'L2', 'human_confirmation_points': ['版本替换最终确认'],
     'kpi_metrics': ['版本冲突次数', '错误引用率'],
     'mapped_agent_ids': ['knowledge-agent'], 'mapped_skill_ids': ['knowledge-hybrid-search'],
     'workstation_scope': ['research'], 'baseline_manual_minutes': 15},
    {'role_code': 'startup_gate_assistant', 'role_name': '启动门禁助理', 'role_cluster': '项目准备与启动簇',
     'service_targets': ['项目经理', 'QA', '合规负责人'], 'core_scenarios': ['项目启动前核验'],
     'input_contract': ['人机料法环数据', '审批状态'], 'output_contract': ['启动核验结果', '阻塞项清单'],
     'automation_level': 'L4', 'human_confirmation_points': ['最终启动放行'],
     'kpi_metrics': ['启动后返工率', '阻塞提前发现率'],
     'mapped_agent_ids': ['orchestration-agent'], 'mapped_skill_ids': ['protocol-to-startup-pack'],
     'workstation_scope': ['execution'], 'baseline_manual_minutes': 30},
    {'role_code': 'resource_matcher', 'role_name': '资源匹配员', 'role_cluster': '项目准备与启动簇',
     'service_targets': ['项目经理', '资源协调人员'], 'core_scenarios': ['项目启动', '资源准备'],
     'input_contract': ['设备', '人员', '场地', '物料'], 'output_contract': ['资源匹配方案', '缺口报告'],
     'automation_level': 'L2', 'human_confirmation_points': ['关键资源调配决策'],
     'kpi_metrics': ['资源冲突次数', '资源准备时效'],
     'mapped_agent_ids': ['execution-agent'], 'mapped_skill_ids': ['visit-scheduler', 'equipment-lifecycle'],
     'workstation_scope': ['execution', 'equipment'], 'baseline_manual_minutes': 25},
    # === 排程与工单簇 ===
    {'role_code': 'scheduling_optimizer', 'role_name': '排程优化员', 'role_cluster': '排程与工单簇',
     'service_targets': ['项目经理', '执行主管', '调度人员'], 'core_scenarios': ['启动排程', '变更排程', '资源冲突排程'],
     'input_contract': ['项目里程碑', '资源约束'], 'output_contract': ['排程草案', '冲突清单', '优先级建议'],
     'automation_level': 'L2', 'human_confirmation_points': ['高优先级取舍'],
     'kpi_metrics': ['排程调整次数', '冲突提前发现率'],
     'mapped_agent_ids': ['execution-agent'], 'mapped_skill_ids': ['visit-scheduler'], 'workstation_scope': ['execution'],
     'baseline_manual_minutes': 20},
    {'role_code': 'workorder_matcher', 'role_name': '工单匹配员', 'role_cluster': '排程与工单簇',
     'service_targets': ['调度人员', '执行主管'], 'core_scenarios': ['派单与重派单'],
     'input_contract': ['工单要求', '人员资质', '设备状态'], 'output_contract': ['推荐执行人', '替代方案'],
     'automation_level': 'L3', 'human_confirmation_points': ['派单最终确认'],
     'kpi_metrics': ['错派率', '平均派单时间'],
     'mapped_agent_ids': ['execution-agent'], 'mapped_skill_ids': ['workorder-automation'], 'workstation_scope': ['execution'],
     'baseline_manual_minutes': 15},
    # === 受试者服务簇 ===
    {'role_code': 'recruitment_screener', 'role_name': '招募助理', 'role_cluster': '受试者服务簇',
     'service_targets': ['招募人员', 'CRC'], 'core_scenarios': ['初筛', '招募线索管理'],
     'input_contract': ['招募条件', '受试者资料'], 'output_contract': ['初筛结果', '候选优先级'],
     'automation_level': 'L2', 'human_confirmation_points': ['入排标准最终判断'],
     'kpi_metrics': ['招募转化率', '筛选耗时'],
     'mapped_agent_ids': ['recruitment-bot'], 'mapped_skill_ids': ['recruitment-screener'], 'workstation_scope': ['recruitment'],
     'baseline_manual_minutes': 20},
    {'role_code': 'reception_assistant', 'role_name': '接待助理', 'role_cluster': '受试者服务簇',
     'service_targets': ['接待人员', '受试者'], 'core_scenarios': ['到访签到', '叫号', '引导'],
     'input_contract': ['预约信息', '访视计划'], 'output_contract': ['签到状态', '队列状态'],
     'automation_level': 'L2', 'human_confirmation_points': ['现场异常处置'],
     'kpi_metrics': ['平均等待时间', '现场差错率'],
     'mapped_agent_ids': ['reception-assistant'], 'mapped_skill_ids': ['reception-automation'], 'workstation_scope': ['reception'],
     'baseline_manual_minutes': 5},
    # === 质量与合规簇 ===
    {'role_code': 'quality_guardian', 'role_name': '质量守护员', 'role_cluster': '质量与合规簇',
     'service_targets': ['QA', '质量负责人', '项目经理'], 'core_scenarios': ['偏差识别', '质量趋势监控'],
     'input_contract': ['工单记录', '样品链路', '审计日志'], 'output_contract': ['偏差线索', '质量热点', '风险趋势'],
     'automation_level': 'L2', 'human_confirmation_points': ['偏差定级', '质量裁决'],
     'kpi_metrics': ['偏差提前发现率', '质量热点响应时长'],
     'mapped_agent_ids': ['quality-guardian'], 'mapped_skill_ids': ['crf-validator', 'sop-lifecycle'], 'workstation_scope': ['quality'],
     'baseline_manual_minutes': 25},
    {'role_code': 'compliance_reviewer', 'role_name': '合规审查员', 'role_cluster': '质量与合规簇',
     'service_targets': ['合规负责人', 'QA'], 'core_scenarios': ['高风险动作预审', '权限边界校验'],
     'input_contract': ['权限模型', '审批状态', '法规规则'], 'output_contract': ['审查意见', '越权告警'],
     'automation_level': 'L4', 'human_confirmation_points': ['合规裁决', '例外批准'],
     'kpi_metrics': ['越权拦截率', '高风险动作命中率'],
     'mapped_agent_ids': ['ethics-agent'], 'mapped_skill_ids': ['audit-trail-engine'], 'workstation_scope': ['ethics', 'quality'],
     'baseline_manual_minutes': 35},
    {'role_code': 'ethics_liaison', 'role_name': '伦理资料助理', 'role_cluster': '质量与合规簇',
     'service_targets': ['伦理负责人', '研究支持'], 'core_scenarios': ['伦理提交', '资料一致性检查'],
     'input_contract': ['协议', '受试者材料', '审批资料'], 'output_contract': ['伦理资料包', '缺项清单'],
     'automation_level': 'L2', 'human_confirmation_points': ['伦理正式提交与答复'],
     'kpi_metrics': ['伦理补件次数', '资料缺失率'],
     'mapped_agent_ids': ['ethics-agent', 'knowledge-agent'], 'mapped_skill_ids': [], 'workstation_scope': ['ethics'],
     'baseline_manual_minutes': 30},
    # === 报告、经营与知识簇 ===
    {'role_code': 'report_generator', 'role_name': '报告生成员', 'role_cluster': '报告、经营与知识簇',
     'service_targets': ['项目负责人', '报告人员', '客户经理'], 'core_scenarios': ['阶段性汇报', '结题交付'],
     'input_contract': ['执行记录', '测试结果', '项目状态'], 'output_contract': ['报告初稿', '章节摘要'],
     'automation_level': 'L2', 'human_confirmation_points': ['对外正式发布'],
     'kpi_metrics': ['报告准备周期', '返工率'],
     'mapped_agent_ids': ['knowledge-agent', 'report-agent'], 'mapped_skill_ids': ['efficacy-report-generator'],
     'workstation_scope': ['research'], 'baseline_manual_minutes': 90},
    {'role_code': 'business_analyst', 'role_name': '经营分析员', 'role_cluster': '报告、经营与知识簇',
     'service_targets': ['管理层', '项目经理'], 'core_scenarios': ['日报', '周报', '经营复盘'],
     'input_contract': ['项目状态', '资源负荷', '财务指标'], 'output_contract': ['经营摘要', '风险列表', '价值看板'],
     'automation_level': 'L2', 'human_confirmation_points': ['资源调整与经营决策'],
     'kpi_metrics': ['经营分析准备时间'],
     'mapped_agent_ids': ['orchestration-agent', 'knowledge-agent'], 'mapped_skill_ids': ['business-dashboard'],
     'workstation_scope': ['secretary'], 'baseline_manual_minutes': 45},
    {'role_code': 'knowledge_curator', 'role_name': '知识管家', 'role_cluster': '报告、经营与知识簇',
     'service_targets': ['全体业务角色'], 'core_scenarios': ['案例沉淀', '知识召回', '经验复用'],
     'input_contract': ['项目资料', '复盘报告', '案例'], 'output_contract': ['知识条目', '检索结果', '经验摘要'],
     'automation_level': 'L1', 'human_confirmation_points': ['知识正式发布', '制度更新'],
     'kpi_metrics': ['知识复用率', '检索命中率'],
     'mapped_agent_ids': ['knowledge-agent'], 'mapped_skill_ids': ['knowledge-hybrid-search'],
     'workstation_scope': [], 'baseline_manual_minutes': 10},
    # === 编排与治理簇 ===
    {'role_code': 'orchestration_hub', 'role_name': '编排中枢', 'role_cluster': '编排与治理簇',
     'service_targets': ['全体业务角色'], 'core_scenarios': ['复杂任务进入', '跨岗位协同'],
     'input_contract': ['用户意图', '上下文', '技能注册表'], 'output_contract': ['任务拆解结果', '执行聚合结果'],
     'automation_level': 'L3', 'human_confirmation_points': ['高风险跨域动作确认'],
     'kpi_metrics': ['任务拆解准确率', '跨岗位协同完成率'],
     'mapped_agent_ids': ['orchestration-agent'], 'mapped_skill_ids': ['secretary-orchestrator'],
     'workstation_scope': ['secretary'], 'baseline_manual_minutes': 5},
    # === 人事与人员簇 ===
    {'role_code': 'hr_assistant', 'role_name': '人事服务助理', 'role_cluster': '人事与人员簇',
     'service_targets': ['HR', '员工'], 'core_scenarios': ['资质管理', '培训安排', '排班'],
     'input_contract': ['人员档案', 'GCP 证书', '培训记录'], 'output_contract': ['到期预警', '培训计划', '排班建议'],
     'automation_level': 'L2', 'human_confirmation_points': ['重大人事决策'],
     'kpi_metrics': ['证书逾期率', '培训覆盖率'],
     'mapped_agent_ids': ['talent-agent'], 'mapped_skill_ids': ['hr-self-service', 'shift-planner'],
     'workstation_scope': ['hr', 'lab-personnel'], 'baseline_manual_minutes': 15},
    # === 设备与物料簇 ===
    {'role_code': 'equipment_manager', 'role_name': '设备管理员', 'role_cluster': '设备与物料簇',
     'service_targets': ['设备管理员', '实验人员'], 'core_scenarios': ['校准管理', '维护计划', '使用记录'],
     'input_contract': ['设备档案', '校准状态', '维护工单'], 'output_contract': ['校准到期预警', '维护建议'],
     'automation_level': 'L2', 'human_confirmation_points': ['关键设备停用决策'],
     'kpi_metrics': ['校准逾期率', '设备故障率'],
     'mapped_agent_ids': ['equipment-agent'], 'mapped_skill_ids': ['equipment-lifecycle'],
     'workstation_scope': ['equipment'], 'baseline_manual_minutes': 15},
]


class Command(BaseCommand):
    help = '将 ROLE_MATRIX 全量岗位同步到 t_worker_role_definition（含九要素与映射）'

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for role in INITIAL_ROLES:
            _, was_created = WorkerRoleDefinition.objects.update_or_create(
                role_code=role['role_code'],
                defaults={
                    'role_name': role['role_name'],
                    'role_cluster': role['role_cluster'],
                    'service_targets': role.get('service_targets', []),
                    'core_scenarios': role.get('core_scenarios', []),
                    'input_contract': role.get('input_contract', []),
                    'output_contract': role.get('output_contract', []),
                    'automation_level': role.get('automation_level', ''),
                    'human_confirmation_points': role.get('human_confirmation_points', []),
                    'kpi_metrics': role.get('kpi_metrics', []),
                    'mapped_agent_ids': role.get('mapped_agent_ids', []),
                    'mapped_skill_ids': role.get('mapped_skill_ids', []),
                    'workstation_scope': role.get('workstation_scope', []),
                    'baseline_manual_minutes': role.get('baseline_manual_minutes'),
                    'enabled': True,
                },
            )
            if was_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(
            self.style.SUCCESS(f'Worker roles synced: created={created} updated={updated}')
        )
