# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scanauditlog',
            new_name='t_qrcode_sc_qr_reco_c3e34c_idx',
            old_name='qrcode_scana_qr_reco_idx',
        ),
        migrations.RenameIndex(
            model_name='scanauditlog',
            new_name='t_qrcode_sc_scanner_8f7988_idx',
            old_name='qrcode_scana_scanner_idx',
        ),
    ]
