# Generated by Django 4.2.27 on 2026-02-15 02:38

import apps.agent_gateway.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=apps.agent_gateway.models.generate_uuid, max_length=100, unique=True, verbose_name='会话ID')),
                ('account_id', models.IntegerField(db_index=True, help_text='用户账号ID', verbose_name='账号ID')),
                ('agent_id', models.CharField(db_index=True, max_length=100, verbose_name='智能体ID')),
                ('context', models.JSONField(default=dict, help_text='会话上下文信息', verbose_name='上下文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '智能体会话',
                'db_table': 't_agent_session',
                'indexes': [models.Index(fields=['session_id'], name='t_agent_ses_session_e925d7_idx'), models.Index(fields=['account_id', 'agent_id'], name='t_agent_ses_account_f79566_idx'), models.Index(fields=['created_at'], name='t_agent_ses_created_2cc89c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, help_text='如：solution-designer, protocol-agent', max_length=100, unique=True, verbose_name='智能体ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('capabilities', models.JSONField(default=list, help_text='智能体的能力列表，如：["协议解析", "方案设计"]', verbose_name='能力列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '智能体定义',
                'db_table': 't_agent_definition',
                'indexes': [models.Index(fields=['agent_id'], name='t_agent_def_agent_i_011849_idx'), models.Index(fields=['is_active'], name='t_agent_def_is_acti_281e49_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=100, verbose_name='智能体ID')),
                ('input_text', models.TextField(blank=True, default='', verbose_name='输入文本')),
                ('output_text', models.TextField(blank=True, default='', verbose_name='输出文本')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时（毫秒）')),
                ('token_usage', models.JSONField(blank=True, help_text='{"input_tokens": 100, "output_tokens": 200}', null=True, verbose_name='Token使用量')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='agent_gateway.agentsession')),
            ],
            options={
                'verbose_name': '智能体调用',
                'db_table': 't_agent_call',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='t_agent_cal_session_454a4a_idx'), models.Index(fields=['agent_id', 'status'], name='t_agent_cal_agent_i_0122e4_idx'), models.Index(fields=['created_at'], name='t_agent_cal_created_b8919a_idx')],
            },
        ),
    ]
