# Generated by Django 4.2.27 on 2026-02-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcall',
            name='model_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='模型ID'),
        ),
        migrations.AddField(
            model_name='agentcall',
            name='provider',
            field=models.CharField(choices=[('ark', '火山引擎 ARK'), ('kimi', 'Kimi (Moonshot AI)')], default='kimi', max_length=20, verbose_name='服务商'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='max_tokens',
            field=models.IntegerField(default=4096, verbose_name='最大 token 数'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='model_id',
            field=models.CharField(blank=True, default='', help_text='ARK: endpoint ID (如 ep-xxx); Kimi: 模型名 (如 moonshot-v1-128k)', max_length=200, verbose_name='模型ID'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='provider',
            field=models.CharField(choices=[('ark', '火山引擎 ARK'), ('kimi', 'Kimi (Moonshot AI)')], default='kimi', help_text='ark=火山引擎(复杂任务), kimi=Kimi(轻量任务)', max_length=20, verbose_name='服务商'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='定义智能体角色和行为的系统提示词', verbose_name='系统提示词'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='0.0-2.0，越高越随机', verbose_name='温度'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='messages',
            field=models.JSONField(default=list, help_text='OpenAI 格式: [{"role": "user", "content": "..."}, ...]', verbose_name='消息历史'),
        ),
        migrations.AlterField(
            model_name='agentcall',
            name='token_usage',
            field=models.JSONField(blank=True, help_text='{"prompt_tokens": 100, "completion_tokens": 200, "total_tokens": 300}', null=True, verbose_name='Token使用量'),
        ),
    ]
