# Generated by Django 4.2.27 on 2026-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_gateway', '0002_agentcall_model_id_agentcall_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcall',
            name='tool_calls_log',
            field=models.JSONField(blank=True, default=list, help_text='[{"tool": "databus_snapshot", "args": {...}, "result_size": 123, "elapsed_ms": 45}]', verbose_name='工具调用记录'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='tools',
            field=models.JSONField(blank=True, default=list, help_text='Agent 可调用的工具名称列表，如 ["databus_snapshot", "knowledge_search"]', verbose_name='可用工具列表'),
        ),
    ]
