# Generated by Django 4.2.27 on 2026-03-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_gateway', '0003_add_tools_and_tool_calls_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='头像/图标URL'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='is_editable_via_ui',
            field=models.BooleanField(default=True, verbose_name='允许UI编辑'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='knowledge_enabled',
            field=models.BooleanField(default=False, verbose_name='知识库注入'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='knowledge_top_k',
            field=models.IntegerField(default=3, verbose_name='知识库召回条数'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='phase',
            field=models.CharField(blank=True, default='', help_text='数字员工成熟阶段标识', max_length=32, verbose_name='成熟阶段'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='role_title',
            field=models.CharField(blank=True, default='', help_text='业务语言展示，如：协议解析专员', max_length=120, verbose_name='岗位名称'),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='tier',
            field=models.CharField(blank=True, choices=[('orchestration', '编排中枢'), ('digital_human', '数字人'), ('agent', '智能体'), ('engine', '自动化引擎')], default='', help_text='orchestration/digital_human/agent/engine', max_length=32, verbose_name='层级'),
        ),
        migrations.AddIndex(
            model_name='agentdefinition',
            index=models.Index(fields=['tier'], name='t_agent_def_tier_75d512_idx'),
        ),
    ]
