# Generated by Django 4.2.27 on 2026-03-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_gateway', '0005_agentdefinition_governance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcall',
            name='provider',
            field=models.CharField(choices=[('ark', '火山引擎 ARK'), ('kimi', 'Kimi (Moonshot AI)'), ('deepseek', 'DeepSeek（文档生成/长文本写作）')], default='kimi', max_length=20, verbose_name='服务商'),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='escalation_targets',
            field=models.JSONField(blank=True, default=list, help_text='[{"condition":"超出范围","target":"orchestration-agent"}]', verbose_name='升级目标'),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='parent_agent_id',
            field=models.CharField(blank=True, default='', help_text='汇报给谁，如 orchestration-agent', max_length=80, verbose_name='上级 Agent'),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='provider',
            field=models.CharField(choices=[('ark', '火山引擎 ARK'), ('kimi', 'Kimi (Moonshot AI)'), ('deepseek', 'DeepSeek（文档生成/长文本写作）')], default='kimi', help_text='ark=火山引擎(复杂任务), kimi=Kimi(轻量任务)', max_length=20, verbose_name='服务商'),
        ),
    ]
