# Generated by Django 4.2.27 on 2026-03-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_gateway', '0007_agent_knowledge_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentKnowledgeDomain',
        ),
    ]
