# Generated by Django 4.2.27 on 2026-02-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('report_type', models.CharField(choices=[('visit_summary', '访视汇总'), ('enrollment_status', '入组状态'), ('safety_report', '安全性报告'), ('compliance_report', '合规报告'), ('workorder_summary', '工单汇总'), ('custom', '自定义')], max_length=30, verbose_name='报告类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('template_config', models.JSONField(blank=True, default=dict, help_text='数据源、字段映射、格式配置', verbose_name='模板配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报告模板',
                'db_table': 't_report_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('visit_summary', '访视汇总'), ('enrollment_status', '入组状态'), ('safety_report', '安全性报告'), ('compliance_report', '合规报告'), ('workorder_summary', '工单汇总'), ('custom', '自定义')], max_length=30, verbose_name='报告类型')),
                ('title', models.CharField(max_length=500, verbose_name='报告标题')),
                ('protocol_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='协议ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generating', '生成中'), ('generated', '已生成'), ('published', '已发布'), ('failed', '生成失败')], default='draft', max_length=20, verbose_name='状态')),
                ('content', models.TextField(blank=True, default='', verbose_name='报告内容')),
                ('data_snapshot', models.JSONField(blank=True, default=dict, verbose_name='数据快照')),
                ('feishu_doc_token', models.CharField(blank=True, default='', max_length=200, verbose_name='飞书文档token')),
                ('generated_by_id', models.IntegerField(blank=True, null=True, verbose_name='生成人ID')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='report.reporttemplate', verbose_name='使用模板')),
            ],
            options={
                'verbose_name': '报告',
                'db_table': 't_report',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['protocol_id', 'report_type'], name='t_report_protoco_d09c1f_idx'), models.Index(fields=['status'], name='t_report_status_a3b72e_idx')],
            },
        ),
    ]
