# Generated by Django 4.2.21 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=120, verbose_name='设备ID')),
                ('reading_type', models.CharField(db_index=True, max_length=80, verbose_name='读数类型')),
                ('value', models.FloatField(verbose_name='读数值')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='单位')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='采集时间')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='原始载荷')),
                ('source', models.CharField(default='https_push', max_length=40, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '设备读数',
                'verbose_name_plural': '设备读数',
                'db_table': 't_iot_device_reading',
            },
        ),
        migrations.AddIndex(
            model_name='devicereading',
            index=models.Index(fields=['device_id', 'timestamp'], name='t_iot_devic_device__8f9025_idx'),
        ),
        migrations.AddIndex(
            model_name='devicereading',
            index=models.Index(fields=['reading_type', 'timestamp'], name='t_iot_devic_reading_5f709f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicereading',
            index=models.Index(fields=['created_at'], name='t_iot_devic_created_cf510e_idx'),
        ),
    ]
