# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicereading',
            new_name='t_iot_devic_device__9caac5_idx',
            old_name='t_iot_devic_device__8f9025_idx',
        ),
        migrations.RenameIndex(
            model_name='devicereading',
            new_name='t_iot_devic_reading_5f047a_idx',
            old_name='t_iot_devic_reading_5f709f_idx',
        ),
        migrations.RenameIndex(
            model_name='devicereading',
            new_name='t_iot_devic_created_5c8d40_idx',
            old_name='t_iot_devic_created_cf510e_idx',
        ),
    ]
