# Generated by Django 4.2.27 on 2026-03-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_full_link', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='project_ful_executi_924710_idx',
            old_name='project_ful_executi_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_ful_schedul_eb4aa0_idx',
            old_name='project_ful_schedul_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_ful_created_122d5d_idx',
            old_name='project_ful_created_idx',
        ),
        migrations.RenameIndex(
            model_name='projectprotocol',
            new_name='project_ful_project_c69655_idx',
            old_name='project_ful_project_idx',
        ),
    ]
