# Generated by Django 4.2.27 on 2026-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_intake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldataingestcandidate',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='0.0~1.0，由各字段置信度加权平均得出；>=0.8 可批量自动批准', verbose_name='整体置信度'),
        ),
        migrations.AlterField(
            model_name='externaldataingestcandidate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externaldataingestcandidate',
            name='ingestion_log',
            field=models.JSONField(blank=True, default=dict, help_text='接入操作的详细结果，含创建/更新的字段清单', verbose_name='接入日志'),
        ),
        migrations.AlterField(
            model_name='externaldataingestcandidate',
            name='source_display_title',
            field=models.CharField(blank=True, default='', help_text='在审核列表中展示的简短标题，如"LIMS仪器：VISIA-001"', max_length=300, verbose_name='来源摘要标题'),
        ),
    ]
