# Generated by Django 4.2.27 on 2026-02-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='操作人ID')),
                ('account_name', models.CharField(max_length=100, verbose_name='操作人名称')),
                ('account_type', models.CharField(blank=True, default='', max_length=20, verbose_name='操作人类型')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('LOGIN', '登录'), ('LOGOUT', '登出'), ('APPROVE', '审批'), ('REJECT', '拒绝'), ('SIGN', '签名'), ('EXPORT', '导出'), ('VIEW', '查看')], max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='操作描述')),
                ('resource_type', models.CharField(max_length=50, verbose_name='资源类型')),
                ('resource_id', models.CharField(max_length=100, verbose_name='资源ID')),
                ('resource_name', models.CharField(blank=True, default='', max_length=200, verbose_name='资源名称')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='变更前')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='变更后')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='变更字段列表')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('request_id', models.CharField(blank=True, default='', max_length=50, verbose_name='请求ID')),
                ('project_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='项目ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'db_table': 't_audit_log',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='t_audit_log_resourc_07fba6_idx'), models.Index(fields=['account_id', 'create_time'], name='t_audit_log_account_0f3d2b_idx'), models.Index(fields=['action', 'create_time'], name='t_audit_log_action_5333a6_idx')],
            },
        ),
    ]
