# Generated by Django 4.2.27 on 2026-02-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='合同编号')),
                ('project', models.CharField(max_length=300, verbose_name='项目名称')),
                ('client', models.CharField(max_length=200, verbose_name='客户')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='合同金额')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='签署日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='到期日')),
                ('status', models.CharField(choices=[('negotiating', '谈判中'), ('signed', '已签署'), ('active', '执行中'), ('completed', '已完成'), ('terminated', '已终止')], default='negotiating', max_length=20, verbose_name='状态')),
                ('feishu_approval_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书审批ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='系统创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '合同',
                'db_table': 't_contract',
                'ordering': ['-signed_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='发票编号')),
                ('client', models.CharField(max_length=200, verbose_name='客户')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='不含税金额')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='税额')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='含税金额')),
                ('type', models.CharField(choices=[('milestone', '里程碑'), ('monthly', '月度'), ('final', '结项')], max_length=20, verbose_name='类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审批'), ('sent', '已寄出'), ('paid', '已回款')], default='draft', max_length=20, verbose_name='状态')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='开票日期')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='系统创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.contract', verbose_name='关联合同')),
            ],
            options={
                'verbose_name': '发票',
                'db_table': 't_invoice',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='报价编号')),
                ('project', models.CharField(max_length=300, verbose_name='项目名称')),
                ('client', models.CharField(max_length=200, verbose_name='客户')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='报价金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已发送'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('expired', '已过期')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateField(verbose_name='创建日期')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='系统创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '报价',
                'db_table': 't_quote',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='t_quote_status_44637e_idx'), models.Index(fields=['client', 'status'], name='t_quote_client_2022df_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='回款编号')),
                ('client', models.CharField(max_length=200, verbose_name='客户')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='应收金额')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='实收金额')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='到账日')),
                ('method', models.CharField(blank=True, default='', max_length=50, verbose_name='付款方式')),
                ('status', models.CharField(choices=[('expected', '待回款'), ('partial', '部分回'), ('full', '已到账'), ('overdue', '已逾期')], default='expected', max_length=20, verbose_name='状态')),
                ('days_overdue', models.IntegerField(default=0, verbose_name='逾期天数')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='系统创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='关联发票')),
            ],
            options={
                'verbose_name': '回款',
                'db_table': 't_payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='t_contract_status_45a85c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client', 'status'], name='t_contract_client_17ebcc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='t_payment_status_b43af0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='t_payment_invoice_c60800_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='t_invoice_status_b305d4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['contract', 'status'], name='t_invoice_contrac_42350b_idx'),
        ),
    ]
