# Generated by Django 4.2.27 on 2026-02-18 12:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budgetcategory_budgetitem_contract_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='parent_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='finance.quote', verbose_name='原始报价'),
        ),
        migrations.AddField(
            model_name='quote',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审批'), ('sent', '已寄出'), ('paid', '已回款'), ('voided', '已作废'), ('credited', '已红冲')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('specification', models.CharField(blank=True, default='', max_length=100, verbose_name='规格型号')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='金额')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='成本估算')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.quote', verbose_name='报价')),
            ],
            options={
                'verbose_name': '报价明细',
                'db_table': 't_quote_item',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContractPaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=200, verbose_name='里程碑')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='比例(%)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='金额')),
                ('payment_days', models.IntegerField(default=30, help_text='到票后N天内付款', verbose_name='账期(天)')),
                ('trigger_condition', models.TextField(blank=True, default='', verbose_name='触发条件')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='finance.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '合同付款条款',
                'db_table': 't_contract_payment_term',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContractChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='变更编号')),
                ('change_type', models.CharField(choices=[('amount_change', '金额变更'), ('scope_change', '范围变更'), ('term_change', '条款变更'), ('other', '其他变更')], max_length=20, verbose_name='变更类型')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='原金额')),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='新金额')),
                ('reason', models.TextField(verbose_name='变更原因')),
                ('description', models.TextField(blank=True, default='', verbose_name='变更描述')),
                ('approval_status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='审批状态')),
                ('feishu_approval_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书审批ID')),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='finance.contract', verbose_name='合同')),
            ],
            options={
                'verbose_name': '合同变更',
                'db_table': 't_contract_change',
                'ordering': ['-create_time'],
            },
        ),
    ]
