# Generated by Django 4.2.27 on 2026-02-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_phase2_payable_expense_budget_adjustment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expenserequest',
            new_name='t_expense_r_applica_604a92_idx',
            old_name='expense_appl_status_idx',
        ),
        migrations.RenameIndex(
            model_name='expenserequest',
            new_name='t_expense_r_protoco_0fb936_idx',
            old_name='expense_prot_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payablerecord',
            new_name='t_payable_r_protoco_2a1395_idx',
            old_name='payable_prot_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payablerecord',
            new_name='t_payable_r_due_dat_615c0f_idx',
            old_name='payable_due_status_idx',
        ),
    ]
