# Generated by Django 4.2.27 on 2026-02-18 12:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_expense_appl_status_idx_t_expense_r_applica_604a92_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='决算编号')),
                ('protocol_id', models.IntegerField(db_index=True, verbose_name='协议ID')),
                ('project_name', models.CharField(blank=True, default='', max_length=200, verbose_name='项目名称')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='合同总额')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='累计开票')),
                ('total_received', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='累计回款')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='累计成本')),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='累计费用')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='毛利')),
                ('gross_margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='毛利率(%)')),
                ('budget_variance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='预算偏差')),
                ('settlement_status', models.CharField(choices=[('draft', '草稿'), ('reviewing', '审核中'), ('approved', '已批准'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('settlement_report', models.JSONField(blank=True, default=dict, verbose_name='详细决算数据')),
                ('feishu_doc_token', models.CharField(blank=True, default='', max_length=200, verbose_name='飞书文档token')),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目决算',
                'db_table': 't_project_settlement',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['protocol_id'], name='t_project_s_protoco_7e4c6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(db_index=True, verbose_name='客户ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, verbose_name='客户名称')),
                ('score_date', models.DateField(verbose_name='评分日期')),
                ('score', models.IntegerField(default=0, verbose_name='信用评分')),
                ('grade', models.CharField(default='C', max_length=2, verbose_name='信用等级')),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='准时回款率(%)')),
                ('avg_overdue_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6, verbose_name='平均逾期天数')),
                ('overdue_count', models.IntegerField(default=0, verbose_name='逾期次数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='历史合同总额')),
                ('score_detail', models.JSONField(blank=True, default=dict, verbose_name='评分明细')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户信用评分',
                'db_table': 't_credit_score',
                'ordering': ['-score_date'],
                'unique_together': {('client_id', 'score_date')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('metric_type', models.CharField(max_length=50, verbose_name='指标类型')),
                ('dimension_type', models.CharField(default='company', max_length=30, verbose_name='维度类型')),
                ('dimension_id', models.IntegerField(default=0, verbose_name='维度ID')),
                ('value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='指标值')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='上期值')),
                ('yoy_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='去年同期值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分析快照',
                'db_table': 't_analysis_snapshot',
                'indexes': [models.Index(fields=['snapshot_date', 'metric_type'], name='t_analysis__snapsho_9a38fb_idx')],
                'unique_together': {('snapshot_date', 'metric_type', 'dimension_type', 'dimension_id')},
            },
        ),
    ]
