# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_add_client_and_invoice_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='t_finance_c_custome_7376a0_idx',
            old_name='t_fin_client_code_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='t_finance_c_is_acti_52f9d4_idx',
            old_name='t_fin_client_active_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicerequest',
            new_name='t_invoice_r_status_266d7f_idx',
            old_name='t_invoice_r_status_2d4a5b_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicerequest',
            new_name='t_invoice_r_request_e257cf_idx',
            old_name='t_invoice_r_request_1e8c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicerequest',
            new_name='t_invoice_r_request_cbdb0a_idx',
            old_name='t_invoice_r_request_3f0a2e_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='创建人ID'),
        ),
    ]
