# Generated by Django 4.2.27 on 2026-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_rename_t_fin_client_code_idx_t_finance_c_custome_7376a0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='ekuaibao_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='易快报 flowId，唯一标识来源单据', max_length=200, verbose_name='易快报内部ID'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='ekuaibao_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='如 B26000474，展示用', max_length=100, verbose_name='易快报单号'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='import_batch_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='对应 EkbImportBatch.batch_no，用于按批次回滚', max_length=50, verbose_name='导入批次号'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='import_source',
            field=models.CharField(default='manual', help_text='manual（手动录入）| ekuaibao（易快报导入）', max_length=20, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='ekuaibao_budget_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='易快报预算ID'),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='import_batch_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='导入批次号'),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='import_source',
            field=models.CharField(default='manual', max_length=20, verbose_name='数据来源'),
        ),
    ]
