# Generated by Django 4.2.27 on 2026-03-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_add_ekuaibao_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='approval_chain',
            field=models.JSONField(blank=True, default=list, help_text='从易快报 logs 提取的审批链，格式：[{action, node_name, operator_name, time}]', verbose_name='审批轨迹'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='client_name',
            field=models.CharField(blank=True, default='', help_text='u_客户名称，如欧莱雅、联合利华；冗余字段便于直接展示', max_length=200, verbose_name='客户名称'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='cost_department',
            field=models.CharField(blank=True, default='', help_text='expenseDepartment.name，区别于申请人所属部门', max_length=100, verbose_name='费用承担部门'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='ekuaibao_submitter_id',
            field=models.CharField(blank=True, default='', help_text='submitterId.id，用于关联到 Account.ekuaibao_staff_id', max_length=200, verbose_name='易快报提交人ID'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='expense_template',
            field=models.CharField(blank=True, default='', help_text='specificationId.name，如"功效测试项目报销单"/"日常管理报销单"', max_length=100, verbose_name='单据模板'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='linked_budget_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='对应 ProjectBudget.budget_no，如 S26000040；通过 expenseLink 关联', max_length=100, verbose_name='关联预算申请单号'),
        ),
    ]
