# Generated by Django 4.2.29 on 2026-03-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_legacyinvoice'),
        ('finance', '0012_invoice_request_invoice_type'),
    ]

    operations = [
    ]
