# Generated by Django 4.2.29 on 2026-03-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_add_expense_business_fields'),
        ('finance', '0015_alter_invoicerequest_tax_rate_default'),
    ]

    operations = [
    ]
