# Generated by Django 4.2.27 on 2026-03-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_merge_20260320_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyInvoice',
        ),
    ]
