# Generated by Django 4.2.28 on 2026-03-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_merge_20260320_1824"),
    ]

    operations = [
        # 索引名：部分环境由 Django 4.2 自动生成（已是 new_name），库中不存在 old_name。
        # 仅同步 migration state，避免 ALTER INDEX 因「旧名不存在」失败。
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="legacyinvoice",
                    new_name="t_legacy_in_status_afd4b8_idx",
                    old_name="t_legacy_in_status_idx",
                ),
                migrations.RenameIndex(
                    model_name="legacyinvoice",
                    new_name="t_legacy_in_custome_1bae29_idx",
                    old_name="t_legacy_in_customer_idx",
                ),
                migrations.RenameIndex(
                    model_name="legacyinvoice",
                    new_name="t_legacy_in_project_bb639b_idx",
                    old_name="t_legacy_in_project_idx",
                ),
                migrations.RenameIndex(
                    model_name="legacyinvoice",
                    new_name="t_legacy_in_invoice_33fa87_idx",
                    old_name="t_legacy_in_invoice_d_idx",
                ),
            ],
            database_operations=[],
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="approval_chain",
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="client_name",
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="cost_department",
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="ekuaibao_id",
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="ekuaibao_no",
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="ekuaibao_submitter_id",
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="expense_template",
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="import_batch_id",
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="import_source",
        ),
        migrations.RemoveField(
            model_name="expenserequest",
            name="linked_budget_no",
        ),
        migrations.RemoveField(
            model_name="projectbudget",
            name="ekuaibao_budget_id",
        ),
        migrations.RemoveField(
            model_name="projectbudget",
            name="import_batch_id",
        ),
        migrations.RemoveField(
            model_name="projectbudget",
            name="import_source",
        ),
        migrations.AlterField(
            model_name="invoicerequest",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("full_elec_special", "全电专票"),
                    ("full_elec_normal", "全电普票"),
                    ("proforma", "形式发票"),
                ],
                default="full_elec_special",
                max_length=24,
                verbose_name="发票类型",
            ),
        ),
    ]
