# Generated by Django 4.2.27 on 2026-03-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_merge_20260320_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyInvoice',
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='account_period',
            field=models.CharField(blank=True, default='', help_text='如 2024-03，用于财务报表归期', max_length=20, verbose_name='会计期间'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='excel_raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='从NAS Excel导入时保存的完整125列原始行数据，防止字段丢失', verbose_name='原始Excel行数据'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='invoice_count',
            field=models.IntegerField(default=0, help_text='报销附件中的发票数量', verbose_name='发票张数'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='软删除标志，易快报来源数据禁止物理删除', verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payee_account',
            field=models.CharField(blank=True, db_index=True, default='', help_text='银行账号，审计追溯核心字段', max_length=100, verbose_name='收款账号'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payee_account_type',
            field=models.CharField(blank=True, default='', help_text='个人 / 对公', max_length=20, verbose_name='账户类型'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payee_bank',
            field=models.CharField(blank=True, default='', help_text='如：中国工商银行、建设银行等', max_length=100, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payee_bank_branch',
            field=models.CharField(blank=True, default='', help_text='支行全称，如：中国工商银行股份有限公司上海长宁支行', max_length=200, verbose_name='开户网点'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payee_city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='开户行所在市'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payee_name',
            field=models.CharField(blank=True, default='', help_text='收款方名称（个人姓名或公司全称）', max_length=200, verbose_name='收款户名'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payee_province',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='开户行所在省'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='实际出账金额（可能 ≠ 报销金额，如部分付款）', max_digits=15, null=True, verbose_name='支付金额'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payment_date',
            field=models.DateField(blank=True, help_text='资金出账日期，对账核销关键字段', null=True, verbose_name='支付日期'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='线下支付 / 现金罗盘 / 银行转账等', max_length=50, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='submit_date',
            field=models.DateField(blank=True, db_index=True, help_text='单据原始提交日期（历史数据保留，不等于 create_time）', null=True, verbose_name='提交日期'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='voucher_no',
            field=models.CharField(blank=True, default='', help_text='财务记账凭证编号', max_length=100, verbose_name='凭证号'),
        ),
    ]
