# Generated by Django 4.2.29 on 2026-03-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_merge_20260320_1824'),
        ('finance', '0017_rename_t_legacy_in_status_idx_t_legacy_in_status_afd4b8_idx_and_more'),
    ]

    operations = [
    ]
