# Generated by Django 4.2.29 on 2026-03-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_invoice_request_invoice_type_choices'),
        ('finance', '0017_merge_20260317_1408'),
    ]

    operations = [
    ]
