# Generated by Django 4.2.29 on 2026-03-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_delete_legacyinvoice'),
        ('finance', '0017_rename_t_legacy_in_status_idx_t_legacy_in_status_afd4b8_idx_and_more'),
    ]

    operations = [
    ]
