# Generated by Django 4.2.27 on 2026-02-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocol', '0005_protocol_feishu_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='产品编码')),
                ('batch_number', models.CharField(blank=True, default='', max_length=100, verbose_name='批号')),
                ('specification', models.CharField(blank=True, default='', max_length=100, verbose_name='规格')),
                ('storage_condition', models.CharField(blank=True, default='', max_length=200, verbose_name='存储条件')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '测试产品',
                'db_table': 't_product',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SampleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='唯一编码')),
                ('current_holder_id', models.IntegerField(blank=True, help_text='Enrollment ID', null=True, verbose_name='当前持有人ID')),
                ('status', models.CharField(choices=[('in_stock', '在库'), ('distributed', '已分发'), ('consumed', '已消耗'), ('returned', '已回收'), ('destroyed', '已销毁')], db_index=True, default='in_stock', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='sample.product', verbose_name='所属产品')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='protocol.protocol', verbose_name='关联协议')),
            ],
            options={
                'verbose_name': '样品实例',
                'db_table': 't_sample_instance',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SampleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('inbound', '入库'), ('distribute', '分发'), ('return', '回收'), ('destroy', '销毁')], max_length=20, verbose_name='操作类型')),
                ('enrollment_id', models.IntegerField(blank=True, null=True, verbose_name='关联入组ID')),
                ('work_order_id', models.IntegerField(blank=True, help_text='工单执行时关联样品（AC-3）', null=True, verbose_name='关联工单ID')),
                ('operator_name', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人')),
                ('operator_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sample.sampleinstance', verbose_name='样品')),
            ],
            options={
                'verbose_name': '样品流转',
                'db_table': 't_sample_transaction',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='t_product_code_f4ca25_idx'),
        ),
        migrations.AddIndex(
            model_name='sampletransaction',
            index=models.Index(fields=['sample', 'transaction_type'], name='t_sample_tr_sample__c3637a_idx'),
        ),
        migrations.AddIndex(
            model_name='sampleinstance',
            index=models.Index(fields=['unique_code'], name='t_sample_in_unique__9d150b_idx'),
        ),
        migrations.AddIndex(
            model_name='sampleinstance',
            index=models.Index(fields=['status'], name='t_sample_in_status_f77344_idx'),
        ),
        migrations.AddIndex(
            model_name='sampleinstance',
            index=models.Index(fields=['protocol'], name='t_sample_in_protoco_cc3fdd_idx'),
        ),
    ]
