# Generated by Django 4.2.27 on 2026-03-05 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0014_relax_workorder_dual_track_checks'),
        ('sample', '0003_inventorycount_productbatch_productdestruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletransaction',
            name='work_order_id',
        ),
        migrations.AddField(
            model_name='productdispensing',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_dispensings', to='workorder.workorder', verbose_name='关联工单'),
        ),
        migrations.AddField(
            model_name='sampletransaction',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='工单执行时关联样品（AC-3）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_transactions', to='workorder.workorder', verbose_name='关联工单'),
        ),
        migrations.AddIndex(
            model_name='productdispensing',
            index=models.Index(fields=['work_order', 'subject_id', 'visit_code'], name='t_product_d_work_or_497b72_idx'),
        ),
    ]
