# Generated by Django 4.2.27 on 2026-02-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签名称')),
                ('category', models.CharField(blank=True, default='', help_text='标签分类：product_category/claim_type/test_method/regulation', max_length=50, verbose_name='标签分类')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '知识标签',
                'db_table': 't_knowledge_tag',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('regulation', '法规'), ('sop', 'SOP'), ('proposal_template', '方案模板'), ('method_reference', '方法参考'), ('lesson_learned', '经验教训'), ('faq', '常见问题')], max_length=30, verbose_name='条目类型')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('tags', models.JSONField(default=list, verbose_name='标签列表')),
                ('source_type', models.CharField(blank=True, default='', help_text='来源类型：protocol/retrospective/sop/document/manual', max_length=50, verbose_name='来源类型')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='来源ID')),
                ('embedding_id', models.CharField(blank=True, default='', max_length=200, verbose_name='向量嵌入存储ID')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '知识条目',
                'db_table': 't_knowledge_entry',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['entry_type', 'is_published'], name='t_knowledge_entry_t_c46637_idx'), models.Index(fields=['source_type', 'source_id'], name='t_knowledge_source__028789_idx'), models.Index(fields=['is_deleted', 'is_published'], name='t_knowledge_is_dele_d04f93_idx')],
            },
        ),
    ]
