# Generated by Django 4.2.27 on 2026-03-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_k1_ontology_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('concept', '概念'), ('instance', '实例'), ('property', '属性'), ('class', '类'), ('instrument', '仪器/设备'), ('method', '检测方法'), ('ingredient', '化妆品成分'), ('competitor', '竞品公司'), ('regulation_entity', '法规实体'), ('measurement', '检测指标'), ('paper', '学术论文')], default='concept', max_length=20, verbose_name='实体类型')),
                ('uri', models.CharField(help_text='全局唯一标识，如 bridg:StudySubject 或 cnkis:visit-plan', max_length=500, verbose_name='语义 URI')),
                ('label', models.CharField(max_length=200, verbose_name='显示名称')),
                ('label_en', models.CharField(blank=True, default='', max_length=200, verbose_name='英文名称')),
                ('definition', models.TextField(blank=True, default='', verbose_name='定义')),
                ('namespace', models.CharField(choices=[('cnkis', 'CN_KIS 项目本体'), ('cdisc_sdtm', 'CDISC SDTM'), ('cdisc_cdash', 'CDISC CDASH'), ('cdisc_odm', 'CDISC ODM'), ('bridg', 'BRIDG (ISO 14199)'), ('nmpa_regulation', 'NMPA 法规公告'), ('internal_sop', '内部 SOP'), ('project_experience', '项目经验'), ('custom', '自定义')], default='cnkis', max_length=30, verbose_name='命名空间')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='存储本体属性的键值对，如 {domain, range, cardinality}', verbose_name='扩展属性')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '知识实体',
                'db_table': 't_knowledge_entity',
                'ordering': ['namespace', 'label'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('is_a', '是一种 (is-a)'), ('part_of', '属于 (part-of)'), ('has_property', '具有属性'), ('related_to', '相关'), ('depends_on', '依赖'), ('produces', '产出'), ('governed_by', '受管辖'), ('precedes', '先于'), ('follows', '后于'), ('translates_to', '翻译为'), ('measured_by', '测量方式'), ('implemented_by', '实现方式'), ('custom', '自定义'), ('has_measurement', '具有检测指标'), ('tested_by', '通过方法检测'), ('limited_by', '受法规限制'), ('used_in', '用于项目/检测'), ('improves', '改进了'), ('competes_with', '与…竞争'), ('published_by', '由…发表'), ('requires', '需要'), ('resolved_by', '通过…解决'), ('has_deviation', '存在偏差')], default='related_to', max_length=30, verbose_name='关系类型')),
                ('predicate_uri', models.CharField(blank=True, default='', help_text='语义谓词 URI，如 bridg:performedOn 或 cnkis:requires', max_length=500, verbose_name='谓词 URI')),
                ('confidence', models.FloatField(default=1.0, help_text='1.0=人工确认, <1.0=LLM 自动抽取的置信度', verbose_name='置信度')),
                ('source', models.CharField(blank=True, default='', help_text='manual/llm-ark/llm-kimi/cdisc-import/bridg-import', max_length=100, verbose_name='来源')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外信息，如抽取时的上下文、原文引用等', verbose_name='元数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '知识关系',
                'db_table': 't_knowledge_relation',
                'ordering': ['-create_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='knowledgeentry',
            new_name='t_knowledge_source__abc74c_idx',
            old_name='t_knowledge_source__9d765f_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeentry',
            new_name='t_knowledge_namespa_e03a5c_idx',
            old_name='t_knowledge_namespace_idx',
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='index_status',
            field=models.CharField(choices=[('pending', '待索引'), ('indexed', '已索引'), ('failed', '索引失败')], db_index=True, default='pending', help_text='向量索引状态', max_length=20, verbose_name='索引状态'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='索引时间'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='quality_score',
            field=models.IntegerField(blank=True, help_text='0-100 综合质量评分，< 40 不自动发布', null=True, verbose_name='质量评分'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='rag_cite_count',
            field=models.IntegerField(default=0, verbose_name='RAG 引用次数'),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('processed', '已处理'), ('pending_review', '待审核'), ('published', '已发布'), ('archived', '已归档'), ('rejected', '已拒绝')], db_index=True, default='draft', help_text='draft/processed/pending_review/published/archived/rejected', max_length=20, verbose_name='知识状态'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='entry_type',
            field=models.CharField(choices=[('regulation', '法规'), ('sop', 'SOP'), ('proposal_template', '方案模板'), ('method_reference', '方法参考'), ('lesson_learned', '经验教训'), ('faq', '常见问题'), ('feishu_doc', '飞书文档'), ('competitor_intel', '竞品情报'), ('instrument_spec', '仪器规格'), ('ingredient_data', '成分数据'), ('meeting_decision', '会议决策'), ('market_insight', '市场洞察'), ('paper_abstract', '论文摘要')], max_length=30, verbose_name='条目类型'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='namespace',
            field=models.CharField(choices=[('cnkis', 'CN_KIS 项目本体'), ('cdisc_sdtm', 'CDISC SDTM'), ('cdisc_cdash', 'CDISC CDASH'), ('cdisc_odm', 'CDISC ODM'), ('bridg', 'BRIDG (ISO 14199)'), ('nmpa_regulation', 'NMPA 法规公告'), ('internal_sop', '内部 SOP'), ('project_experience', '项目经验'), ('custom', '自定义')], default='cnkis', help_text='标识知识条目所属的本体标准', max_length=30, verbose_name='本体命名空间'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='source_type',
            field=models.CharField(blank=True, default='', help_text='来源类型：protocol/retrospective/sop/document/manual/agent_tool/feishu_chat/feishu_meeting', max_length=50, verbose_name='来源类型'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['status'], name='t_knowledge_status_02e74c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['index_status'], name='t_knowledge_index_s_45f1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['quality_score'], name='t_knowledge_quality_1f169c_idx'),
        ),
        migrations.AddField(
            model_name='knowledgerelation',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='knowledge.knowledgeentity', verbose_name='宾语实体'),
        ),
        migrations.AddField(
            model_name='knowledgerelation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='knowledge.knowledgeentity', verbose_name='主语实体'),
        ),
        migrations.AddField(
            model_name='knowledgeentity',
            name='linked_entry',
            field=models.ForeignKey(blank=True, help_text='实体与现有知识条目的双向关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='knowledge.knowledgeentry', verbose_name='关联知识条目'),
        ),
        migrations.AddField(
            model_name='knowledgeentity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='knowledge.knowledgeentity', verbose_name='上位概念'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['subject', 'relation_type'], name='t_knowledge_subject_953655_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['object', 'relation_type'], name='t_knowledge_object__59eb59_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['relation_type'], name='t_knowledge_relatio_230cc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerelation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('subject', 'predicate_uri', 'object'), name='uniq_relation_triple'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentity',
            index=models.Index(fields=['entity_type', 'namespace'], name='t_knowledge_entity__6d5ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentity',
            index=models.Index(fields=['namespace', 'uri'], name='t_knowledge_namespa_4f2e02_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('namespace', 'uri'), name='uniq_entity_namespace_uri'),
        ),
    ]
