# Generated by Django 4.2.27 on 2026-03-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_knowledge_status_and_enum_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeentity',
            name='label',
            field=models.CharField(max_length=500, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='knowledgeentity',
            name='label_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='英文名称'),
        ),
    ]
