# Generated by Django 4.2.27 on 2026-03-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_resize_embedding_vector_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='facet',
            field=models.CharField(blank=True, db_index=True, default='', help_text='条目在专题包中的维度，如 regulation_boundary/key_metrics/sop_risks', max_length=50, verbose_name='专题 Facet'),
        ),
        migrations.CreateModel(
            name='TopicPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_topic', models.CharField(help_text='专题包的标准化主题名，如 "保湿仪器与检测方法" 或 "中国化妆品法规合规"', max_length=200, verbose_name='标准化主题')),
                ('package_id', models.CharField(help_text='全局唯一 ID，如 pkg_moisturizing_instruments，用于跨系统引用', max_length=100, unique=True, verbose_name='专题包 ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='专题描述')),
                ('facets', models.JSONField(default=dict, help_text='各 facet 的覆盖状态和关联 entry 数量，格式: {facet: {count: int, entry_ids: []}}', verbose_name='Facet 覆盖状态')),
                ('coverage_weight', models.FloatField(default=1.0, help_text='该专题包在整体评测中的权重（关键专题权重更高）', verbose_name='覆盖权重')),
                ('required_for_release', models.BooleanField(default=False, help_text='True 表示该专题包的门禁是上线的硬性要求', verbose_name='上线必须通过')),
                ('source_authority_level', models.CharField(choices=[('tier1', 'Tier 1 — 国家标准/法规/ICH'), ('tier2', 'Tier 2 — 行业标准/协会指南'), ('tier3', 'Tier 3 — 学术文献/内部SOP'), ('mixed', 'Mixed — 多来源混合')], default='mixed', max_length=20, verbose_name='权威来源级别')),
                ('status', models.CharField(choices=[('building', '建设中'), ('review', '评审中'), ('published', '已发布'), ('archived', '已归档')], default='building', max_length=20, verbose_name='专题包状态')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='如 {"cluster_keywords": [], "related_packages": [], "n8n_workflow_id": ""}', verbose_name='扩展属性')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '专题包',
                'db_table': 't_knowledge_topic_package',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['canonical_topic'], name='t_knowledge_canonic_3cac5c_idx'), models.Index(fields=['status', 'required_for_release'], name='t_knowledge_status_ce9ad5_idx'), models.Index(fields=['coverage_weight'], name='t_knowledge_coverag_a11f35_idx')],
            },
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='topic_package',
            field=models.ForeignKey(blank=True, help_text='该条目所属的知识专题包，用于专题覆盖度评估', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='knowledge.topicpackage', verbose_name='所属专题包'),
        ),
    ]
