# Generated by Django 4.2.27 on 2026-03-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_domain_policy_and_entry_ownership'),
        ('knowledge', '0013_knowledge_quality_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeentity',
            name='entity_type',
            field=models.CharField(choices=[('concept', '概念'), ('instance', '实例'), ('property', '属性'), ('class', '类'), ('instrument', '仪器/设备'), ('method', '检测方法'), ('ingredient', '化妆品成分'), ('competitor', '竞品公司'), ('regulation_entity', '法规实体'), ('measurement', '检测指标'), ('paper', '学术论文'), ('person', '人员'), ('project', '项目'), ('facility', '场地/实验室'), ('client', '客户/申办方'), ('role', '岗位角色'), ('timepoint', '检测时间点'), ('sample', '样品/耗材')], default='concept', max_length=20, verbose_name='实体类型'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='entry_type',
            field=models.CharField(choices=[('regulation', '法规'), ('sop', 'SOP'), ('proposal_template', '方案模板'), ('method_reference', '方法参考'), ('lesson_learned', '经验教训'), ('faq', '常见问题'), ('feishu_doc', '飞书文档'), ('competitor_intel', '竞品情报'), ('instrument_spec', '仪器规格'), ('ingredient_data', '成分数据'), ('meeting_decision', '会议决策'), ('market_insight', '市场洞察'), ('paper_abstract', '论文摘要'), ('feishu_mail', '飞书邮件'), ('feishu_im', '飞书消息'), ('feishu_calendar', '飞书日历'), ('feishu_task', '飞书任务'), ('feishu_approval', '飞书审批'), ('feishu_wiki', '飞书知识库'), ('feishu_sheet', '飞书电子表格'), ('feishu_slide', '飞书幻灯片'), ('feishu_file', '飞书文件')], max_length=30, verbose_name='条目类型'),
        ),
        migrations.AlterField(
            model_name='knowledgerelation',
            name='relation_type',
            field=models.CharField(choices=[('is_a', '是一种 (is-a)'), ('part_of', '属于 (part-of)'), ('has_property', '具有属性'), ('related_to', '相关'), ('depends_on', '依赖'), ('produces', '产出'), ('governed_by', '受管辖'), ('precedes', '先于'), ('follows', '后于'), ('translates_to', '翻译为'), ('measured_by', '测量方式'), ('implemented_by', '实现方式'), ('custom', '自定义'), ('has_measurement', '具有检测指标'), ('tested_by', '通过方法检测'), ('limited_by', '受法规限制'), ('used_in', '用于项目/检测'), ('improves', '改进了'), ('competes_with', '与…竞争'), ('published_by', '由…发表'), ('requires', '需要'), ('resolved_by', '通过…解决'), ('has_deviation', '存在偏差'), ('manages', '管理/负责'), ('assigned_to', '分配给'), ('reports_to', '汇报给'), ('schedules', '排程'), ('operates', '操作/使用'), ('sponsors', '委托/发起'), ('reviews', '审核/复核'), ('executes', '执行'), ('requests', '提交申请'), ('approves', '审批'), ('locates_in', '位于/所在'), ('certified_for', '持有资质'), ('collaborates_with', '协同')], default='related_to', max_length=30, verbose_name='关系类型'),
        ),
    ]
