# Generated by Django 4.2.29 on 2026-03-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0014_feishu_entry_types'),
        ('knowledge', '0015_resize_embedding_vector_1024'),
    ]

    operations = [
    ]
