# Generated by Django 4.2.27 on 2026-02-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, help_text='Django模型表名，如：t_subject, t_protocol', max_length=100, verbose_name='表名')),
                ('bitable_app_token', models.CharField(max_length=100, verbose_name='飞书多维表格App Token')),
                ('bitable_table_id', models.CharField(max_length=100, verbose_name='飞书多维表格Table ID')),
                ('direction', models.CharField(choices=[('to_feishu', '数据库 -> 飞书'), ('from_feishu', '飞书 -> 数据库'), ('bidirectional', '双向同步')], default='bidirectional', max_length=20, verbose_name='同步方向')),
                ('field_mapping', models.JSONField(default=dict, help_text='数据库字段到飞书字段的映射关系', verbose_name='字段映射')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sync_interval_minutes', models.IntegerField(default=60, help_text='自动同步间隔，0表示不自动同步', verbose_name='同步间隔（分钟）')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
            ],
            options={
                'verbose_name': '同步配置',
                'db_table': 't_sync_config',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('records_synced', models.IntegerField(default=0, verbose_name='同步记录数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='feishu_sync.syncconfig')),
            ],
            options={
                'verbose_name': '同步日志',
                'db_table': 't_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncconfig',
            index=models.Index(fields=['table_name'], name='t_sync_conf_table_n_006f69_idx'),
        ),
        migrations.AddIndex(
            model_name='syncconfig',
            index=models.Index(fields=['enabled'], name='t_sync_conf_enabled_fdf11c_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['config', 'status'], name='t_sync_log_config__2472af_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['started_at'], name='t_sync_log_started_88f5ba_idx'),
        ),
    ]
