# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feishu_sync', '0002_idempotent_sync_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='synclog',
            new_name='t_sync_log_idempot_0e38aa_idx',
            old_name='t_sync_log_idempot_6ee4e2_idx',
        ),
    ]
