# Generated by Django 4.2.27 on 2026-02-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='流程名称')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='流程编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('business_type', models.CharField(help_text='如 deviation/ae/document/ethics', max_length=50, verbose_name='业务类型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('steps', models.JSONField(default=list, help_text='[{"step": 1, "name": "xx", "type": "sequential", "approvers": [{"role": "xx"}, {"user_id": 1}]}]', verbose_name='审批步骤')),
                ('feishu_approval_code', models.CharField(blank=True, default='', help_text='可选，关联飞书原生审批', max_length=100, verbose_name='飞书审批定义Code')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '流程定义',
                'db_table': 't_workflow_definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=50, verbose_name='业务类型')),
                ('business_id', models.IntegerField(verbose_name='业务ID')),
                ('title', models.CharField(max_length=500, verbose_name='审批标题')),
                ('status', models.CharField(choices=[('pending', '审批中'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已撤销')], default='pending', max_length=20, verbose_name='状态')),
                ('current_step', models.IntegerField(default=1, verbose_name='当前步骤')),
                ('initiator_id', models.IntegerField(help_text='Account ID', verbose_name='发起人ID')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='表单数据')),
                ('feishu_approval_instance_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书审批实例ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition', verbose_name='流程定义')),
            ],
            options={
                'verbose_name': '流程实例',
                'db_table': 't_workflow_instance',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(verbose_name='审批步骤')),
                ('approver_id', models.IntegerField(help_text='Account ID', verbose_name='审批人ID')),
                ('action', models.CharField(help_text='approve/reject/forward', max_length=20, verbose_name='操作')),
                ('comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='workflow.workflowinstance', verbose_name='流程实例')),
            ],
            options={
                'verbose_name': '审批记录',
                'db_table': 't_workflow_approval_record',
                'ordering': ['step', 'create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['definition', 'status'], name='t_workflow__definit_a1fe52_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['business_type', 'business_id'], name='t_workflow__busines_abdf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['initiator_id'], name='t_workflow__initiat_79d380_idx'),
        ),
    ]
