# Generated by Django 4.2.27 on 2026-02-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('channel', models.CharField(choices=[('feishu_message', '飞书消息'), ('feishu_card', '飞书卡片'), ('feishu_group', '飞书群'), ('feishu_urgent', '飞书加急'), ('system', '系统内通知')], max_length=20, verbose_name='渠道')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('recipient_id', models.IntegerField(db_index=True, help_text='Account ID', verbose_name='接收人ID')),
                ('recipient_open_id', models.CharField(blank=True, default='', max_length=100, verbose_name='接收人Open ID')),
                ('source_type', models.CharField(blank=True, default='', help_text='如 workorder/ae/deviation', max_length=50, verbose_name='来源类型')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='来源ID')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('delivered', '已送达'), ('read', '已读'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('feishu_message_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书消息ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知记录',
                'db_table': 't_notification_record',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['recipient_id', 'status'], name='t_notificat_recipie_a7207a_idx'), models.Index(fields=['channel', 'status'], name='t_notificat_channel_519003_idx'), models.Index(fields=['create_time'], name='t_notificat_create__f99b0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('notification_type', models.CharField(help_text='如 workorder_assigned/ae_reported', max_length=50, verbose_name='通知类型')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('preferred_channel', models.CharField(choices=[('feishu_message', '飞书消息'), ('feishu_card', '飞书卡片'), ('feishu_group', '飞书群'), ('feishu_urgent', '飞书加急'), ('system', '系统内通知')], default='feishu_card', max_length=20, verbose_name='首选渠道')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知偏好',
                'db_table': 't_notification_preference',
                'unique_together': {('user_id', 'notification_type')},
            },
        ),
    ]
