# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_add_source_workstation_target_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='preferred_channel',
            field=models.CharField(choices=[('feishu_message', '飞书消息'), ('feishu_card', '飞书卡片'), ('feishu_group', '飞书群'), ('feishu_urgent', '飞书加急'), ('wechat_subscribe', '微信订阅消息'), ('sms', '短信'), ('system', '系统内通知')], default='feishu_card', max_length=20, verbose_name='首选渠道'),
        ),
        migrations.AlterField(
            model_name='notificationrecord',
            name='channel',
            field=models.CharField(choices=[('feishu_message', '飞书消息'), ('feishu_card', '飞书卡片'), ('feishu_group', '飞书群'), ('feishu_urgent', '飞书加急'), ('wechat_subscribe', '微信订阅消息'), ('sms', '短信'), ('system', '系统内通知')], max_length=20, verbose_name='渠道'),
        ),
    ]
