# Generated by Django 4.2.27 on 2026-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notificationpreference_preferred_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(help_text='owner/repo 格式', max_length=200, verbose_name='仓库')),
                ('pr_number', models.IntegerField(verbose_name='PR 编号')),
                ('commit_sha', models.CharField(max_length=40, verbose_name='Commit SHA')),
                ('approver_open_id', models.CharField(max_length=100, verbose_name='审批人 Feishu open_id')),
                ('approver_name', models.CharField(blank=True, default='', max_length=100, verbose_name='审批人姓名')),
                ('action', models.CharField(choices=[('approve', '批准'), ('reject', '拒绝')], max_length=20, verbose_name='审批动作')),
                ('github_status_set', models.BooleanField(default=False, verbose_name='已更新 GitHub 状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'PR 飞书审批记录',
                'db_table': 't_pr_approval_record',
                'indexes': [models.Index(fields=['repo', 'pr_number', 'action'], name='t_pr_approv_repo_907fdb_idx')],
                'unique_together': {('repo', 'pr_number', 'approver_open_id')},
            },
        ),
    ]
