# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocol', '0004_alter_protocol_feishu_project_work_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicsCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='委员会名称')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='委员会编码')),
                ('contact_person', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '伦理委员会',
                'db_table': 't_ethics_committee',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EthicsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='申请编号')),
                ('version', models.CharField(default='v1.0', max_length=50, verbose_name='申请版本')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='提交日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewing', '审核中'), ('approved', '已批准'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('feishu_approval_instance_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='飞书审批实例ID')),
                ('created_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='ethics.ethicscommittee', verbose_name='受理委员会')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethics_applications', to='protocol.protocol', verbose_name='关联协议')),
            ],
            options={
                'verbose_name': '伦理申请',
                'db_table': 't_ethics_application',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100, verbose_name='批件号')),
                ('approved_date', models.DateField(verbose_name='批准日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('file_url', models.URLField(blank=True, default='', max_length=500, verbose_name='批件文件URL')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_document', to='ethics.ethicsapplication', verbose_name='关联申请')),
            ],
            options={
                'verbose_name': '伦理批件',
                'db_table': 't_ethics_approval_document',
                'ordering': ['-approved_date'],
            },
        ),
        migrations.AddIndex(
            model_name='ethicsapplication',
            index=models.Index(fields=['protocol', 'status'], name='t_ethics_ap_protoco_b80b47_idx'),
        ),
        migrations.AddIndex(
            model_name='ethicsapplication',
            index=models.Index(fields=['status'], name='t_ethics_ap_status_327fac_idx'),
        ),
        migrations.AddIndex(
            model_name='ethicsapplication',
            index=models.Index(fields=['application_number'], name='t_ethics_ap_applica_ec13e1_idx'),
        ),
    ]
