# Generated by Django 4.2.27 on 2026-02-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethics', '0002_ethics_extended_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='compliancecheck',
            new_name='t_ethics_co_check_t_bed77c_idx',
            old_name='t_ethics_cc_type_st_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancecheck',
            new_name='t_ethics_co_check_n_7868e9_idx',
            old_name='t_ethics_cc_checkno_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancefinding',
            new_name='t_ethics_co_check_i_f855a4_idx',
            old_name='t_ethics_cf_chk_sev_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancefinding',
            new_name='t_ethics_co_status_59a0a2_idx',
            old_name='t_ethics_cf_status_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancefinding',
            new_name='t_ethics_co_finding_97657f_idx',
            old_name='t_ethics_cf_findno_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancetraining',
            new_name='t_ethics_co_trainin_da5df4_idx',
            old_name='t_ethics_ct_type_st_idx',
        ),
        migrations.RenameIndex(
            model_name='compliancetraining',
            new_name='t_ethics_co_trainin_a3ac9b_idx',
            old_name='t_ethics_ct_trainno_idx',
        ),
        migrations.RenameIndex(
            model_name='ethicsreviewopinion',
            new_name='t_ethics_re_applica_9576e5_idx',
            old_name='t_ethics_re_applica_idx',
        ),
        migrations.RenameIndex(
            model_name='ethicsreviewopinion',
            new_name='t_ethics_re_opinion_45e4cb_idx',
            old_name='t_ethics_re_opinion_idx',
        ),
        migrations.RenameIndex(
            model_name='ethicssupervision',
            new_name='t_ethics_su_protoco_ca8e57_idx',
            old_name='t_ethics_su_protoco_idx',
        ),
        migrations.RenameIndex(
            model_name='ethicssupervision',
            new_name='t_ethics_su_supervi_c00123_idx',
            old_name='t_ethics_su_supervi_idx',
        ),
        migrations.RenameIndex(
            model_name='regulation',
            new_name='t_ethics_re_regulat_c7f129_idx',
            old_name='t_ethics_rg_regtype_idx',
        ),
        migrations.RenameIndex(
            model_name='regulation',
            new_name='t_ethics_re_impact__a463a2_idx',
            old_name='t_ethics_rg_impact_idx',
        ),
        migrations.RenameIndex(
            model_name='regulatorycorrespondence',
            new_name='t_ethics_re_directi_e98ea0_idx',
            old_name='t_ethics_rc_dir_sts_idx',
        ),
        migrations.RenameIndex(
            model_name='regulatorycorrespondence',
            new_name='t_ethics_re_corresp_71a805_idx',
            old_name='t_ethics_rc_corrno_idx',
        ),
    ]
