# Generated by Django 4.2.27 on 2026-02-18 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocol', '0006_p2_recruitment_tables'),
        ('crm', '0003_alter_client_feishu_project_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCloseout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', '已发起'), ('checking', '检查中'), ('review', '评审中'), ('archived', '已归档')], default='initiated', max_length=20, verbose_name='状态')),
                ('initiated_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='发起人ID')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeouts', to='protocol.protocol', verbose_name='关联协议')),
            ],
            options={
                'verbose_name': '项目结项',
                'db_table': 't_project_closeout',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='CloseoutChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('document_completeness', '文件完整性'), ('data_completeness', '数据完整性'), ('quality_compliance', '质量合规'), ('financial_settlement', '财务结算')], max_length=30, verbose_name='分组')),
                ('item_code', models.CharField(max_length=50, verbose_name='检查项编号')),
                ('item_description', models.CharField(max_length=500, verbose_name='检查项描述')),
                ('is_auto_check', models.BooleanField(default=False, verbose_name='是否自动检查')),
                ('auto_check_passed', models.BooleanField(blank=True, null=True, verbose_name='自动检查通过')),
                ('is_manually_confirmed', models.BooleanField(default=False, verbose_name='是否手动确认')),
                ('confirmed_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='确认人ID')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('closeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='closeout.projectcloseout', verbose_name='关联结项')),
            ],
            options={
                'verbose_name': '结项检查项',
                'db_table': 't_closeout_checklist',
                'ordering': ['group', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='ClientAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverables', models.JSONField(default=list, help_text='交付物清单 [{name, status, notes}]', verbose_name='交付物清单')),
                ('acceptance_status', models.CharField(choices=[('pending', '待验收'), ('partial', '部分验收'), ('accepted', '已验收'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='验收状态')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签收时间')),
                ('signed_by', models.CharField(blank=True, default='', max_length=200, verbose_name='签收人')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptances', to='crm.client', verbose_name='客户')),
                ('closeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='closeout.projectcloseout', verbose_name='关联结项')),
            ],
            options={
                'verbose_name': '客户验收',
                'db_table': 't_client_acceptance',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRetrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_went_well', models.JSONField(default=list, verbose_name='做得好的方面')),
                ('what_to_improve', models.JSONField(default=list, verbose_name='需要改进的方面')),
                ('action_items', models.JSONField(default=list, verbose_name='行动项')),
                ('lessons_learned', models.JSONField(default=list, verbose_name='经验教训')),
                ('created_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('closeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to='closeout.projectcloseout', verbose_name='关联结项')),
            ],
            options={
                'verbose_name': '项目复盘',
                'db_table': 't_project_retrospective',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['closeout'], name='t_project_r_closeou_0f3dd9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='projectcloseout',
            index=models.Index(fields=['status'], name='t_project_c_status_9e6ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcloseout',
            index=models.Index(fields=['protocol', 'status'], name='t_project_c_protoco_e3fc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='closeoutchecklist',
            index=models.Index(fields=['closeout', 'group'], name='t_closeout__closeou_8a93f7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientacceptance',
            index=models.Index(fields=['closeout'], name='t_client_ac_closeou_76f73a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientacceptance',
            index=models.Index(fields=['acceptance_status'], name='t_client_ac_accepta_da5a1c_idx'),
        ),
    ]
