# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitybom',
            new_name='t_activity__templat_0a2817_idx',
            old_name='resource_bom_tpl_idx',
        ),
        migrations.RenameIndex(
            model_name='activitybom',
            new_name='t_activity__resourc_71172f_idx',
            old_name='resource_bom_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='activitytemplate',
            new_name='t_activity__code_a025d6_idx',
            old_name='resource_at_code_idx',
        ),
        migrations.RenameIndex(
            model_name='activitytemplate',
            new_name='t_activity__is_acti_0dc6d2_idx',
            old_name='resource_at_active_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcecategory',
            new_name='t_resource__resourc_51784c_idx',
            old_name='resource_re_resourc_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcecategory',
            new_name='t_resource__parent__4eff4b_idx',
            old_name='resource_re_parent__idx',
        ),
        migrations.RenameIndex(
            model_name='resourcecategory',
            new_name='t_resource__code_71673f_idx',
            old_name='resource_re_code_idx',
        ),
        migrations.RenameIndex(
            model_name='resourceitem',
            new_name='t_resource__categor_6bbe3a_idx',
            old_name='resource_ri_cat_sta_idx',
        ),
        migrations.RenameIndex(
            model_name='resourceitem',
            new_name='t_resource__code_cbd7fc_idx',
            old_name='resource_ri_code_idx',
        ),
        migrations.RenameIndex(
            model_name='resourceitem',
            new_name='t_resource__status_a80bba_idx',
            old_name='resource_ri_status_idx',
        ),
    ]
