# Generated by Django 4.2.27 on 2026-02-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_workorderqualityaudit_and_more'),
        ('resource', '0002_rename_resource_bom_tpl_idx_t_activity__templat_0a2817_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', '预防性维护'), ('corrective', '纠正性维护'), ('emergency', '紧急维修')], max_length=20, verbose_name='维护类型')),
                ('maintenance_date', models.DateField(verbose_name='维护日期')),
                ('description', models.TextField(verbose_name='维护内容')),
                ('performed_by', models.CharField(blank=True, default='', max_length=200, verbose_name='维护人')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='resource.resourceitem', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备维护',
                'db_table': 't_equipment_maintenance',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='VenueReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('purpose', models.CharField(blank=True, default='', max_length=500, verbose_name='用途')),
                ('reserved_by_id', models.IntegerField(blank=True, null=True, verbose_name='预约人ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='resource.resourceitem', verbose_name='场地')),
            ],
            options={
                'verbose_name': '场地预约',
                'db_table': 't_venue_reservation',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['venue', 'start_time'], name='t_venue_res_venue_i_7f1af9_idx'), models.Index(fields=['status'], name='t_venue_res_status_c42c3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='VenueEnvironmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(verbose_name='记录时间')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度(°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度(%)')),
                ('is_compliant', models.BooleanField(default=True, verbose_name='是否合规')),
                ('non_compliance_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='不合规原因')),
                ('recorder_id', models.IntegerField(blank=True, null=True, verbose_name='记录人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('venue', models.ForeignKey(help_text='ResourceItem with resource_type=environment', on_delete=django.db.models.deletion.CASCADE, related_name='environment_logs', to='resource.resourceitem', verbose_name='场地')),
            ],
            options={
                'verbose_name': '环境监控记录',
                'db_table': 't_venue_environment_log',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['venue', 'recorded_at'], name='t_venue_env_venue_i_88d690_idx'), models.Index(fields=['is_compliant'], name='t_venue_env_is_comp_0d8803_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(verbose_name='使用日期')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='使用时长(分钟)')),
                ('operator_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='操作人ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='resource.resourceitem', verbose_name='设备')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_usages', to='workorder.workorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '设备使用记录',
                'db_table': 't_equipment_usage',
                'ordering': ['-usage_date'],
                'indexes': [models.Index(fields=['equipment', 'usage_date'], name='t_equipment_equipme_30dc21_idx'), models.Index(fields=['work_order'], name='t_equipment_work_or_734461_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField(verbose_name='校准日期')),
                ('next_due_date', models.DateField(verbose_name='下次校准到期日')),
                ('calibrator', models.CharField(blank=True, default='', max_length=200, verbose_name='校准人/机构')),
                ('certificate_no', models.CharField(blank=True, default='', max_length=100, verbose_name='校准证书编号')),
                ('result', models.CharField(default='pass', help_text='pass/fail/conditional', max_length=50, verbose_name='校准结果')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('feishu_calendar_event_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书日历事件ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='resource.resourceitem', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备校准',
                'db_table': 't_equipment_calibration',
                'ordering': ['-calibration_date'],
                'indexes': [models.Index(fields=['equipment', 'next_due_date'], name='t_equipment_equipme_6a739f_idx')],
            },
        ),
    ]
