# Generated by Django 4.2.27 on 2026-02-17 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_alter_deviation_status_capaactionitem'),
        ('resource', '0003_equipmentmaintenance_venuereservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionMethodTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='方法编号')),
                ('name', models.CharField(max_length=200, verbose_name='方法名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='英文名称')),
                ('category', models.CharField(choices=[('skin_hydration', '皮肤水分'), ('skin_elasticity', '皮肤弹性'), ('skin_color', '皮肤色素'), ('skin_imaging', '皮肤成像'), ('skin_roughness', '皮肤粗糙度'), ('skin_sebum', '皮脂分泌'), ('skin_ph', '皮肤pH值'), ('skin_barrier', '皮肤屏障'), ('hair_analysis', '毛发分析'), ('patch_test', '斑贴试验'), ('efficacy_general', '功效综合'), ('other', '其他')], default='other', max_length=30, verbose_name='方法类别')),
                ('description', models.TextField(blank=True, default='', verbose_name='方法说明')),
                ('standard_procedure', models.TextField(blank=True, default='', help_text='JSON 格式步骤列表：[{"step": 1, "name": "...", "description": "...", "duration_minutes": 5}]', verbose_name='标准操作步骤')),
                ('sop_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='SOP 参考编号')),
                ('estimated_duration_minutes', models.IntegerField(default=30, verbose_name='预计检测时长(分钟)')),
                ('preparation_time_minutes', models.IntegerField(default=10, verbose_name='准备时长(分钟)')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最低温度(°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最高温度(°C)')),
                ('humidity_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最低湿度(%)')),
                ('humidity_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最高湿度(%)')),
                ('environment_notes', models.TextField(blank=True, default='', verbose_name='环境要求备注')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='用于协议解析自动匹配，如 ["角质层含水量", "Corneometer", "skin hydration"]', verbose_name='关键词')),
                ('normal_range', models.JSONField(blank=True, default=dict, help_text='{"min": 20, "max": 80, "unit": "AU", "notes": "取决于测量部位"}', verbose_name='正常值范围')),
                ('measurement_points', models.JSONField(blank=True, default=list, help_text='[{"name": "左颊", "code": "L_CHEEK", "repeat": 3}]', verbose_name='测量点配置')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '有效'), ('deprecated', '已废弃')], default='draft', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('sop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_methods', to='quality.sop', verbose_name='关联SOP')),
            ],
            options={
                'verbose_name': '检测方法模板',
                'db_table': 't_detection_method_template',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DetectionMethodResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('equipment', '设备'), ('consumable', '耗材'), ('venue', '场地'), ('software', '软件')], max_length=20, verbose_name='资源类型')),
                ('quantity', models.IntegerField(default=1, verbose_name='需求数量')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='是否必须')),
                ('recommended_models', models.JSONField(blank=True, default=list, help_text='["VISIA-CR Gen7", "VISIA-CR Gen8"]', verbose_name='推荐型号')),
                ('usage_notes', models.TextField(blank=True, default='', verbose_name='使用说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requirements', to='resource.detectionmethodtemplate', verbose_name='检测方法')),
                ('resource_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='method_requirements', to='resource.resourcecategory', verbose_name='资源类别')),
            ],
            options={
                'verbose_name': '检测方法资源需求',
                'db_table': 't_detection_method_resource',
                'ordering': ['method', 'resource_type'],
            },
        ),
        migrations.CreateModel(
            name='DetectionMethodPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(help_text='如：VISIA 操作认证、GCP 证书', max_length=200, verbose_name='资质名称')),
                ('qualification_code', models.CharField(blank=True, default='', max_length=50, verbose_name='资质编号')),
                ('level', models.CharField(choices=[('required', '必须'), ('preferred', '优先'), ('training', '培训中')], default='required', max_length=20, verbose_name='要求级别')),
                ('min_experience_months', models.IntegerField(default=0, verbose_name='最低经验(月)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_requirements', to='resource.detectionmethodtemplate', verbose_name='检测方法')),
            ],
            options={
                'verbose_name': '检测方法人员资质',
                'db_table': 't_detection_method_personnel',
                'ordering': ['method', 'level'],
            },
        ),
    ]
