# Generated by Django 4.2.27 on 2026-02-17 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_detectionmethodtemplate_detectionmethodresource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.IntegerField(help_text='Account ID', verbose_name='操作人ID')),
                ('operator_name', models.CharField(default='', max_length=100, verbose_name='操作人姓名')),
                ('authorized_at', models.DateField(verbose_name='授权日期')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='授权到期日')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('training_record', models.TextField(blank=True, default='', help_text='培训内容/考核结果', verbose_name='培训记录')),
                ('authorized_by_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='授权人ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备操作授权',
                'db_table': 't_equipment_authorization',
            },
        ),
        migrations.AddField(
            model_name='equipmentcalibration',
            name='calibration_type',
            field=models.CharField(choices=[('internal', '内部校准'), ('external', '外部校准')], default='internal', max_length=20, verbose_name='校准类型'),
        ),
        migrations.AddField(
            model_name='equipmentcalibration',
            name='certificate_file_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='校准证书文件URL'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='assigned_to_id',
            field=models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='负责人ID'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='reported_by_id',
            field=models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='报修人ID'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='requires_recalibration',
            field=models.BooleanField(default=False, verbose_name='是否需要重新校准'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='result_notes',
            field=models.TextField(blank=True, default='', verbose_name='维修结果说明'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='title',
            field=models.CharField(default='', help_text='维护工单简洁标题', max_length=200, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='equipmentmaintenance',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='操作人姓名'),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='usage_type',
            field=models.CharField(choices=[('workorder', '工单关联'), ('manual', '手动登记'), ('training', '培训使用')], default='workorder', max_length=20, verbose_name='使用类型'),
        ),
        migrations.AddIndex(
            model_name='equipmentcalibration',
            index=models.Index(fields=['result'], name='t_equipment_result_4f84d5_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmaintenance',
            index=models.Index(fields=['equipment', 'status'], name='t_equipment_equipme_d8a23e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmaintenance',
            index=models.Index(fields=['status', 'maintenance_type'], name='t_equipment_status_301b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmaintenance',
            index=models.Index(fields=['assigned_to_id'], name='t_equipment_assigne_978819_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusage',
            index=models.Index(fields=['operator_id'], name='t_equipment_operato_c54661_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusage',
            index=models.Index(fields=['usage_type'], name='t_equipment_usage_t_e8279a_idx'),
        ),
        migrations.AddField(
            model_name='equipmentauthorization',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='resource.resourceitem', verbose_name='设备'),
        ),
        migrations.AddIndex(
            model_name='equipmentauthorization',
            index=models.Index(fields=['equipment', 'is_active'], name='t_equipment_equipme_9cd66a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentauthorization',
            index=models.Index(fields=['operator_id'], name='t_equipment_operato_f46013_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentauthorization',
            index=models.Index(fields=['expires_at'], name='t_equipment_expires_21ead8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentauthorization',
            unique_together={('equipment', 'operator_id')},
        ),
    ]
