# Generated by Django 4.2.27 on 2026-02-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_equipment_workstation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_no', models.CharField(max_length=50, unique=True, verbose_name='事件编号')),
                ('severity', models.CharField(choices=[('minor', '轻微'), ('major', '一般'), ('critical', '严重')], default='minor', max_length=20, verbose_name='严重级别')),
                ('status', models.CharField(choices=[('open', '待处理'), ('investigating', '调查中'), ('corrected', '已纠正'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='事件描述')),
                ('deviation_param', models.CharField(blank=True, default='', max_length=200, verbose_name='偏离参数')),
                ('deviation_duration', models.CharField(blank=True, default='', max_length=100, verbose_name='偏离时长')),
                ('affected_tests', models.TextField(blank=True, default='', verbose_name='影响的测试')),
                ('root_cause', models.TextField(blank=True, default='', verbose_name='根因分析')),
                ('corrective_action', models.TextField(blank=True, default='', verbose_name='纠正措施')),
                ('preventive_action', models.TextField(blank=True, default='', verbose_name='预防措施')),
                ('reporter_id', models.IntegerField(blank=True, null=True, verbose_name='报告人ID')),
                ('reporter_name', models.CharField(blank=True, default='', max_length=100, verbose_name='报告人')),
                ('assigned_to_id', models.IntegerField(blank=True, null=True, verbose_name='负责人ID')),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=100, verbose_name='负责人')),
                ('discovered_at', models.DateTimeField(blank=True, null=True, verbose_name='发现时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='resource.resourceitem', verbose_name='场地')),
            ],
            options={
                'verbose_name': '不合规事件',
                'db_table': 't_environment_incident',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['venue', 'status'], name='t_environme_venue_i_595df3_idx'), models.Index(fields=['severity'], name='t_environme_severit_e60db8_idx'), models.Index(fields=['create_time'], name='t_environme_create__1cd17c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('daily', '日常清洁'), ('between', '场次间清洁'), ('deep', '深度清洁'), ('special', '特殊清洁')], default='daily', max_length=20, verbose_name='清洁类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('completed', '已完成'), ('verified', '已验证')], default='pending', max_length=20, verbose_name='状态')),
                ('cleaner_name', models.CharField(blank=True, default='', max_length=100, verbose_name='清洁人员')),
                ('cleaner_id', models.IntegerField(blank=True, null=True, verbose_name='清洁人员ID')),
                ('verifier_name', models.CharField(blank=True, default='', max_length=100, verbose_name='验证人')),
                ('verifier_id', models.IntegerField(blank=True, null=True, verbose_name='验证人ID')),
                ('cleaning_date', models.DateField(verbose_name='清洁日期')),
                ('cleaning_agents', models.CharField(blank=True, default='', max_length=500, verbose_name='使用清洁剂')),
                ('checklist_items', models.IntegerField(default=0, verbose_name='检查项数')),
                ('checklist_completed', models.IntegerField(default=0, verbose_name='已完成项数')),
                ('env_confirmed', models.BooleanField(default=False, verbose_name='环境恢复确认')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_records', to='resource.resourceitem', verbose_name='场地')),
            ],
            options={
                'verbose_name': '清洁记录',
                'db_table': 't_cleaning_record',
                'ordering': ['-cleaning_date', '-create_time'],
                'indexes': [models.Index(fields=['venue', 'cleaning_date'], name='t_cleaning__venue_i_d168b9_idx'), models.Index(fields=['cleaning_type'], name='t_cleaning__cleanin_ad061a_idx'), models.Index(fields=['status'], name='t_cleaning__status_ec1221_idx')],
            },
        ),
    ]
