# Generated by Django 4.2.27 on 2026-03-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0011_venue_usage_schedule_flexible'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipmentverification',
            new_name='t_equipment_equipme_b9c9c4_idx',
            old_name='t_equipment__equipme_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentverification',
            new_name='t_equipment_result_6d6ab8_idx',
            old_name='t_equipment__result_idx',
        ),
        migrations.RenameIndex(
            model_name='venuechangelog',
            new_name='t_venue_cha_venue_i_20aa6f_idx',
            old_name='t_venue_ch_venue_i_idx',
        ),
        migrations.RenameIndex(
            model_name='venuechangelog',
            new_name='t_venue_cha_change__8afac2_idx',
            old_name='t_venue_ch_change__idx',
        ),
        migrations.RenameIndex(
            model_name='venuemonitorconfig',
            new_name='t_venue_mon_venue_i_5fea4d_idx',
            old_name='t_venue_mo_venue_i_idx',
        ),
        migrations.RenameIndex(
            model_name='venueusageschedule',
            new_name='t_venue_usa_venue_i_84ea52_idx',
            old_name='t_venue_us_venue_i_idx',
        ),
        migrations.RenameIndex(
            model_name='venueusageschedule',
            new_name='t_venue_usa_venue_i_ae11ef_idx',
            old_name='t_venue_us_venue_i_idx2',
        ),
        migrations.RenameIndex(
            model_name='venueusageschedule',
            new_name='t_venue_usa_specifi_33cb19_idx',
            old_name='t_venue_us_specific_idx',
        ),
        migrations.AlterField(
            model_name='equipmentmaintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('preventive', '预防性维护'), ('corrective', '纠正性维护'), ('emergency', '紧急维修'), ('calibration', '校准'), ('verification', '核查')], max_length=20, verbose_name='维护类型'),
        ),
    ]
