# Generated by Django 4.2.27 on 2026-02-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待入组'), ('enrolled', '已入组'), ('completed', '已完成'), ('withdrawn', '已退出')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True, verbose_name='入组时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '入组记录',
                'db_table': 't_enrollment',
            },
        ),
        migrations.CreateModel(
            name='ICFVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='版本号')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'ICF版本',
                'db_table': 't_icf_version',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='', max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='手机号')),
                ('skin_type', models.CharField(blank=True, choices=[('I', 'I型'), ('II', 'II型'), ('III', 'III型'), ('IV', 'IV型'), ('V', 'V型'), ('VI', 'VI型')], default='', max_length=10, verbose_name='皮肤类型')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=20, verbose_name='风险等级')),
                ('status', models.CharField(choices=[('screening', '筛选中'), ('enrolled', '已入组'), ('active', '进行中'), ('completed', '已完成'), ('withdrawn', '已退出'), ('disqualified', '不符合')], db_index=True, default='screening', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '受试者',
                'db_table': 't_subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签署时间')),
                ('signature_data', models.JSONField(blank=True, null=True, verbose_name='签名数据')),
                ('is_signed', models.BooleanField(default=False, verbose_name='已签署')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('icf_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='subject.icfversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='subject.subject')),
            ],
            options={
                'verbose_name': '知情同意书签署',
                'db_table': 't_subject_consent',
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['status', 'create_time'], name='t_subject_status_bc82ca_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['phone'], name='t_subject_phone_cc69d5_idx'),
        ),
        migrations.AddField(
            model_name='icfversion',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icf_versions', to='protocol.protocol'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='protocol.protocol'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='subject.subject'),
        ),
        migrations.AddIndex(
            model_name='subjectconsent',
            index=models.Index(fields=['subject', 'signed_at'], name='t_subject_c_subject_349bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectconsent',
            index=models.Index(fields=['icf_version'], name='t_subject_c_icf_ver_e1989a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectconsent',
            unique_together={('subject', 'icf_version')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status', 'enrolled_at'], name='t_enrollmen_status_e62520_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['protocol', 'status'], name='t_enrollmen_protoco_a9cb81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('subject', 'protocol')},
        ),
    ]
