# Generated by Django 4.2.27 on 2026-02-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_accountrole_constraints'),
        ('subject', '0003_add_enrollment_created_by_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='account',
            field=models.OneToOneField(blank=True, help_text='受试者本人的登录账号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_profile_ref', to='identity.account', verbose_name='关联账号'),
        ),
        migrations.AddField(
            model_name='subject',
            name='source_channel',
            field=models.CharField(blank=True, choices=[('hospital', '医院'), ('clinic', '诊所'), ('online', '线上'), ('advertisement', '广告'), ('referral', '转介'), ('database', '数据库'), ('wechat', '微信'), ('other', '其他')], default='', help_text='受试者从哪个渠道获取', max_length=20, verbose_name='来源渠道'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_no',
            field=models.CharField(blank=True, default='', help_text='系统自动生成，格式 SUB-YYYYMM-NNNN', max_length=20, unique=True, verbose_name='受试者编号'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_no'], name='t_subject_subject_8c5eac_idx'),
        ),
    ]
