# Generated by Django 4.2.27 on 2026-02-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_p3_execution_checkin_compliance_payment'),
        ('subject', '0006_p2_recruitment_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='工单编号')),
                ('category', models.CharField(choices=[('question', '咨询'), ('complaint', '投诉'), ('suggestion', '建议'), ('schedule', '排程相关'), ('payment', '礼金相关'), ('other', '其他')], default='question', max_length=20, verbose_name='分类')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('replied', '已回复'), ('closed', '已关闭')], db_index=True, default='open', max_length=20, verbose_name='状态')),
                ('reply', models.TextField(blank=True, default='', verbose_name='回复内容')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('replied_by_id', models.IntegerField(blank=True, null=True, verbose_name='回复人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='subject.subject')),
            ],
            options={
                'verbose_name': '客服工单',
                'db_table': 't_subject_support_ticket',
            },
        ),
        migrations.CreateModel(
            name='SubjectQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_type', models.CharField(help_text='自评/他评/满意度/VAS等', max_length=50, verbose_name='问卷类型')),
                ('title', models.CharField(max_length=200, verbose_name='问卷标题')),
                ('form_definition', models.JSONField(blank=True, help_text='问卷结构 JSON Schema', null=True, verbose_name='表单定义')),
                ('answers', models.JSONField(blank=True, null=True, verbose_name='答案')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='评分')),
                ('status', models.CharField(choices=[('pending', '待填写'), ('in_progress', '填写中'), ('submitted', '已提交'), ('verified', '已核实')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='subject.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='subject.subject')),
            ],
            options={
                'verbose_name': '受试者问卷',
                'db_table': 't_subject_questionnaire',
            },
        ),
        migrations.CreateModel(
            name='SubjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='支付编号')),
                ('payment_type', models.CharField(choices=[('visit_compensation', '到访补偿'), ('transportation', '交通补贴'), ('meal', '餐食补贴'), ('completion_bonus', '完成奖励'), ('referral', '推荐奖励'), ('other', '其他')], max_length=30, verbose_name='支付类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('status', models.CharField(choices=[('pending', '待发起'), ('initiated', '已发起'), ('approved', '已审批'), ('paid', '已支付'), ('failed', '支付失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('initiated_at', models.DateTimeField(blank=True, null=True, verbose_name='发起时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('payment_method', models.CharField(blank=True, default='', help_text='微信/银行转账/现金', max_length=50, verbose_name='支付方式')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100, verbose_name='交易号')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subject.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subject.subject')),
            ],
            options={
                'verbose_name': '礼金支付',
                'db_table': 't_subject_payment',
                'indexes': [models.Index(fields=['subject', 'status'], name='t_subject_p_subject_c513f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='签到日期')),
                ('checkin_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='签出时间')),
                ('status', models.CharField(choices=[('checked_in', '已签到'), ('in_progress', '执行中'), ('checked_out', '已签出'), ('no_show', '缺席')], db_index=True, default='checked_in', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='签到位置')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='subject.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='subject.subject')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_checkins', to='workorder.workorder')),
            ],
            options={
                'verbose_name': '签到记录',
                'db_table': 't_subject_checkin',
                'indexes': [models.Index(fields=['subject', 'checkin_date'], name='t_subject_c_subject_466334_idx'), models.Index(fields=['enrollment', 'status'], name='t_subject_c_enrollm_228380_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='预约日期')),
                ('appointment_time', models.TimeField(blank=True, null=True, verbose_name='预约时间')),
                ('purpose', models.CharField(blank=True, default='', max_length=200, verbose_name='预约事由')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('completed', '已完成'), ('no_show', '缺席')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('confirmed_by_id', models.IntegerField(blank=True, null=True, verbose_name='确认人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='subject.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='subject.subject')),
            ],
            options={
                'verbose_name': '预约记录',
                'db_table': 't_subject_appointment',
                'indexes': [models.Index(fields=['subject', 'appointment_date'], name='t_subject_a_subject_8a149c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(verbose_name='评估日期')),
                ('visit_attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='到访率(%)')),
                ('questionnaire_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='问卷完成率(%)')),
                ('time_window_deviation', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='时间窗偏差(天)')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='综合评分')),
                ('level', models.CharField(blank=True, choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '较差'), ('non_compliant', '不合规')], default='', max_length=20, verbose_name='依从性等级')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('assessed_by_id', models.IntegerField(blank=True, null=True, verbose_name='评估人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='subject.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='subject.subject')),
            ],
            options={
                'verbose_name': '依从性记录',
                'db_table': 't_subject_compliance',
                'indexes': [models.Index(fields=['subject', 'assessment_date'], name='t_subject_c_subject_3d67d7_idx')],
            },
        ),
    ]
