# Generated by Django 4.2.27 on 2026-02-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_p3_execution_checkin_compliance_payment'),
        ('subject', '0007_p3_execution_checkin_compliance_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSignRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True, verbose_name='测量时间')),
                ('source', models.CharField(choices=[('manual', '手工录入'), ('device', '设备采集'), ('imported', '导入'), ('lims', 'LIMS系统'), ('edc', 'EDC采集')], default='manual', max_length=20, verbose_name='数据来源')),
                ('operator_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('systolic_bp', models.IntegerField(blank=True, null=True, verbose_name='收缩压(mmHg)')),
                ('diastolic_bp', models.IntegerField(blank=True, null=True, verbose_name='舒张压(mmHg)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率(bpm)')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='呼吸频率(次/分)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体温(℃)')),
                ('spo2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='血氧饱和度(%)')),
                ('enrollment', models.ForeignKey(blank=True, help_text='关联入组（null 表示独立于项目的数据）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='subject.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='subject.subject')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='workorder.workorder')),
            ],
            options={
                'verbose_name': '生命体征',
                'db_table': 't_vital_sign_record',
                'indexes': [models.Index(fields=['subject', 'measured_at'], name='t_vital_sig_subject_19d384_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkinMeasurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True, verbose_name='测量时间')),
                ('source', models.CharField(choices=[('manual', '手工录入'), ('device', '设备采集'), ('imported', '导入'), ('lims', 'LIMS系统'), ('edc', 'EDC采集')], default='manual', max_length=20, verbose_name='数据来源')),
                ('operator_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('measurement_site', models.CharField(blank=True, default='', help_text='前额/脸颊/前臂等', max_length=100, verbose_name='测量部位')),
                ('instrument', models.CharField(blank=True, default='', max_length=100, verbose_name='仪器')),
                ('moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='水分值(Corneometer)')),
                ('tewl', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='TEWL值(Tewameter)')),
                ('sebum', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='皮脂值(Sebumeter)')),
                ('melanin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='黑色素(Mexameter)')),
                ('erythema', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='红斑值(Mexameter)')),
                ('elasticity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='弹性(Cutometer)')),
                ('gloss', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='光泽度(Glossymeter)')),
                ('ph_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH值(Skin-pH-Meter)')),
                ('roughness', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='粗糙度(PRIMOS)')),
                ('image_path', models.CharField(blank=True, default='', help_text='VISIA/拍照', max_length=500, verbose_name='影像路径')),
                ('enrollment', models.ForeignKey(blank=True, help_text='关联入组（null 表示独立于项目的数据）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='subject.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='subject.subject')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='workorder.workorder')),
            ],
            options={
                'verbose_name': '皮肤测量',
                'db_table': 't_skin_measurement_record',
                'indexes': [models.Index(fields=['subject', 'measured_at'], name='t_skin_meas_subject_153ef8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True, verbose_name='测量时间')),
                ('source', models.CharField(choices=[('manual', '手工录入'), ('device', '设备采集'), ('imported', '导入'), ('lims', 'LIMS系统'), ('edc', 'EDC采集')], default='manual', max_length=20, verbose_name='数据来源')),
                ('operator_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_code', models.CharField(max_length=50, verbose_name='检验项编码')),
                ('test_name', models.CharField(max_length=200, verbose_name='检验项名称')),
                ('result_value', models.CharField(blank=True, default='', max_length=100, verbose_name='结果值')),
                ('result_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='数值结果')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='单位')),
                ('reference_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='参考下限')),
                ('reference_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='参考上限')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('specimen_type', models.CharField(blank=True, default='', help_text='血液/尿液/唾液等', max_length=50, verbose_name='标本类型')),
                ('enrollment', models.ForeignKey(blank=True, help_text='关联入组（null 表示独立于项目的数据）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='subject.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='subject.subject')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='workorder.workorder')),
            ],
            options={
                'verbose_name': '实验室检验',
                'db_table': 't_lab_result_record',
                'indexes': [models.Index(fields=['subject', 'measured_at'], name='t_lab_resul_subject_9f9a6c_idx'), models.Index(fields=['test_code'], name='t_lab_resul_test_co_738e86_idx')],
            },
        ),
        migrations.CreateModel(
            name='BodyMetricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True, verbose_name='测量时间')),
                ('source', models.CharField(choices=[('manual', '手工录入'), ('device', '设备采集'), ('imported', '导入'), ('lims', 'LIMS系统'), ('edc', 'EDC采集')], default='manual', max_length=20, verbose_name='数据来源')),
                ('operator_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='身高(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='体重(kg)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='BMI')),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='腰围(cm)')),
                ('hip', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='臀围(cm)')),
                ('body_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体脂率(%)')),
                ('enrollment', models.ForeignKey(blank=True, help_text='关联入组（null 表示独立于项目的数据）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='subject.enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='subject.subject')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_records', to='workorder.workorder')),
            ],
            options={
                'verbose_name': '体格测量',
                'db_table': 't_body_metric_record',
                'indexes': [models.Index(fields=['subject', 'measured_at'], name='t_body_metr_subject_cf6745_idx')],
            },
        ),
    ]
