# Generated by Django 4.2.27 on 2026-02-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_p4_timeseries_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('category', models.CharField(choices=[('screening', '筛选问卷'), ('follow_up', '随访问卷'), ('satisfaction', '满意度调查'), ('safety', '安全性问卷'), ('pro', '患者报告结局'), ('other', '其他')], default='other', max_length=50, verbose_name='问卷类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='问卷描述')),
                ('form_definition', models.JSONField(blank=True, help_text='JSON Schema 格式的表单定义', null=True, verbose_name='表单定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '问卷模板',
                'db_table': 't_questionnaire_template',
            },
        ),
        migrations.CreateModel(
            name='SubjectLoyaltyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(db_index=True, unique=True, verbose_name='受试者ID')),
                ('total_score', models.IntegerField(default=0, verbose_name='总评分')),
                ('participation_count', models.IntegerField(default=0, verbose_name='参与项目数')),
                ('completion_count', models.IntegerField(default=0, verbose_name='完成项目数')),
                ('compliance_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='平均依从性')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='最后活跃日期')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], db_index=True, default='low', max_length=20, verbose_name='流失风险')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '受试者忠诚度评分',
                'db_table': 't_subject_loyalty_score',
            },
        ),
        migrations.AddField(
            model_name='enrollmentrecord',
            name='withdrawal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退出时间'),
        ),
        migrations.AddField(
            model_name='enrollmentrecord',
            name='withdrawal_initiated_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='退出操作人ID'),
        ),
        migrations.AddField(
            model_name='enrollmentrecord',
            name='withdrawal_reason',
            field=models.TextField(blank=True, default='', verbose_name='退出原因'),
        ),
        migrations.AddField(
            model_name='subjectregistration',
            name='withdrawal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退出时间'),
        ),
        migrations.AddField(
            model_name='subjectregistration',
            name='withdrawal_initiated_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='退出操作人ID'),
        ),
        migrations.AddField(
            model_name='subjectregistration',
            name='withdrawal_reason',
            field=models.TextField(blank=True, default='', verbose_name='退出原因'),
        ),
        migrations.CreateModel(
            name='SubjectReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_id', models.IntegerField(db_index=True, verbose_name='推荐人ID')),
                ('referred_id', models.IntegerField(db_index=True, verbose_name='被推荐人ID')),
                ('plan_id', models.IntegerField(blank=True, null=True, verbose_name='关联计划ID')),
                ('reward_payment_id', models.IntegerField(blank=True, null=True, verbose_name='奖励支付ID')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '受试者推荐关系',
                'db_table': 't_subject_referral',
                'unique_together': {('referrer_id', 'referred_id', 'plan_id')},
            },
        ),
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateTimeField(auto_now_add=True, verbose_name='联系时间')),
                ('contact_type', models.CharField(choices=[('phone', '电话'), ('wechat', '微信'), ('email', '邮件'), ('visit', '面访'), ('sms', '短信'), ('other', '其他')], default='phone', max_length=20, verbose_name='联系方式')),
                ('content', models.TextField(verbose_name='联系内容')),
                ('result', models.CharField(choices=[('interested', '有意向'), ('not_interested', '无意向'), ('scheduled', '已约筛选'), ('no_answer', '未接通'), ('callback', '要求回电'), ('need_time', '需考虑'), ('other', '其他')], default='other', max_length=30, verbose_name='联系结果')),
                ('next_contact_date', models.DateField(blank=True, null=True, verbose_name='下次联系日期')),
                ('next_contact_plan', models.CharField(blank=True, default='', max_length=200, verbose_name='下次联系计划')),
                ('contacted_by_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_records', to='subject.subjectregistration')),
            ],
            options={
                'verbose_name': '跟进记录',
                'db_table': 't_contact_record',
                'ordering': ['-contact_date'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(db_index=True, verbose_name='受试者ID')),
                ('enrollment_id', models.IntegerField(blank=True, null=True, verbose_name='入组ID')),
                ('status', models.CharField(choices=[('pending', '待完成'), ('in_progress', '进行中'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('responses', models.JSONField(blank=True, null=True, verbose_name='答卷数据')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='评分')),
                ('assigned_by_id', models.IntegerField(blank=True, null=True, verbose_name='分配人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subject.questionnairetemplate')),
            ],
            options={
                'verbose_name': '问卷分配',
                'db_table': 't_questionnaire_assignment',
                'indexes': [models.Index(fields=['subject_id', 'status'], name='t_questionn_subject_e18def_idx'), models.Index(fields=['template', 'status'], name='t_questionn_templat_571985_idx')],
            },
        ),
    ]
