# Generated by Django 4.2.27 on 2026-02-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0006_p2_recruitment_tables'),
        ('subject', '0009_contact_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('pre_screening', '粗筛中'), ('pre_screened', '粗筛通过'), ('screening', '筛选中'), ('enrolled', '已入组'), ('active', '进行中'), ('completed', '已完成'), ('withdrawn', '已退出'), ('disqualified', '不符合')], db_index=True, default='screening', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='subjectregistration',
            name='status',
            field=models.CharField(choices=[('registered', '已报名'), ('contacted', '已联系'), ('pre_screening', '粗筛中'), ('pre_screened_pass', '粗筛通过'), ('pre_screened_fail', '粗筛不通过'), ('screening', '筛选中'), ('screened_pass', '筛选通过'), ('screened_fail', '筛选未通过'), ('enrolled', '已入组'), ('withdrawn', '已退出')], db_index=True, default='registered', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='PreScreeningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_screening_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='粗筛编号')),
                ('pre_screening_date', models.DateField(verbose_name='粗筛日期')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='粗筛地点')),
                ('hard_exclusion_checks', models.JSONField(blank=True, help_text='[{"item":"年龄范围","met":true,"value":"28"}, ...]', null=True, verbose_name='硬性排除条件检查')),
                ('skin_visual_assessment', models.JSONField(blank=True, help_text='{"overall_condition","test_site_integrity","fitzpatrick_type",...}', null=True, verbose_name='皮肤视觉评估')),
                ('instrument_summary', models.JSONField(blank=True, help_text='{"visia_done":true,"moisture_value":42.5,...}', null=True, verbose_name='仪器测量摘要')),
                ('medical_summary', models.JSONField(blank=True, help_text='{"conditions_count":0,"allergies_count":1,...}', null=True, verbose_name='医学史摘要')),
                ('lifestyle_summary', models.JSONField(blank=True, help_text='{"sun_exposure":"low","skincare_routine":"basic",...}', null=True, verbose_name='生活方式摘要')),
                ('result', models.CharField(choices=[('pending', '待评估'), ('pass', '通过'), ('fail', '未通过'), ('refer', '推荐其他项目')], db_index=True, default='pending', max_length=20, verbose_name='粗筛结果')),
                ('fail_reasons', models.JSONField(blank=True, default=list, help_text='["皮肤敏感度超标","近期使用过抗组胺药"]', null=True, verbose_name='不通过原因')),
                ('reviewer_decision', models.CharField(blank=True, default='', help_text='pass / fail（仅 result=pending 时由 PI 填写）', max_length=20, verbose_name='PI复核结果')),
                ('reviewer_notes', models.TextField(blank=True, default='', verbose_name='PI复核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('screening_appointment_id', models.IntegerField(blank=True, help_text='粗筛通过后创建的正式筛选预约 SubjectAppointment ID', null=True, verbose_name='筛选预约ID')),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='交通补贴金额')),
                ('compensation_paid', models.BooleanField(default=False, verbose_name='补贴已发放')),
                ('screener_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='粗筛评估员ID')),
                ('reviewer_id', models.IntegerField(blank=True, help_text='Account ID', null=True, verbose_name='复核人ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_screenings', to='protocol.protocol', verbose_name='关联协议')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_screenings', to='subject.subjectregistration', verbose_name='报名记录')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_screenings', to='subject.subject', verbose_name='受试者')),
            ],
            options={
                'verbose_name': '粗筛记录',
                'db_table': 't_pre_screening_record',
                'indexes': [models.Index(fields=['protocol', 'result'], name='t_pre_scree_protoco_6d7919_idx'), models.Index(fields=['pre_screening_date', 'result'], name='t_pre_scree_pre_scr_520eaf_idx'), models.Index(fields=['screener_id'], name='t_pre_scree_screene_25038a_idx')],
            },
        ),
    ]
