# Generated by Django 4.2.27 on 2026-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0011_subject_loyalty_nps_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectreferral',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='subjectreferral',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
