# Generated by Django 4.2.27 on 2026-02-21 23:45

from django.db import migrations, models
import django.db.models.deletion


def backfill_loyalty_fk_bridge(apps, schema_editor):
    Subject = apps.get_model('subject', 'Subject')
    SubjectLoyaltyScore = apps.get_model('subject', 'SubjectLoyaltyScore')
    SubjectReferral = apps.get_model('subject', 'SubjectReferral')

    subject_ids = set(Subject.objects.values_list('id', flat=True))

    for row in SubjectLoyaltyScore.objects.filter(subject_ref_id__isnull=True).only('id', 'subject_id'):
        if row.subject_id in subject_ids:
            row.subject_ref_id = row.subject_id
            row.save(update_fields=['subject_ref'])

    for row in SubjectReferral.objects.filter(referrer_subject_id__isnull=True).only('id', 'referrer_id'):
        if row.referrer_id in subject_ids:
            row.referrer_subject_id = row.referrer_id
            row.save(update_fields=['referrer_subject'])

    for row in SubjectReferral.objects.filter(referred_subject_id__isnull=True).only('id', 'referred_id'):
        if row.referred_id in subject_ids:
            row.referred_subject_id = row.referred_id
            row.save(update_fields=['referred_subject'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0012_subjectreferral_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectloyaltyscore',
            name='subject_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_scores', to='subject.subject', verbose_name='受试者FK（桥接）'),
        ),
        migrations.AddField(
            model_name='subjectreferral',
            name='referred_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to='subject.subject', verbose_name='被推荐人FK（桥接）'),
        ),
        migrations.AddField(
            model_name='subjectreferral',
            name='referrer_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent', to='subject.subject', verbose_name='推荐人FK（桥接）'),
        ),
        migrations.RunPython(backfill_loyalty_fk_bridge, noop_reverse),
    ]
