# Generated by Django 4.2.28 on 2026-03-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0014_support_ticket_sla_fields'),
    ]

    # 兼容分支占位迁移：
    # 后续 0019_appointment_visit_project_fields 已完整引入 visit_point/project_* 字段，
    # 这里改为 no-op，避免在新库/CI 从零迁移时重复 AddField 导致冲突。
    operations = []
