# Generated by Django 4.2.28 on 2026-03-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0014_support_ticket_sla_fields'),
    ]

    # 在 SubjectAppointment 上显式 AddField，供后续 0021/0022 等 AlterField 依赖的迁移状态一致。
    # （0019 仅索引/RenameIndex，未引入 visit_point；占位 no-op 会导致从零 migrate 时缺少该字段。）
    operations = [
        migrations.AddField(
            model_name='subjectappointment',
            name='visit_point',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='访视点'),
        ),
    ]
