# Generated by Django 4.2.28 on 2026-03-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0015_add_visit_point_to_appointment'),
    ]

    # project_code / project_name 是后续索引、AlterField 和接待台逻辑的前置字段。
    # 这里必须在新库初始化时真实创建，避免后续 0019/0021 链路找不到字段。
    operations = [
        migrations.AddField(
            model_name='subjectappointment',
            name='visit_point',
            field=models.CharField(
                blank=True,
                default='',
                max_length=100,
                verbose_name='访视点',
            ),
        ),
        migrations.AddField(
            model_name='subjectappointment',
            name='project_code',
            field=models.CharField(
                blank=True,
                default='',
                max_length=100,
                verbose_name='项目编号',
            ),
        ),
        migrations.AddField(
            model_name='subjectappointment',
            name='project_name',
            field=models.CharField(
                blank=True,
                default='',
                max_length=200,
                verbose_name='项目名称',
            ),
        ),
    ]
