# Generated by Django 4.2.27 on 2026-03-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0016_add_appointment_project_fields'),
        ('subject', '0018_rename_biz_token_to_byted_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='identityverifysession',
            new_name='t_identity__subject_2efe1e_idx',
            old_name='t_identity_v_subject_3c2e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='identityverifysession',
            new_name='t_identity__verify__67c01e_idx',
            old_name='t_identity_v_verify__e2f8b0_idx',
        ),
        migrations.AddIndex(
            model_name='subjectappointment',
            index=models.Index(fields=['appointment_date', 'project_code'], name='t_subject_a_appoint_304c9e_idx'),
        ),
    ]
