# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0019_appointment_visit_project_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', '待入组审批'), ('enrolled', '已入组'), ('completed', '已完成'), ('withdrawn', '已退出')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
