# Generated by Django 4.2.28 on 2026-03-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0020_alter_enrollment_status"),
        ("subject", "0021_merge_0016_and_0020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectappointment",
            name="project_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="研究机构方案编号",
                max_length=100,
                verbose_name="项目编号",
            ),
        ),
        migrations.AlterField(
            model_name="subjectappointment",
            name="project_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="研究名称",
                max_length=200,
                verbose_name="项目名称",
            ),
        ),
        migrations.AlterField(
            model_name="subjectappointment",
            name="visit_point",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如 V0/V1/粗筛/筛选/基线等",
                max_length=100,
                verbose_name="访视点",
            ),
        ),
    ]
