# Generated by Django 4.2.27 on 2026-03-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0021_merge_all_20260317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectappointment',
            name='visit_point',
            field=models.CharField(blank=True, default='', help_text='如 V0/V1/粗筛/筛选/基线等', max_length=100, verbose_name='访视点'),
        ),
    ]
