# Generated by Django 4.2.29 on 2026-03-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0021_alter_subjectappointment_project_code_and_more'),
        ('subject', '0022_alter_subjectappointment_visit_point'),
    ]

    operations = [
    ]
