# Generated by Django 4.2.29 on 2026-03-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0023_merge_20260311_1128'),
        ('subject', '0025_subject_project_sc'),
    ]

    operations = [
    ]
