# Generated by Django 4.2.27 on 2026-03-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0026_merge_20260314_0001'),
        ('subject', '0026_merge_20260315_2147'),
    ]

    operations = [
    ]
