# Generated by Django 4.2.27 on 2026-03-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0027_merge_20260317_1557'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectprojectsc',
            name='t_subject_project_sc_subject_project_uniq',
        ),
        migrations.RenameIndex(
            model_name='subjectprojectsc',
            new_name='t_subject_p_project_706840_idx',
            old_name='t_subject_p_project__a1b2c3_idx',
        ),
        migrations.AlterField(
            model_name='subjectprojectsc',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sc_records', to='subject.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectprojectsc',
            unique_together={('subject', 'project_code')},
        ),
    ]
