# Generated by Django 4.2.29 on 2026-03-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0027_merge_0026_conflict'),
        ('subject', '0028_remove_subjectprojectsc_t_subject_project_sc_subject_project_uniq_and_more'),
    ]

    operations = [
    ]
