# Generated by Django 4.2.29 on 2026-03-23 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_full_link', '0002_rename_project_ful_executi_idx_project_ful_executi_924710_idx_and_more'),
        ('subject', '0029_remove_subjectprojectsc_t_subject_project_sc_subject_project_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDiaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.CharField(blank=True, db_index=True, default='', help_text='业务编号冗余，如 W26000000', max_length=100, verbose_name='项目编号')),
                ('config_version_label', models.CharField(blank=True, default='', help_text='如 v1、2026Q1', max_length=50, verbose_name='配置版本标签')),
                ('form_definition_json', models.JSONField(default=list, help_text='题型、选项、顺序、必填等；小程序依此渲染', verbose_name='题目与表单定义')),
                ('rule_json', models.JSONField(default=dict, help_text='应填起止日、时间窗、补填等', verbose_name='填写与校验规则')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], db_index=True, default='draft', max_length=20, verbose_name='配置状态')),
                ('researcher_confirmed_at', models.DateTimeField(blank=True, help_text='非空表示 2.0 门禁已满足，可对受试者生效', null=True, verbose_name='研究员确认时间')),
                ('supervisor_confirmed_at', models.DateTimeField(blank=True, help_text='3.0 督导二次确认时使用', null=True, verbose_name='督导确认时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_diary_configs', to='project_full_link.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '受试者日记配置',
                'db_table': 't_subject_diary_config',
                'indexes': [models.Index(fields=['project', 'status'], name='t_subject_d_project_c374f1_idx'), models.Index(fields=['project_no'], name='t_subject_d_project_76524d_idx')],
            },
        ),
    ]
