# Generated by Django 4.2.29 on 2026-03-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0030_subject_diary_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdiary',
            name='symptom_duration',
            field=models.TextField(blank=True, default='', verbose_name='症状持续时长'),
        ),
        migrations.AddField(
            model_name='subjectdiary',
            name='symptom_onset',
            field=models.TextField(blank=True, default='', verbose_name='症状开始时间'),
        ),
        migrations.AddField(
            model_name='subjectdiary',
            name='symptom_severity',
            field=models.TextField(blank=True, default='', verbose_name='症状程度'),
        ),
        migrations.AlterField(
            model_name='subjectdiary',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='其它备注'),
        ),
    ]
