# Generated by Django 4.2.28 on 2026-03-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0031_subjectcheckin_project_code"),
    ]

    operations = [
        # 与 finance.0017 类似：部分库已是 Django 自动索引名，或新旧名并存，ALTER INDEX 会失败。
        # 仅同步 migration state，不在库上执行重命名。
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="receptionboardcheckin",
                    new_name="t_reception_subject_cd237d_idx",
                    old_name="t_reception_br_chk_subj_date_idx",
                ),
                migrations.RenameIndex(
                    model_name="receptionboardprojectsc",
                    new_name="t_reception_subject_46f40f_idx",
                    old_name="t_reception_br_sc_subj_pc_idx",
                ),
                migrations.RenameIndex(
                    model_name="subjectcheckin",
                    new_name="t_subject_c_subject_219efc_idx",
                    old_name="t_subject_chk_subj_dt_pc_idx",
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="subjectprojectsc",
            name="enrollment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("初筛合格", "初筛合格"),
                    ("正式入组", "正式入组"),
                    ("不合格", "不合格"),
                    ("复筛不合格", "复筛不合格"),
                    ("退出", "退出"),
                    ("缺席", "缺席"),
                ],
                default="",
                help_text="初筛合格/正式入组/不合格/复筛不合格/退出/缺席",
                max_length=20,
                verbose_name="入组情况",
            ),
        ),
        migrations.AlterField(
            model_name="subjectprojectsc",
            name="rd_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="仅当入组情况为正式入组时可填写，如 RD001",
                max_length=20,
                verbose_name="RD号",
            ),
        ),
        migrations.AlterField(
            model_name="subjectprojectsc",
            name="sc_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如 001、002，仅在访视点 V1 签到时按项目内顺序分配，后续访视复用",
                max_length=20,
                verbose_name="SC号",
            ),
        ),
    ]
