# Generated by Django 4.2.29 on 2026-03-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0033_subject_phone_active_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='icfversion',
            name='display_order',
            field=models.IntegerField(default=0, help_text='越小越靠前', verbose_name='签署顺序'),
        ),
        migrations.AddField(
            model_name='icfversion',
            name='mini_sign_rules',
            field=models.JSONField(blank=True, default=dict, help_text='人脸/双签/测验/阅读时长/采集项/双签人员等，与协议级配置结构一致；未保存前由协议配置兜底', verbose_name='小程序签署规则'),
        ),
        migrations.AddField(
            model_name='icfversion',
            name='mini_sign_rules_saved',
            field=models.BooleanField(default=False, help_text='至少完整保存过一次后为 True，用于列表标记与发布前校验', verbose_name='已保存小程序签署规则'),
        ),
        migrations.AddField(
            model_name='icfversion',
            name='node_title',
            field=models.CharField(blank=True, default='', help_text='如：知情同意书、照片使用授权书', max_length=200, verbose_name='节点标题'),
        ),
        migrations.AddField(
            model_name='icfversion',
            name='required_reading_duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='0 表示不校验，建议 10-600', verbose_name='要求阅读时长(秒)'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='investigator_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='研究者见证签署时间'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='staff_audit_status',
            field=models.CharField(blank=True, db_index=True, default='', help_text='pending_review=待审核(列表显示为已签署), approved=已通过审核, returned=退回重签中', max_length=24, verbose_name='工作人员审核状态'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='receipt_no',
            field=models.CharField(blank=True, db_index=True, help_text='同受试者、同协议下多知情节点共用同一回执号', max_length=64, null=True, verbose_name='签署回执号'),
        ),
    ]
