# Generated by Django 4.2.28 on 2026-03-27 02:39
# 仅包含 t_recruitment_plan 维周/主管扩展字段与 protocol 可空（避免与其它未对齐迁移冲突）

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0021_alter_consent_config_account_help_text_qa'),
        ('subject', '0033_subject_phone_active_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentplan',
            name='actual_work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='仅招募专员填写', max_digits=10, null=True, verbose_name='实际工时'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='channel_recruitment_needed',
            field=models.BooleanField(default=False, verbose_name='是否需要渠道招募'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='estimated_work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预计工时'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='material_prep_status',
            field=models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('published', '发布')], db_index=True, default='draft', max_length=20, verbose_name='物料准备状态'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='planned_appointment_count',
            field=models.IntegerField(default=0, verbose_name='计划预约人数'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, help_text='维周同步或手工录入，唯一', max_length=64, null=True, unique=True, verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='recruit_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='招募结束日期'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='recruit_specialist_names',
            field=models.JSONField(blank=True, default=list, help_text='姓名列表，多选则多人可见「我的计划」', verbose_name='派发招募专员'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='recruit_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='招募启动日期'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='researcher_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='研究员'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='sample_requirement',
            field=models.TextField(blank=True, default='', verbose_name='样本要求'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='supervisor_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='督导'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='wei_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='具体访视日期'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='wei_visit_point',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='访视点'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_plans', to='protocol.protocol', verbose_name='关联协议'),
        ),
    ]
