# Generated by Django 4.2.28 on 2026-03-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0033_add_subject_project_sc_enrollment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectprojectsc",
            name="enrollment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("初筛合格", "初筛合格"),
                    ("正式入组", "正式入组"),
                    ("不合格", "不合格"),
                    ("复筛不合格", "复筛不合格"),
                    ("退出", "退出"),
                ],
                default="",
                help_text="初筛合格/正式入组/不合格/复筛不合格/退出",
                max_length=20,
                verbose_name="入组情况",
            ),
        ),
        migrations.AlterField(
            model_name="subjectprojectsc",
            name="rd_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="仅当入组情况为正式入组时可填写，如 RD001",
                max_length=20,
                verbose_name="RD号",
            ),
        ),
        migrations.AlterField(
            model_name="subjectprojectsc",
            name="sc_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如 001、002，仅在访视点 V1 签到时按项目内顺序分配，后续访视复用",
                max_length=20,
                verbose_name="SC号",
            ),
        ),
    ]
