# Generated by Django 4.2.29 on 2026-03-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0031_subject_diary_symptom_detail_fields'),
        ('subject', '0033_subject_phone_active_uniq'),
    ]

    operations = [
    ]
