# Generated by Django 4.2.28 on 2026-03-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "subject",
            "0028_remove_subjectprojectsc_t_subject_project_sc_subject_project_uniq_and_more",
        ),
        ("subject", "0035_add_absence_to_enrollment_status"),
    ]

    operations = []
