# Generated by Django 4.2.27 on 2026-03-23 19:49 (hand-edited: removed DeleteModel ops already handled elsewhere)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0036_merge_20260320_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.BigIntegerField(db_index=True, verbose_name='受试者ID')),
                ('payment_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='关联支付ID')),
                ('event_type', models.CharField(choices=[('payment', '礼金奖励'), ('referral', '推荐奖励'), ('completion', '项目完成奖励'), ('compliance', '依从性奖励'), ('redemption', '积分兑换（扣除）'), ('adjustment', '人工调整'), ('expiry', '积分过期（扣除）'), ('import_backfill', 'NAS历史导入补录')], default='payment', max_length=30, verbose_name='事件类型')),
                ('delta', models.IntegerField(help_text='正=入账，负=出账', verbose_name='积分变动')),
                ('balance_after', models.IntegerField(default=0, help_text='快照余额，仅供展示参考；以聚合为准', verbose_name='变动后余额')),
                ('project_code', models.CharField(blank=True, default='', max_length=50, verbose_name='关联项目')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('is_voided', models.BooleanField(default=False, verbose_name='已作废')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='作废时间')),
                ('voided_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='作废原因')),
                ('operator_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('import_batch', models.CharField(blank=True, default='', max_length=30, verbose_name='导入批次')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '受试者积分台账',
                'db_table': 't_subject_points_ledger',
            },
        ),
        migrations.AddField(
            model_name='subjectpayment',
            name='bank_account_encrypted',
            field=models.TextField(blank=True, default='', help_text='AES Fernet 加密的银行卡号，使用 libs.field_encryption 解密', verbose_name='收款账号（加密）'),
        ),
        migrations.AddField(
            model_name='subjectpayment',
            name='bank_account_last4',
            field=models.CharField(blank=True, default='', help_text='明文后4位，用于展示和模糊匹配', max_length=4, verbose_name='收款账号后4位'),
        ),
        migrations.AddField(
            model_name='subjectpayment',
            name='nas_import_batch',
            field=models.CharField(blank=True, db_index=True, default='', help_text='格式 nas-YYYY-MM-DD', max_length=30, verbose_name='NAS导入批次'),
        ),
        migrations.AddField(
            model_name='subjectpayment',
            name='nas_paid_date',
            field=models.DateField(blank=True, help_text='从文件名解析的实际支付日期', null=True, verbose_name='NAS实际支付日期'),
        ),
        migrations.AddField(
            model_name='subjectpayment',
            name='platform',
            field=models.CharField(blank=True, db_index=True, default='', help_text='八羿/捷仕达/安徽创启/安徽斯长/宿钲/融辰/怀宁青枫', max_length=50, verbose_name='支付平台'),
        ),
        migrations.AddField(
            model_name='subjectpayment',
            name='points_awarded',
            field=models.IntegerField(default=0, help_text='本次支付奖励的积分（1元=1分）', verbose_name='奖励积分'),
        ),
        migrations.AddField(
            model_name='subjectpayment',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='项目代码'),
        ),
        migrations.AddIndex(
            model_name='subjectpayment',
            index=models.Index(fields=['project_code'], name='t_subject_p_project_001ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectpayment',
            index=models.Index(fields=['nas_import_batch'], name='t_subject_p_nas_imp_fdc2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectpointsledger',
            index=models.Index(fields=['subject_id', 'create_time'], name='t_subject_p_subject_a26b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectpointsledger',
            index=models.Index(fields=['event_type'], name='t_subject_p_event_t_06ef60_idx'),
        ),
    ]
