# Generated by Django 4.2.28 on 2026-03-27 08:05

from django.db import migrations, models


def _column_exists(connection, table: str, column: str) -> bool:
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute(
                """
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = %s
                  AND column_name = %s
                """,
                [table, column],
            )
            return cursor.fetchone() is not None
        if connection.vendor == 'sqlite':
            cursor.execute(f'PRAGMA table_info({table})')
            return any(row[1] == column for row in cursor.fetchall())
    return False


def _add_icf_and_consent_fields_if_missing(apps, schema_editor):
    """合并分支后 DB 可能已含部分列；仅补缺失列，避免 duplicate column。"""
    from django.db import models as dj_models
    from django.db import transaction

    IcfVersion = apps.get_model('subject', 'IcfVersion')
    SubjectConsent = apps.get_model('subject', 'SubjectConsent')
    icf_table = IcfVersion._meta.db_table
    consent_table = SubjectConsent._meta.db_table

    icf_fields = [
        (
            'display_order',
            dj_models.IntegerField(
                default=0, help_text='越小越靠前', verbose_name='签署顺序'
            ),
        ),
        (
            'mini_sign_rules',
            dj_models.JSONField(
                blank=True,
                default=dict,
                help_text='人脸/双签/测验/阅读时长/采集项/双签人员等，与协议级配置结构一致；未保存前由协议配置兜底',
                verbose_name='小程序签署规则',
            ),
        ),
        (
            'mini_sign_rules_saved',
            dj_models.BooleanField(
                default=False,
                help_text='至少完整保存过一次后为 True，用于列表标记与发布前校验',
                verbose_name='已保存小程序签署规则',
            ),
        ),
        (
            'node_title',
            dj_models.CharField(
                blank=True,
                default='',
                help_text='如：知情同意书、照片使用授权书',
                max_length=200,
                verbose_name='节点标题',
            ),
        ),
        (
            'required_reading_duration_seconds',
            dj_models.PositiveIntegerField(
                default=0,
                help_text='0 表示不校验，建议 10-600',
                verbose_name='要求阅读时长(秒)',
            ),
        ),
    ]
    consent_fields = [
        (
            'investigator_signed_at',
            dj_models.DateTimeField(
                blank=True, null=True, verbose_name='研究者见证签署时间'
            ),
        ),
        (
            'is_deleted',
            dj_models.BooleanField(
                db_index=True, default=False, verbose_name='已删除'
            ),
        ),
        (
            'staff_audit_status',
            dj_models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='pending_review=待审核(列表显示为已签署), approved=已通过审核, returned=退回重签中',
                max_length=24,
                verbose_name='工作人员审核状态',
            ),
        ),
    ]

    alias = schema_editor.connection.alias
    use_savepoint = schema_editor.connection.vendor == 'postgresql'

    def _add_field_safe(model, fld):
        if use_savepoint:
            sid = transaction.savepoint(using=alias)
            try:
                schema_editor.add_field(model, fld)
            except Exception:
                transaction.savepoint_rollback(sid, using=alias)
                raise
            else:
                transaction.savepoint_commit(sid, using=alias)
        else:
            schema_editor.add_field(model, fld)

    for name, field in icf_fields:
        field.set_attributes_from_name(name)
        if _column_exists(schema_editor.connection, icf_table, name):
            continue
        _add_field_safe(IcfVersion, field)

    for name, field in consent_fields:
        field.set_attributes_from_name(name)
        if _column_exists(schema_editor.connection, consent_table, name):
            continue
        _add_field_safe(SubjectConsent, field)


def _alter_subjectconsent_receipt_no_safe(apps, schema_editor):
    """去掉 unique、保留索引与 help_text；若目标索引已存在（合并分支重复）则跳过。

    PostgreSQL 在语句失败后会把整个事务标为 aborted；仅捕获异常而不回滚会导致后续
    SQL 报「current transaction is aborted」。因此用 savepoint 包住 alter_field，
    失败时 rollback to savepoint 再决定是否忽略。
    """
    from django.db import models as dj_models
    from django.db import transaction
    from django.db.utils import ProgrammingError

    SubjectConsent = apps.get_model('subject', 'SubjectConsent')
    old_field = SubjectConsent._meta.get_field('receipt_no')
    new_field = dj_models.CharField(
        blank=True,
        db_index=True,
        help_text='同受试者、同协议下多知情节点共用同一回执号',
        max_length=64,
        null=True,
        verbose_name='签署回执号',
    )
    new_field.set_attributes_from_name('receipt_no')
    new_field.model = SubjectConsent

    alias = schema_editor.connection.alias
    sid = transaction.savepoint(using=alias)
    try:
        schema_editor.alter_field(
            SubjectConsent, old_field, new_field, strict=False,
        )
    except ProgrammingError as e:
        transaction.savepoint_rollback(sid, using=alias)
        msg = str(e).lower()
        if 'already exists' in msg or 'duplicate' in msg:
            return
        raise
    else:
        transaction.savepoint_commit(sid, using=alias)


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0036_recruitment_ad_liaison_fee_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescreeningrecord',
            options={'verbose_name': '初筛记录'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _add_icf_and_consent_fields_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='icfversion',
                    name='display_order',
                    field=models.IntegerField(
                        default=0,
                        help_text='越小越靠前',
                        verbose_name='签署顺序',
                    ),
                ),
                migrations.AddField(
                    model_name='icfversion',
                    name='mini_sign_rules',
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='人脸/双签/测验/阅读时长/采集项/双签人员等，与协议级配置结构一致；未保存前由协议配置兜底',
                        verbose_name='小程序签署规则',
                    ),
                ),
                migrations.AddField(
                    model_name='icfversion',
                    name='mini_sign_rules_saved',
                    field=models.BooleanField(
                        default=False,
                        help_text='至少完整保存过一次后为 True，用于列表标记与发布前校验',
                        verbose_name='已保存小程序签署规则',
                    ),
                ),
                migrations.AddField(
                    model_name='icfversion',
                    name='node_title',
                    field=models.CharField(
                        blank=True,
                        default='',
                        help_text='如：知情同意书、照片使用授权书',
                        max_length=200,
                        verbose_name='节点标题',
                    ),
                ),
                migrations.AddField(
                    model_name='icfversion',
                    name='required_reading_duration_seconds',
                    field=models.PositiveIntegerField(
                        default=0,
                        help_text='0 表示不校验，建议 10-600',
                        verbose_name='要求阅读时长(秒)',
                    ),
                ),
                migrations.AddField(
                    model_name='subjectconsent',
                    name='investigator_signed_at',
                    field=models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='研究者见证签署时间',
                    ),
                ),
                migrations.AddField(
                    model_name='subjectconsent',
                    name='is_deleted',
                    field=models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name='已删除',
                    ),
                ),
                migrations.AddField(
                    model_name='subjectconsent',
                    name='staff_audit_status',
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        default='',
                        help_text='pending_review=待审核(列表显示为已签署), approved=已通过审核, returned=退回重签中',
                        max_length=24,
                        verbose_name='工作人员审核状态',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='prescreeningrecord',
            name='location',
            field=models.CharField(
                blank=True,
                default='',
                max_length=200,
                verbose_name='初筛地点',
            ),
        ),
        migrations.AlterField(
            model_name='prescreeningrecord',
            name='pre_screening_date',
            field=models.DateField(verbose_name='初筛日期'),
        ),
        migrations.AlterField(
            model_name='prescreeningrecord',
            name='pre_screening_no',
            field=models.CharField(
                db_index=True,
                max_length=50,
                unique=True,
                verbose_name='初筛编号',
            ),
        ),
        migrations.AlterField(
            model_name='prescreeningrecord',
            name='result',
            field=models.CharField(
                choices=[
                    ('pending', '待评估'),
                    ('pass', '通过'),
                    ('fail', '未通过'),
                    ('refer', '推荐其他项目'),
                ],
                db_index=True,
                default='pending',
                max_length=20,
                verbose_name='初筛结果',
            ),
        ),
        migrations.AlterField(
            model_name='prescreeningrecord',
            name='screener_id',
            field=models.IntegerField(
                blank=True,
                help_text='Account ID',
                null=True,
                verbose_name='初筛评估员ID',
            ),
        ),
        migrations.AlterField(
            model_name='prescreeningrecord',
            name='screening_appointment_id',
            field=models.IntegerField(
                blank=True,
                help_text='初筛通过后创建的正式筛选预约 SubjectAppointment ID',
                null=True,
                verbose_name='筛选预约ID',
            ),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='wei_visit_date',
            field=models.CharField(
                blank=True,
                default='',
                help_text='自由文本，如具体日期或「3月上旬」等说明',
                max_length=500,
                verbose_name='具体访视日期',
            ),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(
                choices=[
                    ('pre_screening', '初筛中'),
                    ('pre_screened', '初筛通过'),
                    ('screening', '筛选中'),
                    ('enrolled', '已入组'),
                    ('active', '进行中'),
                    ('completed', '已完成'),
                    ('withdrawn', '已退出'),
                    ('disqualified', '不符合'),
                ],
                db_index=True,
                default='screening',
                max_length=20,
                verbose_name='状态',
            ),
        ),
        migrations.AlterField(
            model_name='subjectappointment',
            name='visit_point',
            field=models.CharField(
                blank=True,
                default='',
                help_text='如 V0/V1/初筛/筛选/基线等',
                max_length=100,
                verbose_name='访视点',
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _alter_subjectconsent_receipt_no_safe,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='subjectconsent',
                    name='receipt_no',
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='同受试者、同协议下多知情节点共用同一回执号',
                        max_length=64,
                        null=True,
                        verbose_name='签署回执号',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='subjectregistration',
            name='status',
            field=models.CharField(
                choices=[
                    ('registered', '已报名'),
                    ('contacted', '已联系'),
                    ('pre_screening', '初筛中'),
                    ('pre_screened_pass', '初筛通过'),
                    ('pre_screened_fail', '初筛不通过'),
                    ('screening', '筛选中'),
                    ('screened_pass', '筛选通过'),
                    ('screened_fail', '筛选未通过'),
                    ('enrolled', '已入组'),
                    ('withdrawn', '已退出'),
                ],
                db_index=True,
                default='registered',
                max_length=20,
                verbose_name='状态',
            ),
        ),
    ]
