# Generated by Django 4.2.29 on 2026-03-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0033_subject_phone_active_uniq'),
        ('subject', '0037_nas_payment_extensions_and_points_ledger'),
    ]

    operations = [
    ]
