# Generated by Django 4.2.28 on 2026-03-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0034_merge_20260327_1435"),
        ("subject", "0037_recruitment_plan_wei_visit_date_text"),
    ]

    operations = []
