# Generated by Django 4.2.27 on 2026-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0038_subjectpayment_protocol_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectGlobalRegistry',
        ),
        migrations.RemoveField(
            model_name='subjectcheckin',
            name='missed_after_sc_rank',
        ),
        migrations.RemoveField(
            model_name='subjectcheckin',
            name='missed_call_at',
        ),
        migrations.RemoveField(
            model_name='subjectprojectsc',
            name='enrollment_status',
        ),
        migrations.AlterField(
            model_name='subjectprojectsc',
            name='rd_number',
            field=models.CharField(blank=True, default='', help_text='逻辑待定，暂空', max_length=20, verbose_name='RD号'),
        ),
        migrations.AlterField(
            model_name='subjectprojectsc',
            name='sc_number',
            field=models.CharField(blank=True, default='', help_text='如 001、002，签到后按项目内顺序分配', max_length=20, verbose_name='SC号'),
        ),
        migrations.DeleteModel(
            name='SubjectPseudonym',
        ),
    ]
