# Generated by Django 4.2.27 on 2026-03-25 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0039_delete_subjectglobalregistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectprojectsc',
            name='protocol_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='关联 t_protocol.id，由 link_protocol_to_project_sc 命令按 project_code=Protocol.code 填充', null=True, verbose_name='协议ID'),
        ),
        migrations.CreateModel(
            name='SubjectVisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_id', models.BigIntegerField(blank=True, db_index=True, help_text='关联 t_subject_questionnaire.id，可取原始全字段 JSONB', null=True, verbose_name='来源问卷ID')),
                ('visit_no', models.CharField(blank=True, default='', max_length=50, verbose_name='访客单号')),
                ('visit_date', models.DateField(verbose_name='来访日期')),
                ('visit_time', models.DateTimeField(blank=True, null=True, verbose_name='来访时间')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('project_code', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='来访事由/项目编号')),
                ('purpose', models.CharField(blank=True, default='', max_length=500, verbose_name='来访事由（原始）')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='进入门岗/房号')),
                ('liaison', models.CharField(blank=True, default='', max_length=100, verbose_name='被访人/联络员')),
                ('is_departed', models.BooleanField(default=False, verbose_name='已离开')),
                ('skin_type_obs', models.CharField(blank=True, default='', max_length=20, verbose_name='现场观察肤质')),
                ('source_batch', models.CharField(blank=True, default='', max_length=50, verbose_name='来源批次')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='subject.subject', verbose_name='受试者')),
            ],
            options={
                'verbose_name': '历史访客记录',
                'db_table': 't_subject_visit_record',
                'indexes': [models.Index(fields=['subject', 'visit_date'], name='t_subject_v_subject_2e0238_idx'), models.Index(fields=['project_code'], name='t_subject_v_project_85d5c0_idx'), models.Index(fields=['visit_date'], name='t_subject_v_visit_d_ecac3c_idx'), models.Index(fields=['questionnaire_id'], name='t_subject_v_questio_bd0242_idx')],
            },
        ),
    ]
