# Generated by Django 4.2.29 on 2026-03-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0038_merge_20260326_1134'),
        ('subject', '0040_add_visit_record_and_protocol_id'),
    ]

    operations = [
    ]
