export {
  ICF_PLACEHOLDER_TOKENS,
  applyIcfPlaceholders,
  applyIcfPlaceholdersWithSourceAnchors,
  buildIcfPlaceholderValues,
  buildIcfPlaceholderValuesFromConsentPreview,
  buildIcfSignatureRawHtmlPlaceholders,
  buildIcfSignatureRawHtmlFromRefs,
  extractSignatureImageRefsFromSummary,
  formatLocalDateYmd,
  icfTemplateHasSubjectSigPlaceholders,
  icfTemplateHasStaffSigPlaceholders,
  type BuildIcfPlaceholderValuesInput,
  type BuildIcfSignatureRawHtmlOptions,
  type IcfIdentityLike,
  type IcfMiniSignConfirmLike,
  type IcfPlaceholderToken,
} from './icfPlaceholders'
