# Generated by Django 4.2.27 on 2026-02-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('short_name', models.CharField(blank=True, default='', max_length=50, verbose_name='简称')),
                ('level', models.CharField(choices=[('strategic', '战略客户'), ('key', '重点客户'), ('normal', '普通客户'), ('potential', '潜在客户')], default='potential', max_length=20, verbose_name='客户等级')),
                ('industry', models.CharField(blank=True, default='', max_length=100, verbose_name='行业')),
                ('contact_name', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='地址')),
                ('total_projects', models.IntegerField(default=0, verbose_name='累计项目数')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='累计营收')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('feishu_project_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书项目ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '客户',
                'db_table': 't_client',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('assignee', models.CharField(blank=True, default='', max_length=100, verbose_name='处理人')),
                ('assignee_id', models.IntegerField(blank=True, null=True, verbose_name='处理人ID')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm.client', verbose_name='客户')),
            ],
            options={
                'verbose_name': '售后工单',
                'db_table': 't_ticket',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='商机名称')),
                ('stage', models.CharField(choices=[('lead', '线索'), ('contact', '接洽中'), ('proposal', '方案提交'), ('negotiation', '商务谈判'), ('won', '已成交'), ('lost', '已丢失')], default='lead', max_length=20, verbose_name='阶段')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='预估金额')),
                ('probability', models.IntegerField(default=0, verbose_name='成交概率(%)')),
                ('owner', models.CharField(max_length=100, verbose_name='负责人')),
                ('owner_id', models.IntegerField(blank=True, null=True, verbose_name='负责人ID')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='预计成交日')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('feishu_project_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书项目ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.client', verbose_name='客户')),
            ],
            options={
                'verbose_name': '商机',
                'db_table': 't_opportunity',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['level'], name='t_client_level_714707_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['industry'], name='t_client_industr_2d465f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='t_ticket_status_727110_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['client', 'status'], name='t_ticket_client__5cfb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='t_opportuni_stage_4d6a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['client', 'stage'], name='t_opportuni_client__b93a0a_idx'),
        ),
    ]
