# Generated by Django 4.2.27 on 2026-03-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_p0_p3_full_model_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='source_mail_signal_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='来源邮件信号ID'),
        ),
    ]
