# Generated by Django 4.2.29 on 2026-03-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_source_mail_signal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='demand_version',
            field=models.CharField(blank=True, default='', help_text='需求规格版本号，如 v1.0', max_length=50, verbose_name='需求版本'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('lead', '线索'), ('contact', '接洽中'), ('evaluation', '需求评估'), ('proposal', '方案提交'), ('negotiation', '商务谈判'), ('won', '已成交'), ('lost', '已丢失')], default='lead', max_length=20, verbose_name='阶段'),
        ),
    ]
