# Generated by Django 4.2.27 on 2026-02-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='协议编号')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('uploaded', '已上传'), ('parsing', '解析中'), ('parsed', '已解析'), ('active', '生效中'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='解析数据')),
                ('efficacy_type', models.CharField(blank=True, choices=[('superiority', '优效性'), ('non_inferiority', '非劣效性'), ('equivalence', '等效性'), ('bioequivalence', '生物等效性'), ('other', '其他')], default='', max_length=50, verbose_name='疗效类型')),
                ('sample_size', models.IntegerField(blank=True, null=True, verbose_name='样本量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '协议',
                'db_table': 't_protocol',
            },
        ),
        migrations.CreateModel(
            name='ProtocolParseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('uploaded', '已上传'), ('parsing', '解析中'), ('parsed', '已解析'), ('active', '生效中'), ('archived', '已归档')], default='parsing', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('parsed_result', models.JSONField(blank=True, null=True, verbose_name='解析结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_logs', to='protocol.protocol')),
            ],
            options={
                'verbose_name': '协议解析日志',
                'db_table': 't_protocol_parse_log',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='protocol',
            index=models.Index(fields=['status', 'create_time'], name='t_protocol_status_9e0ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='protocol',
            index=models.Index(fields=['title'], name='t_protocol_title_251b79_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolparselog',
            index=models.Index(fields=['protocol', 'create_time'], name='t_protocol__protoco_b95d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='protocolparselog',
            index=models.Index(fields=['status'], name='t_protocol__status_5b5dcf_idx'),
        ),
    ]
