# Generated by Django 4.2.27 on 2026-02-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='feishu_project_work_item_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='飞书项目工作项ID'),
        ),
    ]
