# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0003_add_created_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='feishu_project_work_item_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='飞书项目工作项ID(废弃)'),
        ),
    ]
