# Generated by Django 4.2.27 on 2026-02-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_alter_protocol_feishu_project_work_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='feishu_chat_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='S3-5 协议创建时自动创建', max_length=100, verbose_name='飞书项目群ID'),
        ),
    ]
