# Generated by Django 4.2.27 on 2026-02-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0005_protocol_feishu_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='claim_type',
            field=models.CharField(blank=True, default='', help_text='保湿/美白/抗衰/防晒/修护/控油等，逗号分隔多选', max_length=200, verbose_name='功效宣称'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='product_category',
            field=models.CharField(blank=True, default='', help_text='护肤/彩妆/防晒/洗护/口腔/其他', max_length=50, verbose_name='产品类别'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='regulatory_standard',
            field=models.CharField(blank=True, default='', help_text='如《化妆品功效宣称评价规范》', max_length=500, verbose_name='适用法规标准'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sponsor_id',
            field=models.IntegerField(blank=True, help_text='关联 CRM 中的客户 ID', null=True, verbose_name='委托方ID'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='team_members',
            field=models.JSONField(blank=True, default=list, help_text='JSON数组 [{id, name, role}]', null=True, verbose_name='项目团队成员'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='test_methods',
            field=models.JSONField(blank=True, default=list, help_text='JSON数组，如 ["Corneometer", "Tewameter", "VISIA-CR"]', null=True, verbose_name='测试方法列表'),
        ),
    ]
