# Generated by Django 4.2.27 on 2026-02-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0006_p2_recruitment_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='product_line_id',
            field=models.IntegerField(blank=True, help_text='关联 CRM t_client_product_line.id', null=True, verbose_name='产品线ID'),
        ),
    ]
