# Generated by Django 4.2.27 on 2026-03-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0009_protocol_cost_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolversion',
            name='parent_version',
        ),
        migrations.RemoveField(
            model_name='protocolversion',
            name='protocol',
        ),
        migrations.RenameIndex(
            model_name='protocolcostsnapshot',
            new_name='t_protocol__protoco_0b5958_idx',
            old_name='t_protocol__protocol_code_idx',
        ),
        migrations.RenameIndex(
            model_name='protocolcostsnapshot',
            new_name='t_protocol__compute_1ea47a_idx',
            old_name='t_protocol__computed_at_idx',
        ),
        migrations.DeleteModel(
            name='ProtocolVersion',
        ),
    ]
