# Generated by Django 4.2.28 on 2026-03-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0012_remove_generic_efficacy_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_mode', models.CharField(choices=[('global', '全局配置'), ('per_protocol', '按协议配置')], default='per_protocol', max_length=20, verbose_name='配置模式')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='全局配置内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知情全局配置',
                'db_table': 't_consent_global_config',
            },
        ),
        migrations.AlterField(
            model_name='protocol',
            name='consent_display_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='知情管理展示顺序'),
        ),
    ]
