# Generated by Django 4.2.28 on 2026-03-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0013_consent_global_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='WitnessStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, default='', max_length=10, verbose_name='性别')),
                ('id_card_no', models.CharField(blank=True, default='', max_length=24, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='工作邮箱')),
                ('priority', models.IntegerField(default=0, help_text='数值越大越靠前展示', verbose_name='优先')),
                ('face_order_id', models.CharField(blank=True, default='', max_length=128, verbose_name='人脸识别订单号')),
                ('face_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='人脸识别时间')),
                ('signature_file', models.CharField(blank=True, default='', max_length=500, verbose_name='签名文件路径')),
                ('signature_at', models.DateTimeField(blank=True, null=True, verbose_name='签名时间')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='身份已核验')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 't_witness_staff',
                'ordering': ['-priority', '-id'],
                'indexes': [models.Index(fields=['name'], name='t_witness_s_name_34d5d2_idx'), models.Index(fields=['is_deleted', 'update_time'], name='t_witness_s_is_dele_1a45fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='WitnessDualSignAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('protocol_id', models.IntegerField(db_index=True, verbose_name='协议ID')),
                ('icf_version_id', models.IntegerField(verbose_name='签署节点 ICF 版本 ID')),
                ('notify_email', models.EmailField(max_length=254, verbose_name='通知邮箱')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('witness_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='protocol.witnessstaff')),
            ],
            options={
                'db_table': 't_witness_dual_sign_auth_token',
                'indexes': [models.Index(fields=['token'], name='t_witness_d_token_d8c496_idx'), models.Index(fields=['expires_at'], name='t_witness_d_expires_cf185f_idx')],
            },
        ),
    ]
