# Generated by Django 4.2.29 on 2026-03-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0010_remove_protocolversion_parent_version_and_more'),
        ('protocol', '0020_alter_protocol_consent_config_account_id'),
    ]

    operations = [
    ]
