# Generated by Django 4.2.28 on 2026-03-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0020_alter_protocol_consent_config_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='consent_config_account_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='治理台 Account.id，须具备全局角色 qa（QA质量管理）；每项目至多一人', null=True, verbose_name='知情配置负责人账号ID'),
        ),
    ]
