# Generated by Django 4.2.29 on 2026-03-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0021_merge_protocol_leaf_nodes'),
        ('protocol', '0021_alter_consent_config_account_help_text_qa'),
    ]

    operations = [
    ]
