# Generated by Django 4.2.27 on 2026-02-18 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocol', '0006_p2_recruitment_tables'),
        ('crm', '0003_alter_client_feishu_project_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='评估标题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已驳回')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('overall_score', models.FloatField(blank=True, help_text='0-100综合评分', null=True, verbose_name='综合评分')),
                ('auto_check_result', models.JSONField(blank=True, default=dict, help_text='各维度自动检查结果汇总', verbose_name='自动检查汇总')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, help_text='Account ID', null=True, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_assessments', to='crm.opportunity', verbose_name='关联商机')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feasibility_assessments', to='protocol.protocol', verbose_name='关联协议')),
            ],
            options={
                'verbose_name': '可行性评估',
                'db_table': 't_feasibility_assessment',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('personnel', '人员'), ('equipment', '设备'), ('venue', '场地'), ('schedule', '排程'), ('compliance', '合规'), ('recruitment', '受试者招募')], max_length=20, verbose_name='评估维度')),
                ('score', models.IntegerField(default=0, help_text='0-100', verbose_name='评分')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('auto_check_passed', models.BooleanField(blank=True, null=True, verbose_name='自动检查通过')),
                ('auto_check_detail', models.JSONField(blank=True, default=dict, verbose_name='自动检查详情')),
                ('manual_notes', models.TextField(blank=True, default='', verbose_name='人工备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feasibility.feasibilityassessment', verbose_name='关联评估')),
            ],
            options={
                'verbose_name': '评估维度项',
                'db_table': 't_assessment_item',
                'ordering': ['assessment', 'dimension'],
            },
        ),
        migrations.AddIndex(
            model_name='feasibilityassessment',
            index=models.Index(fields=['opportunity', 'status'], name='t_feasibili_opportu_95e5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='feasibilityassessment',
            index=models.Index(fields=['status'], name='t_feasibili_status_44b68c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentitem',
            index=models.Index(fields=['assessment', 'dimension'], name='t_assessmen_assessm_3a7f45_idx'),
        ),
    ]
