# Generated by Django 4.2.27 on 2026-02-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100, verbose_name='飞书用户ID')),
                ('source_type', models.CharField(db_index=True, max_length=20, verbose_name='来源类型')),
                ('source_id', models.CharField(blank=True, default='', max_length=200, verbose_name='来源ID')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要/关键信息')),
                ('raw_content', models.TextField(blank=True, default='', verbose_name='原始内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '个人上下文',
                'db_table': 't_personal_context',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'source_type'], name='t_personal__user_id_c242ed_idx'), models.Index(fields=['user_id', 'created_at'], name='t_personal__user_id_91c21b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardOverviewCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(db_index=True, verbose_name='账号ID')),
                ('cache_type', models.CharField(choices=[('feishu_scan', '飞书信息扫描'), ('project_analysis', '项目客户分析'), ('hot_topics', '热点话题')], max_length=30, verbose_name='缓存类型')),
                ('content', models.JSONField(verbose_name='缓存内容')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工作台总览缓存',
                'db_table': 't_dashboard_overview_cache',
                'indexes': [models.Index(fields=['account_id', 'cache_type'], name='t_dashboard_account_57e89b_idx')],
                'unique_together': {('account_id', 'cache_type')},
            },
        ),
    ]
