# Generated by Django 4.2.27 on 2026-02-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(db_index=True, unique=True, verbose_name='账号ID')),
                ('open_id', models.CharField(db_index=True, max_length=100, verbose_name='飞书OpenID')),
                ('access_token', models.TextField(verbose_name='User Access Token')),
                ('refresh_token', models.TextField(blank=True, default='', verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(verbose_name='Access Token 过期时间')),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Refresh Token 过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '飞书用户Token',
                'db_table': 't_feishu_user_token',
                'indexes': [models.Index(fields=['account_id'], name='t_feishu_us_account_ecdc07_idx')],
            },
        ),
    ]
