# Generated by Django 4.2.27 on 2026-02-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0002_add_feishu_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSummaryDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(db_index=True, verbose_name='账号ID')),
                ('summary_type', models.CharField(default='daily', max_length=30, verbose_name='摘要类型')),
                ('context_snapshot_id', models.BigIntegerField(db_index=True, verbose_name='上下文快照ID')),
                ('content_markdown', models.TextField(blank=True, default='', verbose_name='摘要正文')),
                ('highlights', models.JSONField(blank=True, default=list, verbose_name='关键结论')),
                ('risk_points', models.JSONField(blank=True, default=list, verbose_name='风险点')),
                ('suggested_actions', models.JSONField(blank=True, default=list, verbose_name='建议动作')),
                ('model_provider', models.CharField(default='kimi', max_length=50, verbose_name='模型提供方')),
                ('model_id', models.CharField(default='moonshot-v1-32k', max_length=100, verbose_name='模型ID')),
                ('prompt_version', models.CharField(default='v1', max_length=20, verbose_name='提示词版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '子衿摘要草稿',
                'db_table': 't_assistant_summary_draft',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_id', 'summary_type'], name='t_assistant_account_1fb947_idx'), models.Index(fields=['context_snapshot_id'], name='t_assistant_context_4307a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssistantContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(db_index=True, verbose_name='账号ID')),
                ('time_range', models.CharField(default='7d', max_length=20, verbose_name='时间范围')),
                ('permission_snapshot', models.JSONField(default=dict, verbose_name='权限快照')),
                ('scope_snapshot', models.JSONField(default=dict, verbose_name='数据范围快照')),
                ('context_payload', models.JSONField(default=dict, verbose_name='上下文数据')),
                ('source_trace', models.JSONField(blank=True, default=list, verbose_name='来源追踪')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '子衿上下文快照',
                'db_table': 't_assistant_context_snapshot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_id', 'created_at'], name='t_assistant_account_ab508a_idx'), models.Index(fields=['account_id', 'expires_at'], name='t_assistant_account_7c49b9_idx')],
            },
        ),
    ]
