# Generated by Django 4.2.27 on 2026-02-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0003_assistantsummarydraft_assistantcontextsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(db_index=True, verbose_name='账号ID')),
                ('context_snapshot_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='上下文快照ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='动作类型')),
                ('title', models.CharField(default='', max_length=200, verbose_name='动作标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='动作说明')),
                ('action_payload', models.JSONField(default=dict, verbose_name='动作载荷')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=20, verbose_name='风险等级')),
                ('status', models.CharField(choices=[('suggested', '已建议'), ('pending_confirm', '待确认'), ('confirmed', '已确认'), ('rejected', '已拒绝'), ('executed', '已执行'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending_confirm', max_length=30, verbose_name='状态')),
                ('requires_confirmation', models.BooleanField(default=True, verbose_name='是否需要确认')),
                ('confirmed_by', models.IntegerField(blank=True, null=True, verbose_name='确认人ID')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '子衿动作计划',
                'db_table': 't_assistant_action_plan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_id', 'status'], name='t_assistant_account_6ee3f2_idx'), models.Index(fields=['account_id', 'risk_level'], name='t_assistant_account_8b8f23_idx'), models.Index(fields=['context_snapshot_id'], name='t_assistant_context_072fc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssistantActionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_plan_id', models.BigIntegerField(db_index=True, verbose_name='动作计划ID')),
                ('executor_id', models.IntegerField(db_index=True, verbose_name='执行人ID')),
                ('execution_result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('target_refs', models.JSONField(blank=True, default=list, verbose_name='目标引用')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '子衿动作执行记录',
                'db_table': 't_assistant_action_execution',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['action_plan_id'], name='t_assistant_action__ac43d5_idx'), models.Index(fields=['executor_id', 'started_at'], name='t_assistant_executo_0fb5dd_idx')],
            },
        ),
    ]
