# Generated by Django 4.2.27 on 2026-02-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0004_assistantactionplan_assistantactionexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantActionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_plan_id', models.BigIntegerField(db_index=True, verbose_name='动作计划ID')),
                ('account_id', models.IntegerField(db_index=True, verbose_name='反馈人ID')),
                ('adopted', models.BooleanField(default=False, verbose_name='是否采纳')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='评分(1-5)')),
                ('note', models.TextField(blank=True, default='', verbose_name='反馈说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '子衿动作反馈',
                'db_table': 't_assistant_action_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_plan_id'], name='t_assistant_action__09faac_idx'), models.Index(fields=['account_id', 'created_at'], name='t_assistant_account_90822b_idx')],
            },
        ),
    ]
