# Generated by Django 4.2.27 on 2026-03-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0008_domainworkerblueprint_evergreenwatchreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceMetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('route_applied', '路径应用'), ('route_success', '路径成功'), ('route_failed', '路径失败'), ('route_fallback', '路径回退'), ('manual_override', '人工覆盖'), ('approval_required', '需审批'), ('approval_timeout', '审批超时'), ('scope_gap', 'Scope 缺口'), ('context_gap', 'Context 缺口'), ('skill_success', '技能成功'), ('skill_failed', '技能失败'), ('runtime_success', '运行时成功'), ('runtime_failed', '运行时失败'), ('failed_step', '失败步骤')], db_index=True, max_length=32)),
                ('source', models.CharField(db_index=True, default='unknown', max_length=32)),
                ('dimension_1', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('dimension_2', models.CharField(blank=True, default='', max_length=120)),
                ('account_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('workstation', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '治理指标事件',
                'verbose_name_plural': '治理指标事件',
                'db_table': 't_governance_metric_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'source', 'created_at'], name='t_governanc_event_t_e21ea5_idx'), models.Index(fields=['created_at'], name='t_governanc_created_3b59b8_idx')],
            },
        ),
    ]
