# Generated by Django 4.2.27 on 2026-03-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0009_add_governance_metric_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(db_index=True, help_text='如：protocol-parser, crf-validator', max_length=100, unique=True, verbose_name='技能ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('executor', models.CharField(choices=[('script', '脚本'), ('service', '服务'), ('agent', '智能体')], default='script', help_text='script | service | agent', max_length=20, verbose_name='执行器类型')),
                ('agent_id', models.CharField(blank=True, default='', help_text='executor=agent 时必填', max_length=100, verbose_name='关联智能体ID')),
                ('script_path', models.CharField(blank=True, default='', help_text='相对 openclaw-skills 的路径，如 protocol-parser/scripts/parse_protocol.py', max_length=500, verbose_name='脚本路径')),
                ('service_path', models.CharField(blank=True, default='', help_text='Python 模块路径，executor=service 时使用', max_length=500, verbose_name='服务模块路径')),
                ('service_function', models.CharField(blank=True, default='execute', max_length=100, verbose_name='服务函数名')),
                ('timeout', models.IntegerField(default=60, verbose_name='超时秒数')),
                ('requires_llm', models.BooleanField(default=False, verbose_name='依赖大模型')),
                ('risk_level', models.CharField(default='medium', help_text='low | medium | high', max_length=20, verbose_name='风险等级')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='需审批后执行')),
                ('agent_tools', models.JSONField(blank=True, default=list, help_text='executor=agent 时，该 Agent 可调用的工具列表', verbose_name='Agent 可用工具列表')),
                ('fallback_script', models.CharField(blank=True, default='', help_text='Agent 失败时的备用脚本路径', max_length=500, verbose_name='降级脚本路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('bound_workstations', models.JSONField(blank=True, default=list, help_text='工作台 key 列表，如 ["secretary", "research"]', verbose_name='绑定工作台')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '技能定义',
                'db_table': 't_skill_definition',
                'indexes': [models.Index(fields=['skill_id'], name='t_skill_def_skill_i_d8ff58_idx'), models.Index(fields=['is_active'], name='t_skill_def_is_acti_fb24f8_idx')],
            },
        ),
    ]
