# Generated by Django 4.2.27 on 2026-03-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0010_add_skill_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAgentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_code', models.CharField(db_index=True, help_text='如：protocol, finance, quality', max_length=64, unique=True, verbose_name='领域代码')),
                ('agent_id', models.CharField(help_text='如：protocol-agent', max_length=100, verbose_name='智能体ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=120, verbose_name='展示名')),
                ('priority', models.IntegerField(default=0, help_text='数值越大越优先', verbose_name='优先级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '领域Agent映射',
                'db_table': 't_domain_agent_mapping',
                'ordering': ['-priority', 'domain_code'],
            },
        ),
        migrations.CreateModel(
            name='DomainSkillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_code', models.CharField(db_index=True, max_length=64, verbose_name='领域代码')),
                ('skill_id', models.CharField(max_length=100, verbose_name='技能ID')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '领域技能映射',
                'db_table': 't_domain_skill_mapping',
                'ordering': ['-priority', 'skill_id'],
            },
        ),
        migrations.CreateModel(
            name='KeywordDomainMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='关键词')),
                ('domain_code', models.CharField(db_index=True, max_length=64, verbose_name='领域代码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '关键词领域映射',
                'db_table': 't_keyword_domain_mapping',
                'indexes': [models.Index(fields=['keyword'], name='t_keyword_d_keyword_dfaaee_idx'), models.Index(fields=['domain_code'], name='t_keyword_d_domain__40c8e8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='keyworddomainmapping',
            constraint=models.UniqueConstraint(fields=('keyword',), name='uniq_keyword_domain'),
        ),
        migrations.AddIndex(
            model_name='domainskillmapping',
            index=models.Index(fields=['domain_code'], name='t_domain_sk_domain__d10081_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainskillmapping',
            constraint=models.UniqueConstraint(fields=('domain_code', 'skill_id'), name='uniq_domain_skill'),
        ),
        migrations.AddIndex(
            model_name='domainagentmapping',
            index=models.Index(fields=['domain_code'], name='t_domain_ag_domain__eb5966_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainagentmapping',
            constraint=models.UniqueConstraint(fields=('domain_code',), name='uniq_domain_agent'),
        ),
    ]
