# Generated by Django 4.2.27 on 2026-03-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0011_merge_20260314_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProactiveInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('trend_alert', '趋势预警'), ('client_periodic', '客户定期洞察'), ('project_recommendation', '项目推荐')], max_length=30, verbose_name='洞察类型')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('detail', models.JSONField(default=dict, verbose_name='详细内容')),
                ('client_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='关联客户ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, verbose_name='客户名称')),
                ('related_categories', models.JSONField(default=list, verbose_name='相关品类')),
                ('related_claim_types', models.JSONField(default=list, verbose_name='相关宣称类型')),
                ('trigger_source', models.CharField(blank=True, default='', max_length=50, verbose_name='触发来源')),
                ('scan_batch_id', models.CharField(blank=True, default='', max_length=64, verbose_name='扫描批次ID')),
                ('source_evidence_refs', models.JSONField(default=list, verbose_name='来源证据引用')),
                ('priority', models.CharField(default='medium', max_length=10, verbose_name='优先级')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='相关性评分')),
                ('urgency_score', models.FloatField(default=0.0, verbose_name='紧迫度评分')),
                ('impact_score', models.FloatField(default=0.0, verbose_name='影响力评分')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('approved', '已审核'), ('pushed', '已推送'), ('acted', '已行动'), ('dismissed', '已忽略'), ('expired', '已过期')], default='draft', max_length=20, verbose_name='状态')),
                ('reviewed_by', models.IntegerField(blank=True, null=True, verbose_name='审核人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('pushed_at', models.DateTimeField(blank=True, null=True, verbose_name='推送时间')),
                ('push_channel', models.CharField(blank=True, default='', max_length=30, verbose_name='推送渠道')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('action_taken', models.TextField(blank=True, default='', verbose_name='采取的行动')),
                ('action_result', models.CharField(blank=True, default='', max_length=30, verbose_name='行动结果')),
                ('linked_opportunity_id', models.IntegerField(blank=True, null=True, verbose_name='关联商机ID')),
                ('feedback_score', models.IntegerField(blank=True, null=True, verbose_name='反馈评分(1-5)')),
                ('feedback_note', models.TextField(blank=True, default='', verbose_name='反馈说明')),
                ('governance_level', models.CharField(default='internal_draft', max_length=30, verbose_name='治理等级')),
                ('auto_send_to_client', models.BooleanField(default=False, verbose_name='是否可自动对客')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '主动洞察',
                'db_table': 't_proactive_insight',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProactiveScanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('scan_type', models.CharField(max_length=30, verbose_name='扫描类型')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('biweekly', '双周'), ('monthly', '每月')], default='weekly', max_length=20, verbose_name='频率')),
                ('cron_expression', models.CharField(blank=True, default='', max_length=50, verbose_name='CRON 表达式')),
                ('target_client_ids', models.JSONField(default=list, verbose_name='目标客户ID列表')),
                ('target_categories', models.JSONField(default=list, verbose_name='目标品类')),
                ('target_regions', models.JSONField(default=list, verbose_name='目标法规区域')),
                ('data_sources', models.JSONField(default=list, verbose_name='数据源白名单')),
                ('ai_provider', models.CharField(default='kimi', max_length=20, verbose_name='AI 通道')),
                ('ai_model', models.CharField(default='moonshot-v1-32k', max_length=50, verbose_name='模型')),
                ('prompt_template_key', models.CharField(blank=True, default='', max_length=50, verbose_name='提示词模板')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次运行时间')),
                ('last_run_result', models.JSONField(default=dict, verbose_name='上次运行结果')),
                ('run_count', models.IntegerField(default=0, verbose_name='累计运行次数')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '主动扫描配置',
                'db_table': 't_proactive_scan_config',
            },
        ),
        migrations.CreateModel(
            name='ProactiveScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=64, unique=True, verbose_name='批次ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('partial', '部分完成')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('sources_scanned', models.JSONField(default=list, verbose_name='已扫描数据源')),
                ('raw_signals_count', models.IntegerField(default=0, verbose_name='原始信号数')),
                ('insights_generated', models.IntegerField(default=0, verbose_name='生成洞察数')),
                ('insights_deduplicated', models.IntegerField(default=0, verbose_name='去重后洞察数')),
                ('error_log', models.TextField(blank=True, default='', verbose_name='错误日志')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '扫描运行记录',
                'db_table': 't_proactive_scan_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='feishuusertoken',
            new_name='t_feishu_us_issuer__3c35d8_idx',
            old_name='t_feishu_us_issuer__idx',
        ),
        migrations.RenameIndex(
            model_name='feishuusertoken',
            new_name='t_feishu_us_require_6ecbda_idx',
            old_name='t_feishu_us_requires_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignalattachment',
            new_name='t_mail_sign_mail_si_153d80_idx',
            old_name='t_mail_sign_mail_si_f84b44_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignalattachment',
            new_name='t_mail_sign_extract_38c604_idx',
            old_name='t_mail_sign_extract_950673_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignalevent',
            new_name='t_mail_sign_account_881a6c_idx',
            old_name='t_mail_sign_account_917def_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignalevent',
            new_name='t_mail_sign_sender__6ab230_idx',
            old_name='t_mail_sign_sender__8a0e87_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignalevent',
            new_name='t_mail_sign_thread__80786f_idx',
            old_name='t_mail_sign_thread__92155b_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignalevent',
            new_name='t_mail_sign_status_a82a31_idx',
            old_name='t_mail_sign_status_69dff9_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignalevent',
            new_name='t_mail_sign_mail_si_aff971_idx',
            old_name='t_mail_sign_mail_si_8cad3b_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignallink',
            new_name='t_mail_sign_mail_si_07df9d_idx',
            old_name='t_mail_sign_mail_si_1e4db9_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignallink',
            new_name='t_mail_sign_link_ty_f37198_idx',
            old_name='t_mail_sign_link_ty_58a827_idx',
        ),
        migrations.RenameIndex(
            model_name='mailsignallink',
            new_name='t_mail_sign_confirm_5d1144_idx',
            old_name='t_mail_sign_confirm_aafdb9_idx',
        ),
        migrations.RenameIndex(
            model_name='mailthreadsnapshot',
            new_name='t_mail_thre_thread__6381d3_idx',
            old_name='t_mail_thre_thread__d49233_idx',
        ),
        migrations.RenameIndex(
            model_name='mailthreadsnapshot',
            new_name='t_mail_thre_primary_8dbd01_idx',
            old_name='t_mail_thre_primary_5b8431_idx',
        ),
        migrations.RenameIndex(
            model_name='mailthreadsnapshot',
            new_name='t_mail_thre_primary_b4b4ff_idx',
            old_name='t_mail_thre_primary_884db1_idx',
        ),
        migrations.AddField(
            model_name='proactivescanrun',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='secretary.proactivescanconfig'),
        ),
        migrations.AddIndex(
            model_name='proactiveinsight',
            index=models.Index(fields=['insight_type', 'status'], name='t_proactive_insight_259108_idx'),
        ),
        migrations.AddIndex(
            model_name='proactiveinsight',
            index=models.Index(fields=['client_id', '-created_at'], name='t_proactive_client__5a47b0_idx'),
        ),
        migrations.AddIndex(
            model_name='proactiveinsight',
            index=models.Index(fields=['scan_batch_id'], name='t_proactive_scan_ba_c05c55_idx'),
        ),
        migrations.AddIndex(
            model_name='proactiveinsight',
            index=models.Index(fields=['priority', '-created_at'], name='t_proactive_priorit_6e1ac7_idx'),
        ),
    ]
