# Generated by Django 4.2.27 on 2026-03-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0011_add_orchestration_config_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkstationBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstation_key', models.CharField(db_index=True, help_text='如：secretary, research, finance', max_length=64, unique=True, verbose_name='工作台 key')),
                ('display_name', models.CharField(blank=True, default='', max_length=120, verbose_name='展示名称')),
                ('agent_ids', models.JSONField(blank=True, default=list, help_text='如：["general-assistant", "knowledge-agent"]', verbose_name='绑定的 Agent ID 列表')),
                ('skill_ids', models.JSONField(blank=True, default=list, help_text='如：["protocol-parser", "knowledge-hybrid-search"]', verbose_name='绑定的技能 ID 列表')),
                ('quick_actions', models.JSONField(blank=True, default=list, help_text='[{"id":"daily-brief","label":"今日简报","skill":"secretary-orchestrator","script":"generate_brief","icon":"newspaper"}]', verbose_name='快捷操作')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工作台绑定',
                'db_table': 't_workstation_binding',
                'indexes': [models.Index(fields=['workstation_key'], name='t_workstati_worksta_783f88_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workstationbinding',
            constraint=models.UniqueConstraint(fields=('workstation_key',), name='uniq_workstation_binding'),
        ),
    ]
