# Generated by Django 4.2.27 on 2026-03-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0012_add_workstation_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerRoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(db_index=True, help_text='如：customer_demand_analyst, solution_designer', max_length=80, unique=True, verbose_name='岗位编码')),
                ('role_name', models.CharField(max_length=120, verbose_name='岗位名称')),
                ('role_cluster', models.CharField(blank=True, default='', help_text='如：客户与需求簇、项目准备与启动簇', max_length=80, verbose_name='岗位簇')),
                ('service_targets', models.JSONField(blank=True, default=list, help_text='主要服务的内部或外部角色，如 ["销售","客户经理"]', verbose_name='服务对象')),
                ('core_scenarios', models.JSONField(blank=True, default=list, help_text='主要发生的业务场景', verbose_name='核心场景')),
                ('input_contract', models.JSONField(blank=True, default=list, help_text='岗位依赖的数据、文档、事件', verbose_name='关键输入')),
                ('output_contract', models.JSONField(blank=True, default=list, help_text='岗位交付的内容、清单、建议、状态或证据', verbose_name='关键输出')),
                ('automation_level', models.CharField(blank=True, choices=[('L1', 'L1 信息辅助'), ('L2', 'L2 助理执行'), ('L3', 'L3 受控执行'), ('L4', 'L4 人工确认')], default='', help_text='L1-L4', max_length=10, verbose_name='自动化等级')),
                ('human_confirmation_points', models.JSONField(blank=True, default=list, help_text='哪些动作必须人类确认', verbose_name='必须人工确认事项')),
                ('kpi_metrics', models.JSONField(blank=True, default=list, help_text='如何评估岗位成效', verbose_name='价值指标')),
                ('mapped_agent_ids', models.JSONField(blank=True, default=list, help_text='承担该岗位能力的 agent_id 列表', verbose_name='映射 Agent')),
                ('mapped_skill_ids', models.JSONField(blank=True, default=list, help_text='该岗位可调用的 skill_id 列表', verbose_name='映射技能')),
                ('workstation_scope', models.JSONField(blank=True, default=list, help_text='该岗位可见/可用的工作台 key 列表，空表示全部', verbose_name='工作台范围')),
                ('baseline_manual_minutes', models.IntegerField(blank=True, help_text='用于价值看板估算，单次执行约等于替代多少分钟人工', null=True, verbose_name='人工替代基准（分钟/次）')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '数字员工岗位定义',
                'verbose_name_plural': '数字员工岗位定义',
                'db_table': 't_worker_role_definition',
                'ordering': ['role_cluster', 'role_code'],
            },
        ),
        migrations.AddField(
            model_name='skilldefinition',
            name='baseline_manual_minutes',
            field=models.IntegerField(blank=True, help_text='价值看板用：单次成功执行约替代多少分钟人工，空则用全局默认', null=True, verbose_name='人工替代基准（分钟/次）'),
        ),
        migrations.AlterField(
            model_name='skilldefinition',
            name='risk_level',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', help_text='low | medium | high', max_length=20, verbose_name='风险等级'),
        ),
    ]
