# Generated by Django 4.2.27 on 2026-03-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0021_merge_20260315_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuMigrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text="如 'full-20260317' / 'daily-20260318'", max_length=100, unique=True, verbose_name='批次ID')),
                ('batch_type', models.CharField(choices=[('full_history', '全量历史迁移'), ('daily_incremental', '每日增量采集'), ('weekly_deep', '每周深度扫描'), ('monthly_reconcile', '每月全量对账'), ('manual', '手动触发')], default='manual', max_length=30, verbose_name='批次类型')),
                ('sources', models.JSONField(default=list, help_text="['mail', 'im', ...] 或 ['__ALL__']", verbose_name='目标数据源')),
                ('target_users', models.JSONField(default=list, help_text="['__ALL__'] 或指定 open_id 列表", verbose_name='目标用户')),
                ('status', models.CharField(choices=[('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('paused', '已暂停')], default='running', max_length=20, verbose_name='状态')),
                ('total_users', models.IntegerField(default=0, verbose_name='目标用户数')),
                ('completed_users', models.IntegerField(default=0, verbose_name='已完成用户数')),
                ('total_items', models.IntegerField(default=0, verbose_name='已获取总条数')),
                ('total_deposited', models.IntegerField(default=0, verbose_name='已入库总条数')),
                ('total_errors', models.IntegerField(default=0, verbose_name='错误总数')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='{"mail": {"fetched": 100, "deposited": 80}, ...}', verbose_name='分源统计')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '飞书迁移批次',
                'db_table': 't_feishu_migration_batch',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FeishuMigrationCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_open_id', models.CharField(help_text="飞书 open_id；'__TENANT__' 表示租户维度（Wiki/审批/通讯录等）", max_length=100, verbose_name='飞书 OpenID')),
                ('user_name', models.CharField(blank=True, default='', max_length=100, verbose_name='用户名')),
                ('user_email', models.CharField(blank=True, default='', max_length=200, verbose_name='邮箱')),
                ('source_type', models.CharField(help_text='mail/im/calendar/task/approval/doc/wiki/sheet/slide/drive_file/group_msg/contact', max_length=30, verbose_name='数据源类型')),
                ('status', models.CharField(choices=[('pending', '待迁移'), ('running', '迁移中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('auth_mode', models.CharField(blank=True, default='', help_text='user_token / tenant_token / degraded（tenant fallback） / skipped', max_length=20, verbose_name='认证模式')),
                ('page_token', models.CharField(blank=True, default='', help_text='最后成功的 page_token，下次采集从此继续', max_length=500, verbose_name='分页游标')),
                ('last_item_id', models.CharField(blank=True, default='', help_text='最后成功处理的消息/邮件/文档 ID', max_length=200, verbose_name='最后成功项ID')),
                ('last_timestamp', models.DateTimeField(blank=True, help_text='最后成功项的时间戳，增量采集的起点', null=True, verbose_name='最后成功时间戳')),
                ('oldest_timestamp', models.DateTimeField(blank=True, help_text='已追溯到的最早记录时间戳，null 表示尚未完成全量', null=True, verbose_name='已追溯最早时间')),
                ('total_fetched', models.IntegerField(default=0, verbose_name='已获取数量')),
                ('total_deposited', models.IntegerField(default=0, verbose_name='已入库数量')),
                ('total_skipped', models.IntegerField(default=0, verbose_name='已跳过数量')),
                ('total_errors', models.IntegerField(default=0, verbose_name='错误数量')),
                ('error_log', models.TextField(blank=True, default='', verbose_name='最近错误详情')),
                ('config', models.JSONField(blank=True, default=dict, help_text='{"page_size": 100, "batch_id": "full-20260317", ...}', verbose_name='采集参数快照')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '飞书迁移断点',
                'db_table': 't_feishu_migration_checkpoint',
            },
        ),
        migrations.AddField(
            model_name='personalcontext',
            name='batch_id',
            field=models.CharField(blank=True, default='', help_text='关联 FeishuMigrationBatch.batch_id，如 full-20260317', max_length=100, verbose_name='采集批次ID'),
        ),
        migrations.AddField(
            model_name='personalcontext',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='raw_content 的 SHA-1 哈希，用于采集层去重', max_length=64, verbose_name='内容哈希'),
        ),
        migrations.AddField(
            model_name='personalcontext',
            name='file_path',
            field=models.CharField(blank=True, default='', help_text='原始文件在 /data/media/feishu_files/ 下的相对路径', max_length=500, verbose_name='本地文件路径'),
        ),
        migrations.AddField(
            model_name='personalcontext',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='文件大小(bytes)'),
        ),
        migrations.AddIndex(
            model_name='personalcontext',
            index=models.Index(fields=['content_hash'], name='t_personal__content_4bca9c_idx'),
        ),
        migrations.AddIndex(
            model_name='personalcontext',
            index=models.Index(fields=['batch_id'], name='t_personal__batch_i_77f1df_idx'),
        ),
        migrations.AddIndex(
            model_name='feishumigrationcheckpoint',
            index=models.Index(fields=['status'], name='t_feishu_mi_status_b78571_idx'),
        ),
        migrations.AddIndex(
            model_name='feishumigrationcheckpoint',
            index=models.Index(fields=['source_type', 'status'], name='t_feishu_mi_source__6ed7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='feishumigrationcheckpoint',
            index=models.Index(fields=['auth_mode'], name='t_feishu_mi_auth_mo_c7c098_idx'),
        ),
        migrations.AddIndex(
            model_name='feishumigrationcheckpoint',
            index=models.Index(fields=['updated_at'], name='t_feishu_mi_updated_54046e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feishumigrationcheckpoint',
            unique_together={('user_open_id', 'source_type')},
        ),
        migrations.AddIndex(
            model_name='feishumigrationbatch',
            index=models.Index(fields=['batch_type', 'status'], name='t_feishu_mi_batch_t_26c3af_idx'),
        ),
        migrations.AddIndex(
            model_name='feishumigrationbatch',
            index=models.Index(fields=['started_at'], name='t_feishu_mi_started_0ef7c6_idx'),
        ),
    ]
