# Generated by Django 4.2.27 on 2026-03-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0013_eval_improvements_business_value_entities'),
        ('secretary', '0014_feishu_migration_models'),
    ]

    operations = [
    ]
