# Generated by Django 4.2.27 on 2026-03-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0015_merge_20260317_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handoff_id', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='转交 ID')),
                ('from_agent_id', models.CharField(db_index=True, max_length=80, verbose_name='来源 Agent')),
                ('to_agent_id', models.CharField(db_index=True, max_length=80, verbose_name='目标 Agent')),
                ('handoff_type', models.CharField(choices=[('delegate', '委派'), ('escalate', '升级'), ('transfer', '转交')], max_length=20, verbose_name='转交类型')),
                ('reason', models.TextField(verbose_name='转交原因')),
                ('context_snapshot', models.JSONField(default=dict, help_text='转交时的完整上下文：原始需求、已完成步骤、待处理项', verbose_name='上下文快照')),
                ('task_id', models.CharField(blank=True, default='', max_length=80, verbose_name='关联任务 ID')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='处理结果')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接收'), ('completed', '已完成'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent 转交记录',
                'verbose_name_plural': 'Agent 转交记录',
                'db_table': 't_handoff_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='workermemoryrecord',
            new_name='t_worker_me_is_core_9f76a6_idx',
            old_name='idx_memory_core_worker',
        ),
        migrations.RenameIndex(
            model_name='workermemoryrecord',
            new_name='t_worker_me_visibil_1922dd_idx',
            old_name='idx_memory_visibility_task',
        ),
        migrations.RenameIndex(
            model_name='workermemoryrecord',
            new_name='t_worker_me_compres_b040c8_idx',
            old_name='idx_memory_compressed_worker',
        ),
        migrations.AddField(
            model_name='skilldefinition',
            name='idempotent',
            field=models.BooleanField(default=False, help_text='幂等技能在同一 business_run 中不重复执行', verbose_name='幂等性'),
        ),
        migrations.AddField(
            model_name='skilldefinition',
            name='output_contract',
            field=models.JSONField(blank=True, default=dict, help_text='约定输出格式，如 {"fields":["demand_summary","gap_list"],"format":"json"}', verbose_name='输出契约'),
        ),
        migrations.AddField(
            model_name='skilldefinition',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='执行前必须已完成的技能 ID 列表', verbose_name='前置依赖技能'),
        ),
    ]
