# Generated by Django 4.2.29 on 2026-03-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0009_feishu_usertoken_issuer_preflight'),
        ('secretary', '0020_skill_template'),
    ]

    operations = [
    ]
