# Generated by Django 4.2.29 on 2026-03-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0022_feishu_user_token_lifecycle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feishuusertoken',
            new_name='t_feishu_us_refresh_5f7c6e_idx',
            old_name='t_feishu_user_token_refresh_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='feishuusertoken',
            new_name='t_feishu_us_last_us_317442_idx',
            old_name='t_feishu_user_token_last_used_idx',
        ),
        migrations.AddField(
            model_name='feishumigrationcheckpoint',
            name='running_since',
            field=models.DateTimeField(blank=True, help_text='P4-A: 精确追踪每次 running 开始时间，比 updated_at 更可靠', null=True, verbose_name='本次 running 开始时间'),
        ),
        migrations.AlterField(
            model_name='feishuusertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='首次入库时间'),
        ),
        migrations.AddIndex(
            model_name='feishuusertoken',
            index=models.Index(fields=['status'], name='t_feishu_us_status_5d9904_idx'),
        ),
    ]
