# Generated by Django 4.2.27 on 2026-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0025_feishu_user_token_scope'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feishuusertoken',
            name='t_feishu_us_refresh_5f7c6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='feishuusertoken',
            name='t_feishu_us_last_us_317442_idx',
        ),
        migrations.RemoveIndex(
            model_name='feishuusertoken',
            name='t_feishu_us_status_5d9904_idx',
        ),
        migrations.RemoveField(
            model_name='feishumigrationcheckpoint',
            name='running_since',
        ),
        migrations.AlterField(
            model_name='feishuusertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
