# Generated by Django 4.2.27 on 2026-02-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_plans', to='protocol.protocol')),
            ],
            options={
                'verbose_name': '访视计划',
                'db_table': 't_visit_plan',
            },
        ),
        migrations.CreateModel(
            name='VisitNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('baseline_day', models.IntegerField(default=0, help_text='相对于基线的时间（天）', verbose_name='基线天数')),
                ('window_before', models.IntegerField(default=0, verbose_name='窗口期前（天）')),
                ('window_after', models.IntegerField(default=0, verbose_name='窗口期后（天）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='visit.visitplan')),
            ],
            options={
                'verbose_name': '访视节点',
                'db_table': 't_visit_node',
            },
        ),
        migrations.CreateModel(
            name='VisitActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('examination', '检查'), ('laboratory', '实验室检查'), ('questionnaire', '问卷'), ('medication', '用药'), ('adverse_event', '不良事件'), ('other', '其他')], default='other', max_length=50, verbose_name='活动类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='visit.visitnode')),
            ],
            options={
                'verbose_name': '访视活动',
                'db_table': 't_visit_activity',
            },
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['protocol', 'status'], name='t_visit_pla_protoco_860021_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['status', 'create_time'], name='t_visit_pla_status_6678f4_idx'),
        ),
        migrations.AddIndex(
            model_name='visitnode',
            index=models.Index(fields=['plan', 'baseline_day'], name='t_visit_nod_plan_id_51c85c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitnode',
            index=models.Index(fields=['plan', 'status'], name='t_visit_nod_plan_id_b2a790_idx'),
        ),
        migrations.AddIndex(
            model_name='visitactivity',
            index=models.Index(fields=['node', 'activity_type'], name='t_visit_act_node_id_f3b229_idx'),
        ),
    ]
