# Generated by Django 4.2.27 on 2026-02-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitnode',
            name='feishu_event_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='飞书日历事件ID'),
        ),
    ]
