# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_resourcedemand'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resourcedemand',
            new_name='t_resource__visit_p_0803a3_idx',
            old_name='visit_rd_plan_status_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcedemand',
            new_name='t_resource__status_c50d07_idx',
            old_name='visit_rd_status_idx',
        ),
    ]
