# Generated by Django 4.2.27 on 2026-02-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0006_environmentincident_cleaningrecord'),
        ('hr', '0002_staff_email_staff_employee_no_staff_feishu_open_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_role', models.CharField(choices=[('instrument_operator', '仪器操作员'), ('medical_evaluator', '医生评估员'), ('crc', '临床协调员(CRC)'), ('equipment_support', '仪器保障人员'), ('facility_support', '场地保障人员'), ('sample_manager', '样品管理员')], default='instrument_operator', max_length=30, verbose_name='实验室角色')),
                ('lab_role_secondary', models.CharField(blank=True, choices=[('instrument_operator', '仪器操作员'), ('medical_evaluator', '医生评估员'), ('crc', '临床协调员(CRC)'), ('equipment_support', '仪器保障人员'), ('facility_support', '场地保障人员'), ('sample_manager', '样品管理员')], default='', max_length=30, verbose_name='辅助角色')),
                ('employment_type', models.CharField(choices=[('full_time', '内部全职'), ('part_time', '内部兼职'), ('external', '外部兼职')], default='full_time', max_length=20, verbose_name='雇佣类型')),
                ('competency_level', models.CharField(choices=[('L1', '学习期'), ('L2', '见习期'), ('L3', '独立期'), ('L4', '专家期'), ('L5', '带教导师')], default='L1', max_length=5, verbose_name='能力等级')),
                ('competency_level_updated_at', models.DateField(blank=True, null=True, verbose_name='等级更新日期')),
                ('available_weekdays', models.JSONField(default=list, help_text='[1,2,3,4,5] 表示周一至周五', verbose_name='可排班工作日')),
                ('max_daily_hours', models.IntegerField(default=8, verbose_name='每日最大工时')),
                ('max_weekly_hours', models.IntegerField(default=40, verbose_name='每周最大工时')),
                ('unavailable_dates', models.JSONField(default=list, help_text='["2026-03-01","2026-03-02"]', verbose_name='不可用日期')),
                ('mentor_id', models.IntegerField(blank=True, null=True, verbose_name='导师Staff ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在岗')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '实验室人员档案',
                'db_table': 't_lab_staff_profile',
            },
        ),
        migrations.CreateModel(
            name='MethodQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('learning', '学习中'), ('probation', '见习'), ('independent', '独立'), ('mentor', '带教')], default='learning', max_length=20, verbose_name='资质等级')),
                ('qualified_date', models.DateField(blank=True, null=True, verbose_name='认定日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='资质有效期')),
                ('training_id', models.IntegerField(blank=True, null=True, verbose_name='关联培训记录ID')),
                ('assessment_id', models.IntegerField(blank=True, null=True, verbose_name='关联评估记录ID')),
                ('total_executions', models.IntegerField(default=0, verbose_name='累计执行次数')),
                ('last_execution_date', models.DateField(blank=True, null=True, verbose_name='最近执行日期')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '方法资质',
                'db_table': 't_method_qualification',
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('cert_expiring', '资质即将到期'), ('cert_expired', '资质已过期'), ('single_point', '单点依赖'), ('overload', '工时超负荷'), ('skill_decay', '能力萎缩'), ('quality_decline', '质量下滑'), ('capacity_gap', '产能缺口'), ('training_overdue', '培训逾期')], max_length=30, verbose_name='风险类型')),
                ('level', models.CharField(choices=[('red', '红色（立即行动）'), ('yellow', '黄色（一周内处理）'), ('blue', '蓝色（月度关注）')], max_length=10, verbose_name='风险等级')),
                ('title', models.CharField(max_length=300, verbose_name='预警标题')),
                ('description', models.TextField(verbose_name='预警详情')),
                ('status', models.CharField(choices=[('open', '待处理'), ('acknowledged', '已确认'), ('mitigating', '处理中'), ('resolved', '已解决'), ('dismissed', '已忽略')], default='open', max_length=20, verbose_name='状态')),
                ('related_object_type', models.CharField(blank=True, default='', help_text='如 certificate/method/workorder', max_length=50, verbose_name='关联对象类型')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('action_taken', models.TextField(blank=True, default='', verbose_name='处理措施')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('resolved_by_id', models.IntegerField(blank=True, null=True, verbose_name='解决人ID')),
                ('feishu_message_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书消息ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '风险预警',
                'db_table': 't_risk_alert',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='该周周一日期', verbose_name='周起始日期')),
                ('week_end_date', models.DateField(verbose_name='周结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('confirmed', '已确认')], default='draft', max_length=20, verbose_name='状态')),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='创建人ID')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '排班计划',
                'db_table': 't_shift_schedule',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='排班日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('planned_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='计划工时')),
                ('project_name', models.CharField(blank=True, default='', max_length=200, verbose_name='关联项目')),
                ('protocol_id', models.IntegerField(blank=True, null=True, verbose_name='关联协议ID')),
                ('tasks_description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('confirm_status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('rejected', '已拒绝'), ('swapped', '已换班')], default='pending', max_length=20, verbose_name='确认状态')),
                ('reject_reason', models.CharField(blank=True, default='', max_length=300, verbose_name='拒绝原因')),
                ('feishu_calendar_event_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书日历事件ID')),
                ('feishu_task_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书确认任务ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='lab_personnel.shiftschedule', verbose_name='所属排班计划')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_slots', to='hr.staff', verbose_name='排班人员')),
            ],
            options={
                'verbose_name': '排班时间槽',
                'db_table': 't_shift_slot',
                'ordering': ['shift_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='周起始日期')),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='总工时')),
                ('workorder_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='工单工时')),
                ('training_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='培训工时')),
                ('other_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='其他工时')),
                ('available_hours', models.DecimalField(decimal_places=1, default=40, max_digits=5, verbose_name='可用工时')),
                ('utilization_rate', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='利用率(%)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_time_summaries', to='hr.staff', verbose_name='人员')),
            ],
            options={
                'verbose_name': '工时汇总',
                'db_table': 't_work_time_summary',
            },
        ),
        migrations.CreateModel(
            name='WorkTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='工作日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('actual_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='实际工时')),
                ('source', models.CharField(choices=[('workorder', '工单执行'), ('training', '培训'), ('maintenance', '设备维护'), ('admin', '行政事务'), ('manual', '手动录入')], default='manual', max_length=20, verbose_name='来源')),
                ('source_id', models.IntegerField(blank=True, help_text='关联的工单/培训/维护ID', null=True, verbose_name='来源ID')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_time_logs', to='hr.staff', verbose_name='人员')),
            ],
            options={
                'verbose_name': '工时记录',
                'db_table': 't_work_time_log',
                'ordering': ['-work_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StaffCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('gcp', 'GCP证书'), ('medical_license', '医师执业证'), ('nursing_license', '护士执业证'), ('professional_skill', '专业技能证书'), ('safety_training', '安全培训证书'), ('other', '其他')], max_length=30, verbose_name='证书类型')),
                ('cert_name', models.CharField(max_length=200, verbose_name='证书名称')),
                ('cert_number', models.CharField(blank=True, default='', max_length=100, verbose_name='证书编号')),
                ('issuing_authority', models.CharField(blank=True, default='', max_length=200, verbose_name='发证机关')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('expiry_date', models.DateField(blank=True, help_text='null 表示永久有效', null=True, verbose_name='到期日期')),
                ('status', models.CharField(choices=[('valid', '有效'), ('expiring_90', '90天内到期'), ('expiring_30', '30天内到期'), ('expiring_7', '7天内到期'), ('expired', '已过期'), ('revoked', '已撤销')], default='valid', max_length=20, verbose_name='状态')),
                ('file_url', models.CharField(blank=True, default='', max_length=500, verbose_name='证书文件URL')),
                ('is_locked', models.BooleanField(default=False, help_text='过期自动锁定，禁止持证人接受工单', verbose_name='是否已锁定')),
                ('feishu_reminder_task_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书续期提醒任务ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='hr.staff', verbose_name='人员')),
            ],
            options={
                'verbose_name': '资质证书',
                'db_table': 't_staff_certificate',
                'ordering': ['staff', '-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='换班原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approved_by_id', models.IntegerField(blank=True, null=True, verbose_name='审批人ID')),
                ('feishu_approval_instance_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书审批实例ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('original_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_from', to='lab_personnel.shiftslot', verbose_name='原排班')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_initiated', to='hr.staff', verbose_name='申请人')),
                ('target_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='hr.staff', verbose_name='接替人')),
            ],
            options={
                'verbose_name': '换班申请',
                'db_table': 't_shift_swap_request',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='shiftschedule',
            index=models.Index(fields=['week_start_date', 'status'], name='t_shift_sch_week_st_262de3_idx'),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='related_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='hr.staff', verbose_name='关联人员'),
        ),
        migrations.AddField(
            model_name='methodqualification',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_personnel', to='resource.detectionmethodtemplate', verbose_name='检测方法'),
        ),
        migrations.AddField(
            model_name='methodqualification',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_qualifications', to='hr.staff', verbose_name='人员'),
        ),
        migrations.AddField(
            model_name='labstaffprofile',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_profile', to='hr.staff', verbose_name='关联人员'),
        ),
        migrations.AddIndex(
            model_name='worktimesummary',
            index=models.Index(fields=['week_start_date'], name='t_work_time_week_st_d73ec2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worktimesummary',
            unique_together={('staff', 'week_start_date')},
        ),
        migrations.AddIndex(
            model_name='worktimelog',
            index=models.Index(fields=['staff', 'work_date'], name='t_work_time_staff_i_78d500_idx'),
        ),
        migrations.AddIndex(
            model_name='worktimelog',
            index=models.Index(fields=['source'], name='t_work_time_source_17f6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcertificate',
            index=models.Index(fields=['staff', 'cert_type', 'status'], name='t_staff_cer_staff_i_1e1240_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcertificate',
            index=models.Index(fields=['status'], name='t_staff_cer_status_73b6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='staffcertificate',
            index=models.Index(fields=['expiry_date'], name='t_staff_cer_expiry__3dd915_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftslot',
            index=models.Index(fields=['schedule', 'shift_date'], name='t_shift_slo_schedul_bf76cb_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftslot',
            index=models.Index(fields=['staff', 'shift_date'], name='t_shift_slo_staff_i_4836e6_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftslot',
            index=models.Index(fields=['confirm_status'], name='t_shift_slo_confirm_4e87db_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['level', 'status'], name='t_risk_aler_level_7b5465_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['risk_type', 'status'], name='t_risk_aler_risk_ty_0027eb_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['related_staff'], name='t_risk_aler_related_fe3c43_idx'),
        ),
        migrations.AddIndex(
            model_name='methodqualification',
            index=models.Index(fields=['staff', 'level'], name='t_method_qu_staff_i_e29928_idx'),
        ),
        migrations.AddIndex(
            model_name='methodqualification',
            index=models.Index(fields=['method', 'level'], name='t_method_qu_method__917f5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='methodqualification',
            unique_together={('staff', 'method')},
        ),
        migrations.AddIndex(
            model_name='labstaffprofile',
            index=models.Index(fields=['lab_role', 'is_active'], name='t_lab_staff_lab_rol_d54297_idx'),
        ),
        migrations.AddIndex(
            model_name='labstaffprofile',
            index=models.Index(fields=['employment_type'], name='t_lab_staff_employm_7aa85b_idx'),
        ),
        migrations.AddIndex(
            model_name='labstaffprofile',
            index=models.Index(fields=['competency_level'], name='t_lab_staff_compete_9764c8_idx'),
        ),
    ]
