# Generated by Django 4.2.27 on 2026-02-20 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_staff_email_staff_employee_no_staff_feishu_open_id_and_more'),
        ('lab_personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labstaffprofile',
            name='backup_staff_ids',
            field=models.JSONField(blank=True, default=list, help_text='JSON 数组 [staff_id1, staff_id2]，用于排班替补预案', verbose_name='替补人员ID列表'),
        ),
        migrations.CreateModel(
            name='FieldChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='如 LabStaffProfile / StaffCertificate', max_length=100, verbose_name='模型名称')),
                ('record_id', models.IntegerField(verbose_name='记录ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='变更前值')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='变更后值')),
                ('changed_by_id', models.IntegerField(blank=True, null=True, verbose_name='操作人ID')),
                ('changed_by_name', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='变更原因')),
            ],
            options={
                'verbose_name': '字段变更日志',
                'db_table': 't_field_change_log',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='t_field_cha_model_n_076a41_idx'), models.Index(fields=['changed_at'], name='t_field_cha_changed_d33c62_idx'), models.Index(fields=['changed_by_id'], name='t_field_cha_changed_5da2e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DelegationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.IntegerField(db_index=True, verbose_name='关联协议ID')),
                ('protocol_name', models.CharField(blank=True, default='', max_length=300, verbose_name='协议名称')),
                ('scope', models.TextField(help_text='详细描述 PI 授权该人员执行的具体职责和操作', verbose_name='授权范围')),
                ('delegation_date', models.DateField(verbose_name='授权日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='授权到期日')),
                ('pi_name', models.CharField(max_length=100, verbose_name='PI 姓名')),
                ('pi_staff_id', models.IntegerField(blank=True, null=True, verbose_name='PI Staff ID')),
                ('pi_signature_id', models.IntegerField(blank=True, help_text='关联 signature.ElectronicSignature.id', null=True, verbose_name='PI 电子签名ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('revoked_at', models.DateField(blank=True, null=True, verbose_name='撤销日期')),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='撤销原因')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_logs', to='hr.staff', verbose_name='被授权人员')),
            ],
            options={
                'verbose_name': 'PI授权日志',
                'db_table': 't_delegation_log',
                'ordering': ['-delegation_date'],
                'indexes': [models.Index(fields=['staff', 'protocol_id'], name='t_delegatio_staff_i_8948f1_idx'), models.Index(fields=['protocol_id', 'is_active'], name='t_delegatio_protoco_7cb45c_idx'), models.Index(fields=['delegation_date'], name='t_delegatio_delegat_a43a00_idx')],
            },
        ),
    ]
