# Generated by Django 4.2.28 on 2026-03-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDistributionExecution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_order_id', models.BigIntegerField()),
                ('related_project_no', models.CharField(max_length=100)),
                ('subject_rd', models.CharField(max_length=100)),
                ('subject_initials', models.CharField(max_length=50)),
                ('screening_no', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('operator_id', models.BigIntegerField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=50, null=True)),
                ('exception_description', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product_distribution_execution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductDistributionOperation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('execution_id', models.BigIntegerField()),
                ('stage', models.CharField(max_length=50)),
                ('execution_cycle', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('bottle_sequence', models.CharField(blank=True, max_length=50, null=True)),
                ('is_selected', models.IntegerField(default=1)),
                ('product_distribution', models.IntegerField(default=0)),
                ('product_inspection', models.IntegerField(default=0)),
                ('product_recovery', models.IntegerField(default=0)),
                ('product_site_use', models.IntegerField(default=0)),
                ('distribution_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('inspection_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('recovery_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('diary_distribution', models.IntegerField(default=0)),
                ('diary_inspection', models.IntegerField(default=0)),
                ('diary_recovery', models.IntegerField(default=0)),
                ('usage_diagram_file_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product_distribution_operation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductDistributionWorkOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_order_no', models.CharField(max_length=100, unique=True)),
                ('project_no', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('visit_count', models.IntegerField(default=0)),
                ('researcher', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_method', models.TextField(blank=True, null=True)),
                ('usage_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('project_requirements', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product_distribution_work_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductSampleRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=50)),
                ('operation_date', models.DateField()),
                ('related_project_no', models.CharField(max_length=100)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('researcher', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(max_length=255)),
                ('operator_id', models.BigIntegerField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product_sample_request',
                'managed': True,
            },
        ),
    ]
