# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdistributionexecution',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productdistributionoperation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productdistributionworkorder',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productsamplerequest',
            options={'managed': False},
        ),
    ]
