# Generated by Django 4.2.27 on 2026-02-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduleplan',
            new_name='t_schedule__visit_p_67d916_idx',
            old_name='sched_plan_vp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleplan',
            new_name='t_schedule__status_70f466_idx',
            old_name='sched_plan_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleslot',
            new_name='t_schedule__schedul_8dff2b_idx',
            old_name='sched_slot_plan_date_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleslot',
            new_name='t_schedule__visit_n_052df0_idx',
            old_name='sched_slot_node_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleslot',
            new_name='t_schedule__assigne_b2e92d_idx',
            old_name='sched_slot_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleslot',
            new_name='t_schedule__status_977212_idx',
            old_name='sched_slot_status_idx',
        ),
    ]
