# Generated by Django 4.2.27 on 2026-02-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_rename_sched_plan_vp_status_idx_t_schedule__visit_p_67d916_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('fsi', '首例入组'), ('lsi', '末例入组'), ('lso', '末例出组'), ('dbl', '数据库锁定'), ('report', '报告提交'), ('custom', '自定义')], max_length=20, verbose_name='里程碑类型')),
                ('name', models.CharField(max_length=200, verbose_name='里程碑名称')),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='已达成')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('feishu_calendar_event_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书日历事件ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('schedule_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='scheduling.scheduleplan', verbose_name='排程计划')),
            ],
            options={
                'verbose_name': '排程里程碑',
                'db_table': 't_schedule_milestone',
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['schedule_plan', 'milestone_type'], name='t_schedule__schedul_42d14c_idx')],
            },
        ),
    ]
