# Generated by Django 4.2.28 on 2026-03-24 03:10
#
# 使用标准 ORM 迁移建表（替代 SeparateDatabaseAndState+RunPython）。
# 原 RunPython 在 SeparateDatabaseAndState 内拿到的 from_state 不含本次 state 中的新模型，
# 导致 apps.get_model 失败；且内含仅 PostgreSQL 的 introspection，SQLite 无法执行。

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_schedulemilestone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionOrderUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=list,
                        help_text="表头+行列表或行对象列表",
                        verbose_name="解析行数据",
                    ),
                ),
                (
                    "created_by_id",
                    models.IntegerField(blank=True, null=True, verbose_name="上传人ID"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "执行订单上传",
                "db_table": "t_execution_order_upload",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="LabScheduleUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="来源文件名",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=list,
                        help_text="已弃用，数据存 LabScheduleRow 表",
                        verbose_name="解析行数据",
                    ),
                ),
                (
                    "created_by_id",
                    models.IntegerField(blank=True, null=True, verbose_name="上传人ID"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "实验室排期上传",
                "db_table": "t_lab_schedule_upload",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="TimelineUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=list,
                        help_text="TimelineRow[] 序列化",
                        verbose_name="时间线行数据",
                    ),
                ),
                (
                    "created_by_id",
                    models.IntegerField(blank=True, null=True, verbose_name="上传人ID"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "时间线上传",
                "db_table": "t_timeline_upload",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="TimelineSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supervisor",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="督导"
                    ),
                ),
                (
                    "research_group",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="研究组"
                    ),
                ),
                (
                    "t0_date",
                    models.DateField(blank=True, null=True, verbose_name="T0 基准日期"),
                ),
                (
                    "split_days",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="拆分天数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("timeline_published", "时间线已发布"),
                            ("completed", "排程完成"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                (
                    "admin_published",
                    models.BooleanField(default=False, verbose_name="行政排程已发布"),
                ),
                (
                    "eval_published",
                    models.BooleanField(default=False, verbose_name="评估排程已发布"),
                ),
                (
                    "tech_published",
                    models.BooleanField(default=False, verbose_name="技术排程已发布"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="排程数据"),
                ),
                (
                    "created_by_id",
                    models.IntegerField(blank=True, null=True, verbose_name="创建人ID"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "execution_order_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_schedule",
                        to="scheduling.executionorderupload",
                        verbose_name="执行订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "排程核心",
                "db_table": "t_timeline_schedule",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="TimelinePublishedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("online", "线上"), ("offline", "线下")],
                        db_index=True,
                        default="online",
                        max_length=16,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(default=dict, verbose_name="时间线行快照"),
                ),
                (
                    "created_by_id",
                    models.IntegerField(blank=True, null=True, verbose_name="发布人ID"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "timeline_schedule",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_plan",
                        to="scheduling.timelineschedule",
                        verbose_name="排程核心",
                    ),
                ),
            ],
            options={
                "verbose_name": "时间线发布记录",
                "db_table": "t_timeline_published_plan",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="LabScheduleRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="组别"
                    ),
                ),
                (
                    "equipment_code",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="设备编号"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="设备"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="日期"
                    ),
                ),
                (
                    "protocol_code",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="项目编号"
                    ),
                ),
                (
                    "sample_size",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="样本量"
                    ),
                ),
                (
                    "person_role",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="人员/岗位"
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="房间"
                    ),
                ),
                (
                    "day_group",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="组别"
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="scheduling.labscheduleupload",
                        verbose_name="所属上传",
                    ),
                ),
            ],
            options={
                "verbose_name": "实验室排期行",
                "db_table": "t_lab_schedule_row",
                "ordering": ["upload", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="timelineschedule",
            constraint=models.UniqueConstraint(
                fields=("execution_order_upload",),
                name="unique_timeline_schedule_per_order_v2",
            ),
        ),
        migrations.AddIndex(
            model_name="labschedulerow",
            index=models.Index(
                fields=["upload"], name="t_lab_sched_upload__286593_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labschedulerow",
            index=models.Index(
                fields=["person_role"], name="t_lab_sched_person__77f3f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labschedulerow",
            index=models.Index(
                fields=["equipment"], name="t_lab_sched_equipme_f0d2fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labschedulerow",
            index=models.Index(fields=["date"], name="t_lab_sched_date_b2cdf3_idx"),
        ),
    ]
