# Generated by Django 4.2.28 on 2026-03-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_timeline_execution_lab_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineschedule',
            name='post_publish_edit_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='排程全部完成后，允许撤回再编辑合计次数上限为 3', verbose_name='发布后撤回再编辑已用次数'),
        ),
    ]
