"""
针对专业知识组合评估中最薄弱的专题包，补权威锚点而非盲目补量。

当前重点：
1. booking_policy                -> 缺法规锚点
2. pkg_cro_quality_operations    -> 权威密度过低
3. pkg_instrument_methods        -> 缺标准/合规边界
"""
from django.core.management.base import BaseCommand

from apps.knowledge.ingestion_pipeline import RawKnowledgeInput, run_pipeline
from apps.knowledge.models import KnowledgeEntry


SEEDS = [
    RawKnowledgeInput(
        title='招募预约合规锚点：知情同意必须先于任何研究程序',
        content=(
            '权威依据：ICH E6(R2)/(R3) GCP、伦理审查通则。\n'
            '核心规则：任何涉及研究目的解释、筛选性采集、测试前准备的流程，都必须建立在有效知情同意之后。'
            '未签署 ICF 前，只能进行公开信息层面的咨询，不得采集研究数据、安排研究程序、执行筛选测量。\n'
            '数字人适用边界：预约助手在未确认 ICF 状态前，只能提供流程说明与候选时段，不得推进到受试者筛选或研究访视。'
        ),
        summary='招募与预约专题的首要法规锚点：知情同意先于筛选和研究程序。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='booking-policy:regulation:icf-before-procedure',
        namespace='cnkis',
        tags=['招募预约', '知情同意', '法规锚点'],
        package_id='booking_policy',
        canonical_topic='招募与预约',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='招募预约方法锚点：筛选窗口、改约窗口与失访判定的最小字段集',
        content=(
            '用于预约与筛选衔接的最小字段必须结构化记录：候选人唯一标识、联系授权状态、ICF 状态、筛选适用条件、预约时间窗、'
            '改约次数、爽约原因、是否触发人工复核。\n'
            '若缺少上述字段，数字人将无法稳定完成排期重算、失访识别与审计追溯。\n'
            '建议把预约动作、筛选动作、人工确认动作拆成三段留痕，而不是用单条备注覆盖。'
        ),
        summary='招募预约专题的方法学锚点：窗口规则和衔接字段必须结构化。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='booking-policy:method:minimum-booking-fields',
        namespace='cnkis',
        tags=['招募预约', '方法锚点', '结构化字段'],
        package_id='booking_policy',
        canonical_topic='招募与预约',
        facet='study_design',
    ),
    RawKnowledgeInput(
        title='CRO质量运营法规锚点：偏差、CAPA、审计追踪必须同链闭环',
        content=(
            '权威依据：ICH E6 GCP、21 CFR Part 11、质量管理通行要求。\n'
            '核心规则：偏差记录、根因分析、CAPA、关闭确认和审计追踪不能割裂保存；'
            '任何修改都必须可追溯到责任人、时间、原因与审批动作。\n'
            '数字人适用边界：若发现只有纠正动作没有根因、只有根因没有关闭验证、或电子记录无法溯源，则必须判为质量闭环不完整。'
        ),
        summary='CRO 质量与运营实务专题的法规锚点：偏差/CAPA/审计追踪必须同链闭环。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='cro-quality:regulation:deviation-capa-audit-chain',
        namespace='cnkis',
        tags=['CRO质量', 'CAPA', '审计追踪', '法规锚点'],
        package_id='pkg_cro_quality_operations',
        canonical_topic='CRO 质量与运营实务',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='CRO质量运营方法锚点：偏差分级、升级条件与关闭验证的统一判定框架',
        content=(
            '建议把偏差按受试者安全、数据完整性、法规合规、客户交付影响四个维度统一评分。\n'
            '至少定义：一般偏差、重大偏差、关键偏差三个等级；并明确各等级的升级时限、审批角色、CAPA 完成时限、关闭验证要求。\n'
            '数字人工作要求：不能只识别“有偏差”，必须同时输出分级、升级节点、关闭证据缺口。'
        ),
        summary='CRO 质量与运营实务专题的方法锚点：偏差分级与关闭验证框架。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='cro-quality:method:deviation-severity-framework',
        namespace='cnkis',
        tags=['CRO质量', '偏差分级', '方法锚点'],
        package_id='pkg_cro_quality_operations',
        canonical_topic='CRO 质量与运营实务',
        facet='sop_risks',
    ),
    RawKnowledgeInput(
        title='CRO质量运营交付锚点：偏差/CAPA对外报告最小披露模板',
        content=(
            '对客户或审计方输出偏差/CAPA 摘要时，最小模板应同时包含：事件描述、发现时间、影响范围、受试者/数据影响、临时遏制措施、'
            '根因、CAPA、预计关闭时间、关闭验证方式。\n'
            '禁止仅用“已处理”“已沟通”之类模糊表述替代闭环要素。'
        ),
        summary='CRO 质量与运营实务专题的交付锚点：偏差/CAPA 对外报告模板。',
        entry_type='proposal_template',
        source_type='specialist_anchor_seed',
        source_key='cro-quality:template:deviation-capa-client-summary',
        namespace='cnkis',
        tags=['CRO质量', '交付模板', 'CAPA'],
        package_id='pkg_cro_quality_operations',
        canonical_topic='CRO 质量与运营实务',
        facet='reporting_templates',
    ),
    RawKnowledgeInput(
        title='仪器与检测方法法规锚点：研究关键仪器必须具备校准、状态标识与可追溯记录',
        content=(
            '适用于功效评价关键仪器的最低合规要求包括：设备唯一标识、状态标识（可用/停用/待校准）、校准周期、维修记录、使用记录、'
            '异常停机与恢复记录。\n'
            '若校准过期、状态不明或维修后未验证恢复，则数据不能直接进入正式分析。'
        ),
        summary='仪器与检测方法专题的法规锚点：关键仪器必须满足校准和追溯要求。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='instrument-methods:regulation:calibration-traceability',
        namespace='cnkis',
        tags=['仪器方法', '校准', '法规锚点'],
        package_id='pkg_instrument_methods',
        canonical_topic='仪器与检测方法',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='仪器与检测方法标准锚点：方法选择必须匹配宣称、终点与测量环境',
        content=(
            '方法选择不能只看“能测”，必须同时匹配：功效宣称类型、主要终点、受试者条件、测量环境控制和统计分析方式。\n'
            '例如保湿研究至少要区分 Corneometer 的水合终点与 Tewameter 的屏障终点；'
            '防晒研究则必须区分 ISO 24444、ISO 24442 与 ISO 24443 的不同适用边界。'
        ),
        summary='仪器与检测方法专题的标准锚点：方法选择要匹配宣称、终点和环境。',
        entry_type='methodology',
        source_type='specialist_anchor_seed',
        source_key='instrument-methods:methodology:claim-endpoint-environment-fit',
        namespace='cnkis',
        tags=['仪器方法', '标准锚点', '方法选择'],
        package_id='pkg_instrument_methods',
        canonical_topic='仪器与检测方法',
        facet='instrument_methods',
    ),
    RawKnowledgeInput(
        title='仪器与检测方法执行锚点：测量前环境适应、重复测量与异常读数处置 SOP',
        content=(
            '数字人执行时必须强制检查三类关键前提：\n'
            '1. 环境适应是否达到要求（温度/湿度/静置时间）；\n'
            '2. 每个测量位点是否完成规定次数的重复测量；\n'
            '3. 异常读数是否重测并保留原因。\n'
            '缺失上述任一条件时，输出必须带“数据可靠性不足”的标记。'
        ),
        summary='仪器与检测方法专题的执行锚点：环境适应、重复测量和异常重测必须固化。',
        entry_type='sop',
        source_type='specialist_anchor_seed',
        source_key='instrument-methods:sop:environment-repeat-outlier',
        namespace='cnkis',
        tags=['仪器方法', '执行锚点', 'SOP'],
        package_id='pkg_instrument_methods',
        canonical_topic='仪器与检测方法',
        facet='sop_risks',
    ),
]

SEEDS.extend([
    RawKnowledgeInput(
        title='不良反应分级锚点：一般不良反应、严重不良反应与可疑严重风险的区分',
        content='数字人必须区分一般不良反应、严重不良反应和需要立即升级的可疑严重风险。最小判断维度包括：是否危及生命、是否导致住院/医学干预、是否造成持续功能损害、是否需要紧急停用产品或终止研究程序。若信息不足，默认进入人工医学复核而不是自行降级。',
        summary='不良反应专题的核心权威锚点：事件分级与升级判定。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='adverse-event:method:severity-triage',
        namespace='cnkis',
        tags=['不良反应', '分级', '医学升级'],
        package_id='adverse_event',
        canonical_topic='不良反应',
        facet='sop_risks',
    ),
    RawKnowledgeInput(
        title='招募预约法规锚点：改约、爽约与再次联系必须留痕并遵守联系授权',
        content='招募与预约动作不仅是运营动作，也是合规动作。数字人必须先判断候选人是否授予联系授权，再决定是否允许短信提醒、电话回访或再次邀约；每次改约、爽约和复联都应记录时间、原因、渠道、责任人和是否触发人工跟进。',
        summary='招募与预约专题的法规锚点：联系授权与改约留痕。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='booking-policy:regulation:contact-consent-and-reschedule-log',
        namespace='cnkis',
        tags=['招募预约', '联系授权', '留痕'],
        package_id='booking_policy',
        canonical_topic='招募与预约',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='招募预约法规锚点：筛选失败与不适配人群不得被重复误触达',
        content='对于已明确不符合入组标准、明确拒绝参与或要求停止联系的人群，数字人必须打上不可继续触达标记。任何后续自动推荐、自动提醒或重新预约都必须以最新授权和状态为准，否则属于隐私与运营越界。',
        summary='招募与预约专题的法规锚点：筛选失败与拒绝参与人群的触达边界。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='booking-policy:regulation:do-not-recontact-boundary',
        namespace='cnkis',
        tags=['招募预约', '触达边界', '拒绝参与'],
        package_id='booking_policy',
        canonical_topic='招募与预约',
        facet='claim_boundary',
    ),
    RawKnowledgeInput(
        title='招募预约方法锚点：候选人优先级排序必须同时考虑匹配度、时效性和资源占用',
        content='预约排序不能只按先来后到。数字人至少要同时评估：协议匹配度、时间窗紧迫性、受试者历史爽约风险、关键设备/访视资源占用和人工复核优先级；否则会导致高价值名额被低质量候选人占用。',
        summary='招募与预约专题的方法锚点：预约排序的多因素决策框架。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='booking-policy:method:priority-ranking-framework',
        namespace='cnkis',
        tags=['招募预约', '排序', '方法锚点'],
        package_id='booking_policy',
        canonical_topic='招募与预约',
        facet='key_metrics',
    ),
    RawKnowledgeInput(
        title='招募预约方法锚点：失访风险前置识别与补位策略',
        content='数字人需要在正式爽约前识别失访风险信号，例如多次改约、沟通中断、关键准备材料缺失、交通距离异常、历史低依从记录等。对高风险对象应提前触发补位名单和人工确认，而不是等到窗口到期后再被动补救。',
        summary='招募与预约专题的方法锚点：失访风险前置识别。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='booking-policy:method:no-show-risk-preemption',
        namespace='cnkis',
        tags=['招募预约', '失访风险', '补位策略'],
        package_id='booking_policy',
        canonical_topic='招募与预约',
        facet='sop_risks',
    ),
    RawKnowledgeInput(
        title='功效宣称法规锚点：宣称结论必须同时说明证据类型、适用边界与限制条件',
        content='数字人在输出功效宣称结论时，不得只给“有效/显著改善”的单句结论。合规表达至少要交代证据类型、研究对象、时间窗、主要终点和不适用边界，防止将局部结果泛化成普遍承诺。',
        summary='功效宣称专题的法规锚点：宣称结论必须带证据和边界。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='efficacy-claims:regulation:evidence-boundary-limit',
        namespace='cnkis',
        tags=['功效宣称', '结论边界', '法规锚点'],
        package_id='efficacy_claims',
        canonical_topic='功效宣称',
        facet='claim_boundary',
    ),
    RawKnowledgeInput(
        title='功效宣称法规锚点：消费者感受不能直接替代人体功效评价终点',
        content='消费者感受、主观偏好和满意度可以作为辅助支持，但不能直接替代人体功效评价、仪器终点或法规要求的核心证据。数字人必须能识别“体验型宣称”和“功效型宣称”的证据等级差异。',
        summary='功效宣称专题的法规锚点：体验证据与功效证据不可混用。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='efficacy-claims:regulation:consumer-feel-not-efficacy-endpoint',
        namespace='cnkis',
        tags=['功效宣称', '消费者测试', '证据等级'],
        package_id='efficacy_claims',
        canonical_topic='功效宣称',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='功效宣称方法锚点：宣称类型与终点映射表必须先于研究设计',
        content='数字人不能先有产品卖点、后临时拼接终点。研究设计前必须先建立“宣称类型 -> 主要终点 -> 次要终点 -> 证据形式 -> 允许结论语气”的映射表，避免设计和宣称脱节。',
        summary='功效宣称专题的方法锚点：宣称与终点映射先行。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='efficacy-claims:method:claim-endpoint-mapping-table',
        namespace='cnkis',
        tags=['功效宣称', '终点映射', '研究设计'],
        package_id='efficacy_claims',
        canonical_topic='功效宣称',
        facet='study_design',
    ),
    RawKnowledgeInput(
        title='功效宣称方法锚点：结论措辞强度必须与效应量和一致性相匹配',
        content='同样是统计学显著，数字人不能一律输出“显著改善”。建议按照效应量、重复时间点一致性、主次终点一致性和样本稳定性控制结论强度，区分“可支持”“较强支持”“强支持”等级。',
        summary='功效宣称专题的方法锚点：结论强度分级。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='efficacy-claims:method:claim-strength-grading',
        namespace='cnkis',
        tags=['功效宣称', '效应量', '结论强度'],
        package_id='efficacy_claims',
        canonical_topic='功效宣称',
        facet='key_metrics',
    ),
    RawKnowledgeInput(
        title='功效宣称方法锚点：跨市场宣称迁移必须重新校验监管语义',
        content='同一产品在不同监管区的证据可复用程度有限。数字人必须识别中国、欧盟、美国在功效表述、人体试验要求、标签话术和宣传边界上的语义差异，不能把海外合规话术直接平移到中国市场。',
        summary='功效宣称专题的方法锚点：跨市场宣称迁移需要监管语义校验。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='efficacy-claims:method:cross-market-semantic-check',
        namespace='cnkis',
        tags=['功效宣称', '跨市场', '监管语义'],
        package_id='efficacy_claims',
        canonical_topic='功效宣称',
        facet='faq_misconceptions',
    ),
    RawKnowledgeInput(
        title='功效宣称证据锚点：阴性结果、边缘结果和不一致结果也必须保留',
        content='数字人用于生成报告和宣称结论时，必须保留阴性结果、边缘结果和相互不一致的终点结果，不能只抽取有利结论。否则会破坏证据完整性，并在审计时形成选择性报告风险。',
        summary='功效宣称专题的证据锚点：不能只保留正向结论。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='efficacy-claims:method:retain-negative-and-inconsistent-results',
        namespace='cnkis',
        tags=['功效宣称', '阴性结果', '证据完整性'],
        package_id='efficacy_claims',
        canonical_topic='功效宣称',
        facet='reporting_templates',
    ),
    RawKnowledgeInput(
        title='设备故障法规锚点：故障期间产生的数据必须先隔离再判定可用性',
        content='设备故障、校准失败、维修后恢复等情形下，相关数据不得默认继续使用。数字人必须先将受影响数据标记为待判定状态，再根据故障时间窗、影响终点、替代测量和复测情况决定是否纳入正式分析。',
        summary='设备故障专题的法规锚点：故障期间数据必须先隔离。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='equipment-failure:regulation:data-quarantine-during-failure',
        namespace='cnkis',
        tags=['设备故障', '数据隔离', '法规锚点'],
        package_id='equipment_failure',
        canonical_topic='设备故障',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='设备故障法规锚点：维修后重新投入使用前必须完成验证与放行',
        content='研究关键仪器维修、部件更换或软件升级后，不能直接回到研究使用状态。数字人必须核查是否完成功能验证、校准确认、状态变更审批和恢复放行记录，否则一律视为未恢复可用。',
        summary='设备故障专题的法规锚点：维修后必须验证放行。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='equipment-failure:regulation:post-repair-release-validation',
        namespace='cnkis',
        tags=['设备故障', '恢复放行', '验证'],
        package_id='equipment_failure',
        canonical_topic='设备故障',
        facet='sop_risks',
    ),
    RawKnowledgeInput(
        title='设备故障方法锚点：备用仪器启用必须校验方法等同性',
        content='启用备用仪器时，数字人不能只看“型号相近”或“功能相同”。至少要核查关键参数范围、校准状态、测量原理、输出单位和历史偏差，确保方法等同性，否则必须在报告中标识来源差异。',
        summary='设备故障专题的方法锚点：备用仪器需要方法等同性验证。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='equipment-failure:method:backup-device-equivalence',
        namespace='cnkis',
        tags=['设备故障', '备用仪器', '等同性'],
        package_id='equipment_failure',
        canonical_topic='设备故障',
        facet='instrument_methods',
    ),
    RawKnowledgeInput(
        title='设备故障方法锚点：停机影响范围必须映射到受试者、时间窗和终点',
        content='数字人要从故障日志反推影响范围，而不是笼统记录“设备异常”。至少要输出受影响受试者、受影响时间窗、受影响终点、是否存在替代测量和是否需要重测，才能支撑后续偏差评估。',
        summary='设备故障专题的方法锚点：故障影响范围映射。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='equipment-failure:method:impact-window-subject-endpoint-map',
        namespace='cnkis',
        tags=['设备故障', '影响范围', '终点映射'],
        package_id='equipment_failure',
        canonical_topic='设备故障',
        facet='key_metrics',
    ),
    RawKnowledgeInput(
        title='设备故障方法锚点：校准失败、漂移超限与读数异常应区分处理',
        content='数字人不能把所有仪器异常都归成“故障”。校准失败、长期漂移、单次读数异常和通讯故障的处置策略不同，应分别决定是否重测、复核、停机或启动维修工单。',
        summary='设备故障专题的方法锚点：异常类型分流处置。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='equipment-failure:method:failure-type-triage',
        namespace='cnkis',
        tags=['设备故障', '异常分流', '校准失败'],
        package_id='equipment_failure',
        canonical_topic='设备故障',
        facet='faq_misconceptions',
    ),
    RawKnowledgeInput(
        title='设备故障证据锚点：故障闭环必须包含发现、隔离、评估、恢复与复盘五段记录',
        content='只有维修记录不算闭环。数字人应要求故障闭环至少形成五段证据：发现、隔离、影响评估、恢复验证、复盘改进；缺失其中任一段都应提示质量经理复核。',
        summary='设备故障专题的证据锚点：五段式闭环记录。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='equipment-failure:method:five-stage-closure-record',
        namespace='cnkis',
        tags=['设备故障', '闭环记录', '复盘'],
        package_id='equipment_failure',
        canonical_topic='设备故障',
        facet='reporting_templates',
    ),
    RawKnowledgeInput(
        title='法规合规法规锚点：法规、方案、SOP、对外口径必须保持一致性',
        content='数字人不能只验证单个文档是否看起来合规，更要检查法规要求、研究方案、内部 SOP、报告结论和客户对外口径是否一致。若四者不一致，必须优先标为合规风险而不是生成结论。',
        summary='法规合规专题的法规锚点：法规、方案、SOP 和对外口径一致性。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='regulatory-compliance:regulation:cross-document-consistency',
        namespace='cnkis',
        tags=['法规合规', '一致性', '法规锚点'],
        package_id='regulatory_compliance',
        canonical_topic='法规合规',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='法规合规方法锚点：监管检查视角下的高风险缺口优先级',
        content='数字人应把高风险缺口优先级统一排序：受试者安全 > 数据完整性 > 虚假宣传 > 审计追踪缺失 > 文件一致性偏差 > 表述优化问题。这样可以避免把低风险文案问题排在关键合规缺口之前。',
        summary='法规合规专题的方法锚点：监管视角的缺口优先级。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='regulatory-compliance:method:risk-priority-order',
        namespace='cnkis',
        tags=['法规合规', '风险优先级', '检查视角'],
        package_id='regulatory_compliance',
        canonical_topic='法规合规',
        facet='key_metrics',
    ),
    RawKnowledgeInput(
        title='报告合规法规锚点：结论、表格、附件与原始数据引用链必须可追溯',
        content='任何报告结论都必须能够回溯到对应终点、统计输出、受试者集和原始记录。数字人在生成或审核报告时，必须同时检查结论句、统计表、图表编号、附件引用和原始数据编号是否一致。',
        summary='报告合规专题的法规锚点：报告引用链必须可追溯。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='report-compliance:regulation:traceable-evidence-chain',
        namespace='cnkis',
        tags=['报告合规', '可追溯', '引用链'],
        package_id='report_compliance',
        canonical_topic='报告合规',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='报告合规法规锚点：负面结果、偏差和限制条件不得省略',
        content='报告的合规性不只是“有结果”，还包括如实保留偏差、限制条件、阴性结果和边缘结果。数字人若发现报告仅保留正向结论、删除限制条件，必须标记为高风险返工项。',
        summary='报告合规专题的法规锚点：不能省略负面结果与限制条件。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='report-compliance:regulation:retain-limitations-and-negative-results',
        namespace='cnkis',
        tags=['报告合规', '阴性结果', '限制条件'],
        package_id='report_compliance',
        canonical_topic='报告合规',
        facet='claim_boundary',
    ),
    RawKnowledgeInput(
        title='报告合规方法锚点：图表、统计表与结论句的一致性校验清单',
        content='数字人审核报告时，至少要校验统计量、样本量、时间点、终点名称、单位和显著性符号在图表、统计表和结论句中的一致性。任何一项不一致都可能导致客户误读或监管质疑。',
        summary='报告合规专题的方法锚点：图表与结论一致性校验。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='report-compliance:method:table-figure-conclusion-consistency',
        namespace='cnkis',
        tags=['报告合规', '一致性校验', '图表'],
        package_id='report_compliance',
        canonical_topic='报告合规',
        facet='reporting_templates',
    ),
    RawKnowledgeInput(
        title='报告合规方法锚点：结论措辞必须匹配研究设计与分析集',
        content='数字人不能在探索性研究、开放标签研究或小样本分析中使用过强结论。结论力度必须与研究设计、对照方式、分析集和缺失数据处理方法匹配，否则会造成交付过度承诺。',
        summary='报告合规专题的方法锚点：结论力度匹配研究设计。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='report-compliance:method:conclusion-strength-fit-design',
        namespace='cnkis',
        tags=['报告合规', '研究设计', '结论强度'],
        package_id='report_compliance',
        canonical_topic='报告合规',
        facet='study_design',
    ),
    RawKnowledgeInput(
        title='报告合规方法锚点：报告版本、返工原因与签发状态必须结构化记录',
        content='返工管理不能只留邮件往来。数字人应要求报告版本、返工原因、修订位置、责任角色、重新审核状态和最终签发状态结构化留痕，才能支撑客户沟通与质量复盘。',
        summary='报告合规专题的方法锚点：返工与签发结构化留痕。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='report-compliance:method:revision-and-approval-log',
        namespace='cnkis',
        tags=['报告合规', '版本管理', '返工'],
        package_id='report_compliance',
        canonical_topic='报告合规',
        facet='sop_risks',
    ),
    RawKnowledgeInput(
        title='报告合规证据锚点：引用原文、统计输出与客户话术三层对照模板',
        content='为防止报告、摘要和客户话术发生漂移，数字人应建立三层对照：原始证据、统计输出、交付口径。只有三层保持一致，才允许生成最终对外表达。',
        summary='报告合规专题的证据锚点：三层对照模板。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='report-compliance:method:three-layer-alignment-template',
        namespace='cnkis',
        tags=['报告合规', '对照模板', '客户话术'],
        package_id='report_compliance',
        canonical_topic='报告合规',
        facet='faq_misconceptions',
    ),
    RawKnowledgeInput(
        title='现场异常法规锚点：环境超限时先止损再判断是否继续研究',
        content='温湿度、照射强度、设备状态或样本条件超出方案允许范围时，数字人首先要触发止损与隔离动作，而不是先判断“是否还能凑合继续”。继续研究必须建立在风险评估和授权放行之后。',
        summary='现场异常专题的法规锚点：环境超限先止损。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='site-incident:regulation:stop-loss-before-continue',
        namespace='cnkis',
        tags=['现场异常', '环境超限', '止损'],
        package_id='site_incident',
        canonical_topic='现场异常',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='现场异常法规锚点：异常恢复必须有复核人与恢复条件',
        content='现场异常不能仅凭执行人员口头判断恢复。数字人应要求明确恢复条件、复核角色、受影响范围和恢复时间点，并把“异常结束”与“恢复可用”分成两个独立状态管理。',
        summary='现场异常专题的法规锚点：恢复必须有条件与复核。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='site-incident:regulation:resume-with-conditions-and-review',
        namespace='cnkis',
        tags=['现场异常', '恢复条件', '复核'],
        package_id='site_incident',
        canonical_topic='现场异常',
        facet='sop_risks',
    ),
    RawKnowledgeInput(
        title='现场异常方法锚点：异常分级必须区分安全、合规、数据和客户影响',
        content='现场异常不应只按“轻微/严重”口语化处理。数字人应分别给出受试者安全影响、合规影响、数据影响和客户交付影响，再汇总为综合处置级别。',
        summary='现场异常专题的方法锚点：四维异常分级。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='site-incident:method:four-dimension-severity',
        namespace='cnkis',
        tags=['现场异常', '分级', '影响维度'],
        package_id='site_incident',
        canonical_topic='现场异常',
        facet='key_metrics',
    ),
    RawKnowledgeInput(
        title='现场异常方法锚点：暂停、继续、重测、废弃数据的判定树',
        content='数字人需要输出明确判定树，而不是仅提示“请人工判断”。异常出现后至少要判断：是否立即暂停、是否允许继续、是否需要重测、既有数据是否废弃，以及是否触发客户通知。',
        summary='现场异常专题的方法锚点：暂停/继续/重测/废弃的判定树。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='site-incident:method:pause-continue-retest-discard-tree',
        namespace='cnkis',
        tags=['现场异常', '判定树', '重测'],
        package_id='site_incident',
        canonical_topic='现场异常',
        facet='study_design',
    ),
    RawKnowledgeInput(
        title='现场异常证据锚点：异常通报模板必须包含影响范围和下一步动作',
        content='现场异常通报不能只有“发生了什么”，还必须写明受影响对象、当前控制措施、下一步动作、预计恢复时间和责任角色。否则客户、QA 和项目团队无法形成协同闭环。',
        summary='现场异常专题的证据锚点：异常通报模板。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='site-incident:method:incident-notice-template',
        namespace='cnkis',
        tags=['现场异常', '通报模板', '影响范围'],
        package_id='site_incident',
        canonical_topic='现场异常',
        facet='reporting_templates',
    ),
    RawKnowledgeInput(
        title='受试者权益法规锚点：退出研究的权利不得附加惩罚性条件',
        content='受试者有权在任何阶段退出研究，退出不应附加惩罚性条件，也不应影响其已获得的合理服务和已说明的补偿安排。数字人不能为了留存率而弱化退出权或设置隐性障碍。',
        summary='受试者权益专题的法规锚点：退出权不得被弱化。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='subject-rights:regulation:withdrawal-right-no-penalty',
        namespace='cnkis',
        tags=['受试者权益', '退出权', '法规锚点'],
        package_id='subject_rights',
        canonical_topic='受试者权益',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='受试者权益法规锚点：隐私、样本、照片和附加数据用途必须分别授权',
        content='数字人不能把所有授权理解为一个总勾选。个人信息、研究样本、照片/影像、附加分析用途和后续再利用应分别识别授权边界，超出范围即需重新授权或人工介入。',
        summary='受试者权益专题的法规锚点：数据与样本授权边界分离。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='subject-rights:regulation:separate-consent-boundaries',
        namespace='cnkis',
        tags=['受试者权益', '隐私', '授权边界'],
        package_id='subject_rights',
        canonical_topic='受试者权益',
        facet='claim_boundary',
    ),
    RawKnowledgeInput(
        title='受试者权益法规锚点：脆弱受试者需更高解释义务与保护措施',
        content='涉及未成年人、认知能力受限者、强依赖关系人群或其他脆弱受试者时，数字人应自动提高解释义务和保护门槛，触发监护人、见证人或额外人工复核流程，而不是沿用普通流程。',
        summary='受试者权益专题的法规锚点：脆弱受试者保护要求更高。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='subject-rights:regulation:vulnerable-subject-protection',
        namespace='cnkis',
        tags=['受试者权益', '脆弱受试者', '保护措施'],
        package_id='subject_rights',
        canonical_topic='受试者权益',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='受试者权益方法锚点：知情同意理解确认的最小核查清单',
        content='签字不等于理解。数字人应至少核查研究目的、主要流程、潜在风险、退出权、隐私边界和联系人机制是否被受试者正确复述，否则不能视为真正完成理解确认。',
        summary='受试者权益专题的方法锚点：理解确认清单。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='subject-rights:method:comprehension-checklist',
        namespace='cnkis',
        tags=['受试者权益', '知情同意', '理解确认'],
        package_id='subject_rights',
        canonical_topic='受试者权益',
        facet='core_concepts',
    ),
    RawKnowledgeInput(
        title='受试者权益方法锚点：投诉、撤回、隐私请求的升级路径',
        content='数字人应把投诉、撤回请求、数据删除请求、照片撤授权和补偿争议视为不同类型事件，分别给出升级路径、处理时限和责任角色，而不是统一转成一类客服事项。',
        summary='受试者权益专题的方法锚点：权益请求分型升级。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='subject-rights:method:rights-request-routing',
        namespace='cnkis',
        tags=['受试者权益', '投诉', '升级路径'],
        package_id='subject_rights',
        canonical_topic='受试者权益',
        facet='sop_risks',
    ),
    RawKnowledgeInput(
        title='受试者权益方法锚点：权益事件留痕的最小字段',
        content='任何权益相关事件至少应记录：发起人、事件类型、发生时间、授权状态、受影响数据/样本、已采取动作、处理结论和复核人。少于这些字段，后续争议和审计都无法稳定支撑。',
        summary='受试者权益专题的方法锚点：权益事件留痕字段。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='subject-rights:method:min-fields-rights-event-log',
        namespace='cnkis',
        tags=['受试者权益', '留痕字段', '审计'],
        package_id='subject_rights',
        canonical_topic='受试者权益',
        facet='key_metrics',
    ),
    RawKnowledgeInput(
        title='受试者权益证据锚点：ICF版本、解释记录和签署状态三联一致',
        content='数字人必须同时核查 ICF 版本、解释记录和签署状态三者是否一致。若版本不一致、解释时间晚于签署时间或缺少见证/监护记录，则应立即视为高风险权益缺口。',
        summary='受试者权益专题的证据锚点：ICF 三联一致性。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='subject-rights:method:icf-version-explanation-signature-alignment',
        namespace='cnkis',
        tags=['受试者权益', 'ICF', '一致性'],
        package_id='subject_rights',
        canonical_topic='受试者权益',
        facet='reporting_templates',
    ),
    RawKnowledgeInput(
        title='研究设计统计法规锚点：主要终点、样本量与分析方法必须在研究前锁定',
        content='主要终点、样本量计算基础和主要分析方法必须在研究实施前锁定并版本受控，不能在看到数据后再回填。数字人若发现终点、样本量或主要方法的事后变更，应标记为高风险统计偏差。',
        summary='研究设计与统计分析专题的法规锚点：前置锁定原则。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='study-design:regulation:endpoint-sample-method-prelock',
        namespace='cnkis',
        tags=['研究设计', '统计分析', '前置锁定'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='研究设计统计法规锚点：盲态保持、揭盲控制与数据库锁定顺序',
        content='数字人应把盲态保持、数据库锁定、SAP 锁定和揭盲顺序视为刚性控制链。任何先揭盲、后补 SAP 或后锁库的行为，都应作为高优先级统计合规风险上报。',
        summary='研究设计与统计分析专题的法规锚点：盲态、锁库与揭盲顺序。',
        entry_type='regulation',
        source_type='specialist_anchor_seed',
        source_key='study-design:regulation:blinding-lock-unblind-order',
        namespace='cnkis',
        tags=['研究设计', '盲态', '锁库'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='study_design',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：样本量计算必须明确效应值、方差和脱落率来源',
        content='数字人审核样本量时，至少要看到目标效应值、方差估计、显著性水平、把握度和脱落率来源。只有最终数字、没有假设来源的样本量，不应被视为可审计设计。',
        summary='研究设计与统计分析专题的方法锚点：样本量假设来源必须明确。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:sample-size-assumption-traceability',
        namespace='cnkis',
        tags=['研究设计', '样本量', '可追溯'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='key_metrics',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：随机化方案应匹配样本规模与异质性',
        content='数字人不能默认所有研究都用简单随机。应根据样本规模、中心数、皮肤类型异质性和关键基线变量判断是否使用区组随机、分层随机或自身对照设计。',
        summary='研究设计与统计分析专题的方法锚点：随机化设计匹配原则。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:randomization-fit-for-heterogeneity',
        namespace='cnkis',
        tags=['研究设计', '随机化', '异质性'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='study_design',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：分析集定义必须与偏差、脱落和依从性联动',
        content='FAS、PP、SS 等分析集不能只写缩写。数字人应能追溯每个受试者进入或退出分析集的原因，并把偏差、脱落和依从性问题映射到分析集定义上。',
        summary='研究设计与统计分析专题的方法锚点：分析集定义联动偏差与脱落。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:analysis-set-linked-to-deviation-dropout',
        namespace='cnkis',
        tags=['研究设计', '分析集', '偏差'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='sop_risks',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：缺失数据处理策略必须与缺失机制相匹配',
        content='数字人不得把 LOCF 作为默认万能方案。应先判断缺失更接近 MCAR、MAR 还是 MNAR，再决定使用混合模型、多重插补、敏感性分析或其他策略，并明确限制条件。',
        summary='研究设计与统计分析专题的方法锚点：缺失机制与处理策略匹配。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:missingness-mechanism-fit',
        namespace='cnkis',
        tags=['研究设计', '缺失数据', '统计策略'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='faq_misconceptions',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：多重比较控制策略必须预先写入 SAP',
        content='多个主要终点、多个时间点或多个亚组分析时，数字人必须核查多重比较控制策略是否预先定义。若只在结果阶段临时补加 Bonferroni 或选择性汇报，则应视为统计质量缺口。',
        summary='研究设计与统计分析专题的方法锚点：多重比较策略预定义。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:multiplicity-plan-predefined',
        namespace='cnkis',
        tags=['研究设计', '多重比较', 'SAP'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='study_design',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：效应量与置信区间必须和 p 值同时报告',
        content='仅报告 p 值不足以支撑专业数字人的结论强度控制。数字人应强制同时输出效应量、95%CI 和临床/业务意义解读，避免把“统计学显著”误当成“业务上充分显著”。',
        summary='研究设计与统计分析专题的方法锚点：效应量、置信区间与 p 值并报。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:effect-size-ci-with-pvalue',
        namespace='cnkis',
        tags=['研究设计', '效应量', '置信区间'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='reporting_templates',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：敏感性分析用于检验结论稳健性而非补救主结果',
        content='数字人应把敏感性分析作为稳健性验证工具，而不是在主结果不理想时寻找替代结论的补救工具。若主结果、敏感性分析和亚组结论明显不一致，必须明确披露而非择优选取。',
        summary='研究设计与统计分析专题的方法锚点：敏感性分析的正确用途。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:sensitivity-analysis-purpose',
        namespace='cnkis',
        tags=['研究设计', '敏感性分析', '稳健性'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='faq_misconceptions',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：自身对照设计需额外防范交叉污染与部位差异',
        content='半脸对照、双臂对照等自身对照设计虽然能提高效率，但数字人必须额外核查交叉污染、左右部位基线差异、使用顺序偏差和受试者操作一致性。',
        summary='研究设计与统计分析专题的方法锚点：自身对照设计的附加风险。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:within-subject-design-risks',
        namespace='cnkis',
        tags=['研究设计', '自身对照', '偏差风险'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='sop_risks',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：盲态评估需要验证是否真正未破盲',
        content='数字人应将盲态设计与盲态有效性分开判断。若产品气味、质地、颜色或操作差异明显，应增加盲态保持措施并考虑设置破盲风险评估，而不是默认“双盲”名义就足够。',
        summary='研究设计与统计分析专题的方法锚点：盲态有效性验证。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:blinding-effectiveness-check',
        namespace='cnkis',
        tags=['研究设计', '盲态', '破盲风险'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='study_design',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：中期检查、期中分析和运营监控不得混用',
        content='数字人应区分运营层面的入组/执行监控与统计意义上的期中分析。任何会接触终点趋势或疗效差异的中期分析，都必须有预定义方案和权限控制。',
        summary='研究设计与统计分析专题的方法锚点：中期分析与运营监控区分。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:interim-analysis-vs-ops-monitoring',
        namespace='cnkis',
        tags=['研究设计', '期中分析', '权限控制'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='regulation_boundary',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：非劣效界值必须有临床与业务双重依据',
        content='数字人不能接受“行业常用”作为非劣效界值的唯一依据。应同时说明临床/业务可接受差异、历史证据来源和统计假设，否则非劣效结论不具说服力。',
        summary='研究设计与统计分析专题的方法锚点：非劣效界值的双重依据。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:noninferiority-margin-justification',
        namespace='cnkis',
        tags=['研究设计', '非劣效', '界值'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='key_metrics',
    ),
    RawKnowledgeInput(
        title='研究设计统计方法锚点：统计编程、输出复核与报告引用需三方分离',
        content='数字人支持统计交付时，应要求统计编程、结果复核和报告引用至少逻辑分离，避免同一输出未经复核直接进入客户报告。这样才能降低公式错误、版本错配和复制失误风险。',
        summary='研究设计与统计分析专题的方法锚点：编程、复核、引用三方分离。',
        entry_type='method_reference',
        source_type='specialist_anchor_seed',
        source_key='study-design:method:program-review-report-separation',
        namespace='cnkis',
        tags=['研究设计', '统计编程', '复核'],
        package_id='pkg_study_design_statistics',
        canonical_topic='研究设计与统计分析',
        facet='reporting_templates',
    ),
])


class Command(BaseCommand):
    help = '为薄弱专题包补充权威锚点，优先修复类型失衡和证据链缺口'

    def add_arguments(self, parser):
        parser.add_argument(
            '--disable-llm-enrich',
            action='store_true',
            help='关闭 LLM 富化，走稳定规则管线',
        )

    def handle(self, *args, **options):
        if options.get('disable_llm_enrich'):
            import apps.knowledge.ingestion_pipeline as pipeline_module

            pipeline_module._LLM_ENRICH_ENABLED = False
            self.stdout.write('已关闭 LLM 富化，使用稳定规则管线落库。')

        created = 0
        skipped = 0
        errors = 0

        for raw in SEEDS:
            existed_before = KnowledgeEntry.objects.filter(
                source_type=raw.source_type,
                source_key=raw.source_key,
                is_deleted=False,
            ).exists()
            try:
                result = run_pipeline(raw)
            except Exception as exc:
                self.stdout.write(self.style.ERROR(f'  ✗ 失败: {raw.title} | {exc}'))
                errors += 1
                continue

            if result and result.entry_id:
                KnowledgeEntry.objects.filter(id=result.entry_id).update(
                    status='published',
                    is_published=True,
                )

            if result and result.entry_id and not existed_before:
                self.stdout.write(self.style.SUCCESS(f'  ✓ [{result.entry_id}] {raw.title}'))
                created += 1
            else:
                self.stdout.write(f'  - 跳过（已存在）: {raw.title}')
                skipped += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'权威锚点补充完成: created={created} skipped={skipped} errors={errors}'
            )
        )
