# Generated by Django 4.2.27 on 2026-03-18 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EkbAttachmentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(db_index=True, max_length=200, verbose_name='单据ID')),
                ('attachment_id', models.CharField(max_length=200, unique=True, verbose_name='附件ID')),
                ('file_name', models.CharField(max_length=500, verbose_name='文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(bytes)')),
                ('file_type', models.CharField(blank=True, default='', max_length=50, verbose_name='文件类型')),
                ('local_path', models.CharField(blank=True, default='', max_length=1000, verbose_name='本地存储路径')),
                ('download_status', models.CharField(default='pending', help_text='pending/downloaded/failed', max_length=20, verbose_name='下载状态')),
                ('checksum', models.CharField(blank=True, default='', max_length=64, verbose_name='文件指纹SHA256')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '易快报附件索引',
                'db_table': 't_ekb_attachment_index',
            },
        ),
        migrations.CreateModel(
            name='EkbConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='数据模块')),
                ('ekb_id', models.CharField(max_length=200, verbose_name='易快报内部ID')),
                ('conflict_type', models.CharField(choices=[('exact_id', '编号精确匹配'), ('exact_name', '名称精确匹配'), ('fuzzy_name', '名称相似匹配'), ('duplicate', '易快报内部重复'), ('dual_track', '双轨期间人工录入重复')], max_length=30, verbose_name='冲突类型')),
                ('similarity_score', models.FloatField(default=1.0, help_text='0.0~1.0，精确匹配为1.0', verbose_name='相似度')),
                ('ekb_data', models.JSONField(verbose_name='易快报数据')),
                ('existing_record_id', models.IntegerField(blank=True, null=True, verbose_name='新系统已有记录ID')),
                ('existing_table', models.CharField(blank=True, default='', max_length=100, verbose_name='新系统表名')),
                ('existing_data', models.JSONField(default=dict, verbose_name='新系统已有数据')),
                ('diff_fields', models.JSONField(default=list, help_text='[{"field": "name", "ekb": "A", "existing": "B"}]', verbose_name='差异字段')),
                ('resolution', models.CharField(choices=[('pending', '待审核'), ('use_ekb', '使用易快报数据'), ('use_existing', '保留现有数据'), ('manual_merge', '人工合并后注入'), ('skip', '跳过不注入')], default='pending', max_length=20, verbose_name='处理决策')),
                ('resolved_by_id', models.IntegerField(blank=True, null=True, verbose_name='处理人ID')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='处理备注')),
                ('merged_data', models.JSONField(blank=True, default=dict, help_text='manual_merge 时填写最终要注入的数据', verbose_name='合并后数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '易快报数据冲突',
                'db_table': 't_ekb_conflict',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='EkbImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(help_text='格式: YYYYMMDD_HHMMSS，如 20260318_143000', max_length=50, unique=True, verbose_name='批次号')),
                ('phase', models.CharField(default='', help_text='phase0/phase1/phase2/phase3/phase4/incremental', max_length=20, verbose_name='采集阶段')),
                ('status', models.CharField(choices=[('collecting', '采集中'), ('collected', '采集完成'), ('injecting', '注入中'), ('injected', '注入完成'), ('partial', '部分注入'), ('rolled_back', '已回滚'), ('failed', '失败')], default='collecting', max_length=20, verbose_name='状态')),
                ('modules', models.JSONField(default=list, verbose_name='采集模块列表')),
                ('module_stats', models.JSONField(default=dict, verbose_name='各模块记录数')),
                ('backup_path', models.CharField(blank=True, default='', help_text='相对 backend/ 的路径', max_length=500, verbose_name='JSON备份目录')),
                ('total_records', models.IntegerField(default=0, verbose_name='总记录数')),
                ('injected_records', models.IntegerField(default=0, verbose_name='已注入记录数')),
                ('conflict_count', models.IntegerField(default=0, verbose_name='冲突记录数')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳过记录数')),
                ('operator', models.CharField(blank=True, default='system', max_length=100, verbose_name='操作人')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='采集完成时间')),
                ('injected_at', models.DateTimeField(blank=True, null=True, verbose_name='注入完成时间')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='回滚时间')),
            ],
            options={
                'verbose_name': '易快报导入批次',
                'db_table': 't_ekb_import_batch',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='EkbSyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, unique=True, verbose_name='数据模块')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='上次同步时间')),
                ('last_batch_no', models.CharField(blank=True, default='', max_length=50, verbose_name='上次批次号')),
                ('last_record_count', models.IntegerField(default=0, verbose_name='上次同步记录数')),
                ('consecutive_stable_days', models.IntegerField(default=0, help_text='双轨期间连续 N 天对账差异为0时，建议切换到新系统为主', verbose_name='连续稳定对账天数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '易快报同步检查点',
                'db_table': 't_ekb_sync_checkpoint',
            },
        ),
        migrations.CreateModel(
            name='EkbRawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='corporation/departments/staffs/flows/budgets/...', max_length=50, verbose_name='数据模块')),
                ('ekb_id', models.CharField(help_text='易快报系统中的原始记录 ID', max_length=200, verbose_name='易快报内部ID')),
                ('raw_data', models.JSONField(help_text='完整原始字段，不做任何加工', verbose_name='原始数据')),
                ('scraped_at', models.DateTimeField(verbose_name='采集时间')),
                ('checksum', models.CharField(help_text='SHA256(json.dumps(raw_data, sort_keys=True))', max_length=64, verbose_name='数据指纹')),
                ('source_updated_at', models.DateTimeField(blank=True, help_text='易快报记录的 updateTime 字段（用于增量判断）', null=True, verbose_name='源数据更新时间')),
                ('injection_status', models.CharField(default='pending', help_text='pending/injected/skipped/conflict/failed', max_length=20, verbose_name='注入状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='ekuaibao_integration.ekbimportbatch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '易快报原始数据',
                'db_table': 't_ekb_raw_record',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='EkbInjectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='数据模块')),
                ('ekb_id', models.CharField(max_length=200, verbose_name='易快报内部ID')),
                ('target_table', models.CharField(help_text='如 t_expense_request / t_project_budget / t_subject_payment', max_length=100, verbose_name='目标表名')),
                ('target_id', models.IntegerField(help_text='注入后在业务表中的主键', verbose_name='目标记录ID')),
                ('action', models.CharField(choices=[('created', '新建'), ('updated', '更新'), ('linked', '关联')], max_length=20, verbose_name='注入操作')),
                ('target_workstation', models.CharField(blank=True, default='', help_text='finance/research/recruitment/hr/execution/quality', max_length=30, verbose_name='目标工作台')),
                ('before_data', models.JSONField(default=dict, help_text='action=updated 时保存被覆盖字段的原值；action=created 时为空 dict', verbose_name='注入前数据快照')),
                ('after_data', models.JSONField(default=dict, verbose_name='注入数据')),
                ('rolled_back', models.BooleanField(default=False, verbose_name='已回滚')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='回滚时间')),
                ('rollback_by', models.CharField(blank=True, default='', max_length=100, verbose_name='回滚操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injection_logs', to='ekuaibao_integration.ekbimportbatch', verbose_name='所属批次')),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='injection_logs', to='ekuaibao_integration.ekbrawrecord', verbose_name='原始记录')),
            ],
            options={
                'verbose_name': '易快报注入日志',
                'db_table': 't_ekb_injection_log',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='ekbimportbatch',
            index=models.Index(fields=['batch_no'], name='ekb_batch_no_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbimportbatch',
            index=models.Index(fields=['status', 'create_time'], name='ekb_batch_status_idx'),
        ),
        migrations.AddField(
            model_name='ekbconflict',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='ekuaibao_integration.ekbimportbatch', verbose_name='所属批次'),
        ),
        migrations.AddField(
            model_name='ekbconflict',
            name='raw_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='ekuaibao_integration.ekbrawrecord', verbose_name='原始记录'),
        ),
        migrations.AddField(
            model_name='ekbattachmentindex',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='ekuaibao_integration.ekbimportbatch', verbose_name='所属批次'),
        ),
        migrations.AddIndex(
            model_name='ekbrawrecord',
            index=models.Index(fields=['batch', 'module'], name='ekb_raw_batch_module_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbrawrecord',
            index=models.Index(fields=['module', 'ekb_id'], name='ekb_raw_module_id_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbrawrecord',
            index=models.Index(fields=['checksum'], name='ekb_raw_checksum_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbrawrecord',
            index=models.Index(fields=['module', 'injection_status'], name='ekb_raw_inject_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbinjectionlog',
            index=models.Index(fields=['batch', 'module'], name='ekb_inj_batch_mod_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbinjectionlog',
            index=models.Index(fields=['target_table', 'target_id'], name='ekb_inj_target_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbinjectionlog',
            index=models.Index(fields=['rolled_back', 'create_time'], name='ekb_inj_rollback_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbinjectionlog',
            index=models.Index(fields=['ekb_id'], name='ekb_inj_ekb_id_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbinjectionlog',
            index=models.Index(fields=['target_workstation'], name='ekb_inj_workstation_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbconflict',
            index=models.Index(fields=['batch', 'module'], name='ekb_conflict_batch_mod_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbconflict',
            index=models.Index(fields=['resolution'], name='ekb_conflict_resolution_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbconflict',
            index=models.Index(fields=['module', 'conflict_type'], name='ekb_conflict_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbattachmentindex',
            index=models.Index(fields=['flow_id'], name='ekb_att_flow_idx'),
        ),
        migrations.AddIndex(
            model_name='ekbattachmentindex',
            index=models.Index(fields=['attachment_id'], name='ekb_att_id_idx'),
        ),
    ]
