# Generated by Django 4.2.27 on 2026-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekuaibao_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkbWebSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_id', models.CharField(max_length=100, unique=True, verbose_name='企业ID')),
                ('web_token', models.CharField(max_length=500, verbose_name='Web Session Token')),
                ('feishu_open_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书 open_id')),
                ('feishu_staff_name', models.CharField(blank=True, default='', max_length=100, verbose_name='员工姓名')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token 过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '易快报飞书版会话',
                'db_table': 't_ekb_web_session',
            },
        ),
    ]
