# Generated by Django 4.2.27 on 2026-02-15 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('display_name', models.CharField(default='', max_length=100, verbose_name='显示名称')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('avatar', models.URLField(blank=True, default='', verbose_name='头像URL')),
                ('account_type', models.CharField(choices=[('internal', '内部员工'), ('subject', '受试者'), ('external', '外部客户'), ('system', '系统账号')], default='internal', max_length=20, verbose_name='账号类型')),
                ('status', models.CharField(choices=[('active', '激活'), ('inactive', '未激活'), ('locked', '锁定'), ('disabled', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('password_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='密码哈希')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='多因素认证')),
                ('mfa_secret', models.CharField(blank=True, default='', max_length=100, verbose_name='MFA密钥')),
                ('feishu_user_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='飞书用户ID')),
                ('feishu_open_id', models.CharField(blank=True, default='', max_length=100, verbose_name='飞书OpenID')),
                ('wechat_openid', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='微信OpenID')),
                ('wechat_unionid', models.CharField(blank=True, default='', max_length=100, verbose_name='微信UnionID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '账号',
                'db_table': 't_account',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('function', models.CharField(max_length=50, verbose_name='功能')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('scope', models.CharField(blank=True, default='*', max_length=50, verbose_name='作用域')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '权限',
                'db_table': 't_permission',
                'unique_together': {('module', 'function', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统预置')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='identity.role')),
            ],
            options={
                'verbose_name': '角色',
                'db_table': 't_role',
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255, unique=True, verbose_name='Token哈希')),
                ('device_info', models.CharField(blank=True, default='', max_length=200, verbose_name='设备信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='已撤销')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='identity.account')),
            ],
            options={
                'verbose_name': '会话令牌',
                'db_table': 't_session_token',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='identity.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='identity.role')),
            ],
            options={
                'db_table': 't_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='项目ID（项目级角色）')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_roles', to='identity.account')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_accounts', to='identity.role')),
            ],
            options={
                'db_table': 't_account_role',
                'unique_together': {('account', 'role')},
            },
        ),
    ]
