# Generated by Django 4.2.27 on 2026-03-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_accountworkstationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountworkstationconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
