# Generated by Django 4.2.27 on 2026-03-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_alter_accountworkstationconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ekuaibao_staff_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='易快报 staffs.id，格式如 nYA6xdjChA7c00:2102431421852322', max_length=200, verbose_name='易快报员工ID'),
        ),
        migrations.AddField(
            model_name='account',
            name='ekuaibao_username',
            field=models.CharField(blank=True, default='', help_text='易快报 staffs.code，如 zhuyan', max_length=100, verbose_name='易快报用户名'),
        ),
    ]
